# Generated by Django 5.2.5 on 2025-10-10 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_ru', models.TextField(verbose_name='Support (Russian)')),
                ('support_ky', models.TextField(verbose_name='Support (Kyrgyz)')),
                ('support_en', models.TextField(verbose_name='Support (English)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Additional Support',
                'verbose_name_plural': 'Additional Support',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(verbose_name='Step number')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Title (Russian)')),
                ('title_ky', models.CharField(max_length=200, verbose_name='Title (Kyrgyz)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (English)')),
                ('description_ru', models.TextField(verbose_name='Description (Russian)')),
                ('description_ky', models.TextField(verbose_name='Description (Kyrgyz)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('color_scheme', models.CharField(default='from-blue-500 to-cyan-500', max_length=50, verbose_name='Color scheme')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Process Step',
                'verbose_name_plural': 'Process Steps',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='QuotaStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_type', models.CharField(choices=[('total_spots', 'Total Spots'), ('success_rate', 'Success Rate'), ('organizations', 'Organizations'), ('quota_types', 'Quota Types')], max_length=20, unique=True, verbose_name='Statistic Type')),
                ('number', models.CharField(max_length=20, verbose_name='Number/Value')),
                ('label_ru', models.CharField(max_length=200, verbose_name='Label (Russian)')),
                ('label_ky', models.CharField(max_length=200, verbose_name='Label (Kyrgyz)')),
                ('label_en', models.CharField(max_length=200, verbose_name='Label (English)')),
                ('description_ru', models.TextField(verbose_name='Description (Russian)')),
                ('description_ky', models.TextField(verbose_name='Description (Kyrgyz)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quota Statistics',
                'verbose_name_plural': 'Quota Statistics',
                'ordering': ['order', 'stat_type'],
            },
        ),
        migrations.CreateModel(
            name='QuotaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sports', 'Sports'), ('health', 'Health'), ('target', 'Target')], max_length=20, unique=True, verbose_name='Type')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Title (Russian)')),
                ('title_ky', models.CharField(max_length=200, verbose_name='Title (Kyrgyz)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (English)')),
                ('description_ru', models.TextField(verbose_name='Description (Russian)')),
                ('description_ky', models.TextField(verbose_name='Description (Kyrgyz)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('icon', models.CharField(max_length=10, verbose_name='Icon (emoji)')),
                ('spots', models.PositiveIntegerField(verbose_name='Available spots')),
                ('deadline', models.CharField(max_length=50, verbose_name='Application deadline')),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('cyan', 'Cyan'), ('purple', 'Purple'), ('orange', 'Orange')], default='blue', max_length=20, verbose_name='Color scheme')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quota Type',
                'verbose_name_plural': 'Quota Types',
                'ordering': ['order', 'type'],
            },
        ),
        migrations.CreateModel(
            name='QuotaRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_ru', models.TextField(verbose_name='Requirement (Russian)')),
                ('requirement_ky', models.TextField(verbose_name='Requirement (Kyrgyz)')),
                ('requirement_en', models.TextField(verbose_name='Requirement (English)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quota_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='admission.quotatype', verbose_name='Quota Type')),
            ],
            options={
                'verbose_name': 'Quota Requirement',
                'verbose_name_plural': 'Quota Requirements',
                'ordering': ['quota_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuotaBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_ru', models.TextField(verbose_name='Benefit (Russian)')),
                ('benefit_ky', models.TextField(verbose_name='Benefit (Kyrgyz)')),
                ('benefit_en', models.TextField(verbose_name='Benefit (English)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quota_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='admission.quotatype', verbose_name='Quota Type')),
            ],
            options={
                'verbose_name': 'Quota Benefit',
                'verbose_name_plural': 'Quota Benefits',
                'ordering': ['quota_type', 'order'],
            },
        ),
    ]
