# Generated by Django 5.1.2 on 2025-10-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AspirantDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name_ru', models.CharField(max_length=200, verbose_name='Document Name (Russian)')),
                ('document_name_ky', models.CharField(max_length=200, verbose_name='Document Name (Kyrgyz)')),
                ('document_name_en', models.CharField(max_length=200, verbose_name='Document Name (English)')),
                ('file', models.FileField(upload_to='master_documents/', verbose_name='File')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Master Document',
                'verbose_name_plural': 'Master Documents',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AspirantMainDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name_ru', models.CharField(max_length=200, verbose_name='Event Name (Russian)')),
                ('event_name_ky', models.CharField(max_length=200, verbose_name='Event Name (Kyrgyz)')),
                ('event_name_en', models.CharField(max_length=200, verbose_name='Event Name (English)')),
                ('date', models.CharField(max_length=100, verbose_name='Date/Period')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Master Main Date',
                'verbose_name_plural': 'Master Main Dates',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AspirantPrograms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name_ru', models.CharField(max_length=200, verbose_name='Program Name')),
                ('program_name_ky', models.CharField(max_length=200, verbose_name='Program Name')),
                ('program_name_en', models.CharField(max_length=200, verbose_name='Program Name')),
                ('description_ru', models.TextField(verbose_name='Description (Russian)')),
                ('description_ky', models.TextField(verbose_name='Description (Kyrgyz)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('features_ru', models.JSONField(verbose_name='Features (Russian)')),
                ('features_ky', models.JSONField(verbose_name='Features (Kyrgyz)')),
                ('features_en', models.JSONField(verbose_name='Features (English)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Master Program',
                'verbose_name_plural': 'Master Programs',
                'ordering': ['order', 'program_name_ru'],
            },
        ),
        migrations.CreateModel(
            name='AspirantRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Title (Russian)')),
                ('title_ky', models.CharField(max_length=200, verbose_name='Title (Kyrgyz)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (English)')),
                ('description_ru', models.TextField(verbose_name='Description (Russian)')),
                ('description_ky', models.TextField(verbose_name='Description (Kyrgyz)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Master Requirement',
                'verbose_name_plural': 'Master Requirements',
                'ordering': ['order', 'title_ru'],
            },
        ),
        migrations.CreateModel(
            name='MasterDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name_ru', models.CharField(max_length=200, verbose_name='Document Name (Russian)')),
                ('document_name_ky', models.CharField(max_length=200, verbose_name='Document Name (Kyrgyz)')),
                ('document_name_en', models.CharField(max_length=200, verbose_name='Document Name (English)')),
                ('file', models.FileField(upload_to='master_documents/', verbose_name='File')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Master Document',
                'verbose_name_plural': 'Master Documents',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MasterMainDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name_ru', models.CharField(max_length=200, verbose_name='Event Name (Russian)')),
                ('event_name_ky', models.CharField(max_length=200, verbose_name='Event Name (Kyrgyz)')),
                ('event_name_en', models.CharField(max_length=200, verbose_name='Event Name (English)')),
                ('date', models.CharField(max_length=100, verbose_name='Date/Period')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Master Main Date',
                'verbose_name_plural': 'Master Main Dates',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MasterPrograms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name_ru', models.CharField(max_length=200, verbose_name='Program Name')),
                ('program_name_ky', models.CharField(max_length=200, verbose_name='Program Name')),
                ('program_name_en', models.CharField(max_length=200, verbose_name='Program Name')),
                ('description_ru', models.TextField(verbose_name='Description (Russian)')),
                ('description_ky', models.TextField(verbose_name='Description (Kyrgyz)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('features_ru', models.JSONField(verbose_name='Features (Russian)')),
                ('features_ky', models.JSONField(verbose_name='Features (Kyrgyz)')),
                ('features_en', models.JSONField(verbose_name='Features (English)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Master Program',
                'verbose_name_plural': 'Master Programs',
                'ordering': ['order', 'program_name_ru'],
            },
        ),
        migrations.CreateModel(
            name='MasterRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Title (Russian)')),
                ('title_ky', models.CharField(max_length=200, verbose_name='Title (Kyrgyz)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (English)')),
                ('description_ru', models.TextField(verbose_name='Description (Russian)')),
                ('description_ky', models.TextField(verbose_name='Description (Kyrgyz)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Master Requirement',
                'verbose_name_plural': 'Master Requirements',
                'ordering': ['order', 'title_ru'],
            },
        ),
    ]
