# Generated by Django 5.1.2 on 2025-10-11 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_aspirantdocuments_aspirantmaindate_aspirantprograms_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aspirantdocuments',
            options={'ordering': ['order'], 'verbose_name': 'Aspirant  Document', 'verbose_name_plural': 'Aspirant Documents'},
        ),
        migrations.AlterModelOptions(
            name='aspirantmaindate',
            options={'ordering': ['order'], 'verbose_name': 'Aspirant Main Date', 'verbose_name_plural': 'Aspirant Main Dates'},
        ),
        migrations.AlterModelOptions(
            name='aspirantprograms',
            options={'ordering': ['order', 'program_name_ru'], 'verbose_name': 'Aspirant Program', 'verbose_name_plural': 'Aspirant Programs'},
        ),
        migrations.AlterModelOptions(
            name='aspirantrequirements',
            options={'ordering': ['order', 'title_ru'], 'verbose_name': 'Aspirant Requirement', 'verbose_name_plural': 'Aspirant Requirements'},
        ),
        migrations.AlterField(
            model_name='aspirantdocuments',
            name='file',
            field=models.FileField(upload_to='aspirant_documents/', verbose_name='File'),
        ),
    ]
