# Generated by Django 5.1.2 on 2025-10-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_alter_aspirantdocuments_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAdmissionSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.TextField(verbose_name='Title (Russian)')),
                ('title_ky', models.TextField(verbose_name='Title (Kyrgyz)')),
                ('title_en', models.TextField(verbose_name='Title (English)')),
                ('description_ru', models.TextField(verbose_name='Description (Russian)')),
                ('description_ky', models.TextField(verbose_name='Description (Kyrgyz)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('deadline_ru', models.TextField(verbose_name='Deadline (Russian)')),
                ('deadline_ky', models.TextField(verbose_name='Deadline (Kyrgyz)')),
                ('deadline_en', models.TextField(verbose_name='Deadline (English)')),
                ('requirement_ru', models.TextField(verbose_name='Requirement (Russian)')),
                ('requirement_ky', models.TextField(verbose_name='Requirement (Kyrgyz)')),
                ('requirement_en', models.TextField(verbose_name='Requirement (English)')),
                ('order', models.PositiveIntegerField(verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Doctor Admission Info',
                'verbose_name_plural': 'Doctor Admission Info',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DoctorPrograms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name_ru', models.CharField(max_length=200, verbose_name='Program Name')),
                ('program_name_ky', models.CharField(max_length=200, verbose_name='Program Name')),
                ('program_name_en', models.CharField(max_length=200, verbose_name='Program Name')),
                ('short_description_ru', models.CharField(max_length=300, verbose_name='Short Description (Russian)')),
                ('short_description_ky', models.CharField(max_length=300, verbose_name='Short   Description (Kyrgyz)')),
                ('short_description_en', models.CharField(max_length=300, verbose_name='Short Description (English)')),
                ('description_ru', models.TextField(verbose_name='Description (Russian)')),
                ('description_ky', models.TextField(verbose_name='Description (Kyrgyz)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('features_ru', models.JSONField(verbose_name='Features (Russian)')),
                ('features_ky', models.JSONField(verbose_name='Features (Kyrgyz)')),
                ('features_en', models.JSONField(verbose_name='Features (English)')),
                ('duration', models.PositiveBigIntegerField(verbose_name='Duration (years)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Doctor Program',
                'verbose_name_plural': 'Doctor Programs',
                'ordering': ['order', 'program_name_ru'],
            },
        ),
        migrations.CreateModel(
            name='DoctorStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleInt', models.CharField(max_length=200, verbose_name='Title (Russian)')),
                ('description_ru', models.TextField(verbose_name='Description (Russian)')),
                ('description_ky', models.TextField(verbose_name='Description (Kyrgyz)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
            ],
            options={
                'verbose_name': 'Doctor Statistics',
                'verbose_name_plural': 'Doctor Statistics',
            },
        ),
    ]
