# Generated by Django 5.1.2 on 2025-10-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_doctoradmissionsteps_doctorprograms_doctorstatistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprograms',
            name='program_name_en',
            field=models.CharField(max_length=200, verbose_name='Program Name(english)'),
        ),
        migrations.AlterField(
            model_name='doctorprograms',
            name='program_name_ky',
            field=models.CharField(max_length=200, verbose_name='Program Name(kyrgyz)'),
        ),
        migrations.AlterField(
            model_name='doctorprograms',
            name='program_name_ru',
            field=models.CharField(max_length=200, verbose_name='Program Name(russian)'),
        ),
    ]
