# Generated by Django 5.1.2 on 2025-10-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0005_alter_doctorprograms_program_name_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeAdmissionRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Title (Russian)')),
                ('title_ky', models.CharField(max_length=200, verbose_name='Title (Kyrgyz)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (English)')),
                ('description_ru', models.TextField(verbose_name='Description (Russian)')),
                ('description_ky', models.TextField(verbose_name='Description (Kyrgyz)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'College Admission Requirement',
                'verbose_name_plural': 'College Admission Requirements',
                'ordering': ['title_ru'],
            },
        ),
        migrations.CreateModel(
            name='CollegeAdmissionSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.TextField(verbose_name='Title (Russian)')),
                ('title_ky', models.TextField(verbose_name='Title (Kyrgyz)')),
                ('title_en', models.TextField(verbose_name='Title (English)')),
                ('description_ru', models.TextField(verbose_name='Description (Russian)')),
                ('description_ky', models.TextField(verbose_name='Description (Kyrgyz)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('duration_ru', models.TextField(verbose_name='Duration (Russian) date and month')),
                ('duration_ky', models.TextField(verbose_name='Duration (Kyrgyz) date and month')),
                ('duration_en', models.TextField(verbose_name='Duration (English) date and month')),
                ('order', models.PositiveIntegerField(verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'College Admission Step',
                'verbose_name_plural': 'College Admission Steps',
            },
        ),
        migrations.CreateModel(
            name='CollegePrograms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name_ru', models.CharField(max_length=200, verbose_name='Program Name(russian)')),
                ('program_name_ky', models.CharField(max_length=200, verbose_name='Program Name(kyrgyz)')),
                ('program_name_en', models.CharField(max_length=200, verbose_name='Program Name(english)')),
                ('short_description_ru', models.CharField(max_length=300, verbose_name='Short Description (Russian)')),
                ('short_description_ky', models.CharField(max_length=300, verbose_name='Short   Description (Kyrgyz)')),
                ('short_description_en', models.CharField(max_length=300, verbose_name='Short Description (English)')),
                ('description_ru', models.TextField(verbose_name='Description (Russian)')),
                ('description_ky', models.TextField(verbose_name='Description (Kyrgyz)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('features_ru', models.JSONField(default=list, verbose_name='Features (Russian)')),
                ('features_ky', models.JSONField(default=list, verbose_name='Features (Kyrgyz)')),
                ('features_en', models.JSONField(default=list, verbose_name='Features (English)')),
                ('duration', models.PositiveBigIntegerField(verbose_name='Duration (years)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Doctor Program',
                'verbose_name_plural': 'Doctor Programs',
                'ordering': ['order', 'program_name_ru'],
            },
        ),
        migrations.CreateModel(
            name='CollegeSoonEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_ru', models.CharField(max_length=200, verbose_name='Event (Russian)')),
                ('event_ky', models.CharField(max_length=200, verbose_name='Event (Kyrgyz)')),
                ('event_en', models.CharField(max_length=200, verbose_name='Event (English)')),
                ('date', models.CharField(max_length=100, verbose_name='Date/Period')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'College Soon Event',
                'verbose_name_plural': 'College Soon Events',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='CollegeStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleInt', models.CharField(max_length=200, verbose_name='Title (Russian)')),
                ('description_ru', models.TextField(verbose_name='Description (Russian)')),
                ('description_ky', models.TextField(verbose_name='Description (Kyrgyz)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
            ],
            options={
                'verbose_name': 'College Statistics',
                'verbose_name_plural': 'College Statistics',
            },
        ),
        migrations.CreateModel(
            name='DoctorSoonEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_ru', models.CharField(max_length=200, verbose_name='Event (Russian)')),
                ('event_ky', models.CharField(max_length=200, verbose_name='Event (Kyrgyz)')),
                ('event_en', models.CharField(max_length=200, verbose_name='Event (English)')),
                ('date', models.CharField(max_length=100, verbose_name='Date/Period')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Doctor Soon Event',
                'verbose_name_plural': 'Doctor Soon Events',
                'ordering': ['date'],
            },
        ),
        migrations.AlterField(
            model_name='doctorprograms',
            name='features_en',
            field=models.JSONField(default=list, verbose_name='Features (English)'),
        ),
        migrations.AlterField(
            model_name='doctorprograms',
            name='features_ky',
            field=models.JSONField(default=list, verbose_name='Features (Kyrgyz)'),
        ),
        migrations.AlterField(
            model_name='doctorprograms',
            name='features_ru',
            field=models.JSONField(default=list, verbose_name='Features (Russian)'),
        ),
    ]
