# Generated by Django 5.1.2 on 2025-10-11 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0006_collegeadmissionrequirements_collegeadmissionsteps_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collegeprograms',
            options={'ordering': ['order', 'program_name_ru'], 'verbose_name': 'College Program', 'verbose_name_plural': 'College Programs'},
        ),
    ]
