# Generated by Django 5.1.2 on 2025-10-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0008_bachelorprogram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bachelorprogram',
            name='Offline',
            field=models.BooleanField(default=False, verbose_name='очное'),
        ),
    ]
