# Generated by Django 5.2.7 on 2025-10-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0010_alter_bachelorprogram_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bachelorprogram",
            name="CareerPerspectives_en",
            field=models.JSONField(
                blank=True,
                default=list,
                max_length=200,
                null=True,
                verbose_name="Перспективы карьеры (английский)",
            ),
        ),
        migrations.AlterField(
            model_name="bachelorprogram",
            name="CareerPerspectives_kg",
            field=models.JSONField(
                blank=True,
                default=list,
                max_length=200,
                null=True,
                verbose_name="Перспективы карьеры (киргизский)",
            ),
        ),
        migrations.AlterField(
            model_name="bachelorprogram",
            name="CareerPerspectives_ru",
            field=models.JSONField(
                blank=True,
                default=list,
                max_length=200,
                null=True,
                verbose_name="Перспективы карьеры (русский)",
            ),
        ),
        migrations.AlterField(
            model_name="bachelorprogram",
            name="mainDiscipline_en",
            field=models.JSONField(
                blank=True,
                default=list,
                max_length=200,
                null=True,
                verbose_name="Основные дисциплины (английский)",
            ),
        ),
        migrations.AlterField(
            model_name="bachelorprogram",
            name="mainDiscipline_kg",
            field=models.JSONField(
                blank=True,
                default=list,
                max_length=200,
                null=True,
                verbose_name="Основные дисциплины (киргизский)",
            ),
        ),
        migrations.AlterField(
            model_name="bachelorprogram",
            name="mainDiscipline_ru",
            field=models.JSONField(
                blank=True,
                default=list,
                max_length=200,
                null=True,
                verbose_name="Основные дисциплины (русский)",
            ),
        ),
    ]
