# Generated by Django 5.2.7 on 2025-10-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0011_alter_bachelorprogram_careerperspectives_en_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bachelorprogram",
            options={
                "verbose_name": "Бакалаврская программа",
                "verbose_name_plural": "Бакалаврские программы",
            },
        ),
        migrations.AlterField(
            model_name="aspirantprograms",
            name="features_en",
            field=models.JSONField(
                verbose_name="Features (English, default=list, null=True, blank=True)"
            ),
        ),
        migrations.AlterField(
            model_name="aspirantprograms",
            name="features_kg",
            field=models.JSONField(
                verbose_name="Features (Kyrgyz, default=list, null=True, blank=True)"
            ),
        ),
        migrations.AlterField(
            model_name="aspirantprograms",
            name="features_ru",
            field=models.JSONField(
                verbose_name="Features (Russian, default=list, null=True, blank=True)"
            ),
        ),
        migrations.AlterField(
            model_name="bachelorprogram",
            name="Offline",
            field=models.BooleanField(default=False, verbose_name="очное"),
        ),
        migrations.AlterField(
            model_name="bachelorprogram",
            name="description_en",
            field=models.TextField(verbose_name="Описание программы (английский)"),
        ),
        migrations.AlterField(
            model_name="bachelorprogram",
            name="description_kg",
            field=models.TextField(verbose_name="Описание программы (киргизский)"),
        ),
        migrations.AlterField(
            model_name="bachelorprogram",
            name="description_ru",
            field=models.TextField(verbose_name="Описание программы (русский)"),
        ),
        migrations.AlterField(
            model_name="bachelorprogram",
            name="duration",
            field=models.PositiveBigIntegerField(
                verbose_name="Продолжительность программы (в годах)"
            ),
        ),
        migrations.AlterField(
            model_name="bachelorprogram",
            name="emoji",
            field=models.CharField(blank=True, max_length=5, verbose_name="эмодзи"),
        ),
        migrations.AlterField(
            model_name="bachelorprogram",
            name="name_en",
            field=models.CharField(
                max_length=200, verbose_name="Название программы (английский)"
            ),
        ),
        migrations.AlterField(
            model_name="bachelorprogram",
            name="name_kg",
            field=models.CharField(
                max_length=200, verbose_name="Название программы (киргизский)"
            ),
        ),
        migrations.AlterField(
            model_name="bachelorprogram",
            name="name_ru",
            field=models.CharField(
                max_length=200, verbose_name="Название программы (русский)"
            ),
        ),
        migrations.AlterField(
            model_name="collegeprograms",
            name="features_en",
            field=models.JSONField(
                default=list,
                verbose_name="Features (English, default=list, null=True, blank=True)",
            ),
        ),
        migrations.AlterField(
            model_name="collegeprograms",
            name="features_kg",
            field=models.JSONField(
                default=list,
                verbose_name="Features (Kyrgyz, default=list, null=True, blank=True)",
            ),
        ),
        migrations.AlterField(
            model_name="collegeprograms",
            name="features_ru",
            field=models.JSONField(
                default=list,
                verbose_name="Features (Russian, default=list, null=True, blank=True)",
            ),
        ),
        migrations.AlterField(
            model_name="doctorprograms",
            name="features_en",
            field=models.JSONField(
                default=list,
                verbose_name="Features (English, default=list, null=True, blank=True)",
            ),
        ),
        migrations.AlterField(
            model_name="doctorprograms",
            name="features_kg",
            field=models.JSONField(
                default=list,
                verbose_name="Features (Kyrgyz, default=list, null=True, blank=True)",
            ),
        ),
        migrations.AlterField(
            model_name="doctorprograms",
            name="features_ru",
            field=models.JSONField(
                default=list,
                verbose_name="Features (Russian, default=list, null=True, blank=True)",
            ),
        ),
        migrations.AlterField(
            model_name="masterprograms",
            name="features_en",
            field=models.JSONField(
                verbose_name="Features (English, default=list, null=True, blank=True)"
            ),
        ),
        migrations.AlterField(
            model_name="masterprograms",
            name="features_kg",
            field=models.JSONField(
                verbose_name="Features (Kyrgyz, default=list, null=True, blank=True)"
            ),
        ),
        migrations.AlterField(
            model_name="masterprograms",
            name="features_ru",
            field=models.JSONField(
                verbose_name="Features (Russian, default=list, null=True, blank=True)"
            ),
        ),
    ]
