# Generated by Django 5.2.7 on 2025-10-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0012_alter_bachelorprogram_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mastermaindate",
            name="date_en",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Date/Period (English)"
            ),
        ),
        migrations.AddField(
            model_name="mastermaindate",
            name="date_kg",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Date/Period (Kyrgyz)"
            ),
        ),
        migrations.AlterField(
            model_name="mastermaindate",
            name="date",
            field=models.CharField(
                max_length=100, verbose_name="Date/Period (Russian)"
            ),
        ),
    ]
