# Generated by Django 5.1.2 on 2025-10-09 05:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership_structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название (RU)')),
                ('title_kg', models.CharField(blank=True, max_length=200, verbose_name='Название (KG)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Название (EN)')),
                ('document_type', models.CharField(choices=[('regulation', 'Положение'), ('order', 'Приказ'), ('instruction', 'Инструкция'), ('charter', 'Устав'), ('plan', 'План'), ('report', 'Отчет'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Тип документа')),
                ('description', models.TextField(blank=True, verbose_name='Описание (RU)')),
                ('description_kg', models.TextField(blank=True, verbose_name='Описание (KG)')),
                ('description_en', models.TextField(blank=True, verbose_name='Описание (EN)')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Файл')),
                ('document_number', models.CharField(blank=True, max_length=100, verbose_name='Номер документа')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='Дата документа')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Размер файла (байт)')),
                ('file_format', models.CharField(blank=True, max_length=10, verbose_name='Формат файла')),
                ('icon', models.CharField(blank=True, default='📄', max_length=50, verbose_name='Иконка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемый')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-document_date', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО (RU)')),
                ('name_kg', models.CharField(blank=True, max_length=200, verbose_name='ФИО (KG)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='ФИО (EN)')),
                ('position', models.CharField(max_length=200, verbose_name='Должность (RU)')),
                ('position_kg', models.CharField(blank=True, max_length=200, verbose_name='Должность (KG)')),
                ('position_en', models.CharField(blank=True, max_length=200, verbose_name='Должность (EN)')),
                ('leadership_type', models.CharField(choices=[('rector', 'Ректор'), ('vice_rector', 'Проректор'), ('director', 'Директор'), ('deputy_director', 'Заместитель директора'), ('department_head', 'Заведующий кафедрой'), ('dean', 'Декан'), ('vice_dean', 'Заместитель декана')], default='department_head', max_length=50, verbose_name='Тип руководства')),
                ('department', models.CharField(blank=True, max_length=200, verbose_name='Подразделение (RU)')),
                ('department_kg', models.CharField(blank=True, max_length=200, verbose_name='Подразделение (KG)')),
                ('department_en', models.CharField(blank=True, max_length=200, verbose_name='Подразделение (EN)')),
                ('bio', models.TextField(blank=True, verbose_name='Биография (RU)')),
                ('bio_kg', models.TextField(blank=True, verbose_name='Биография (KG)')),
                ('bio_en', models.TextField(blank=True, verbose_name='Биография (EN)')),
                ('achievements', models.JSONField(blank=True, default=list, verbose_name='Достижения (RU)')),
                ('achievements_kg', models.JSONField(blank=True, default=list, verbose_name='Достижения (KG)')),
                ('achievements_en', models.JSONField(blank=True, default=list, verbose_name='Достижения (EN)')),
                ('education', models.TextField(blank=True, verbose_name='Образование (RU)')),
                ('education_kg', models.TextField(blank=True, verbose_name='Образование (KG)')),
                ('education_en', models.TextField(blank=True, verbose_name='Образование (EN)')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('image', models.ImageField(blank=True, null=True, upload_to='leadership/', verbose_name='Фото')),
                ('experience_years', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Лет опыта')),
                ('icon', models.CharField(blank=True, default='👤', max_length=50, verbose_name='Иконка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Руководство',
                'verbose_name_plural': 'Руководство',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название (RU)')),
                ('name_kg', models.CharField(blank=True, max_length=200, verbose_name='Название (KG)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Название (EN)')),
                ('structure_type', models.CharField(choices=[('faculty', 'Факультет'), ('department', 'Кафедра'), ('unit', 'Подразделение'), ('service', 'Служба'), ('center', 'Центр')], default='department', max_length=50, verbose_name='Тип структуры')),
                ('description', models.TextField(blank=True, verbose_name='Описание (RU)')),
                ('description_kg', models.TextField(blank=True, verbose_name='Описание (KG)')),
                ('description_en', models.TextField(blank=True, verbose_name='Описание (EN)')),
                ('head', models.CharField(blank=True, max_length=200, verbose_name='Руководитель (RU)')),
                ('head_kg', models.CharField(blank=True, max_length=200, verbose_name='Руководитель (KG)')),
                ('head_en', models.CharField(blank=True, max_length=200, verbose_name='Руководитель (EN)')),
                ('responsibilities', models.JSONField(blank=True, default=list, verbose_name='Обязанности (RU)')),
                ('responsibilities_kg', models.JSONField(blank=True, default=list, verbose_name='Обязанности (KG)')),
                ('responsibilities_en', models.JSONField(blank=True, default=list, verbose_name='Обязанности (EN)')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Расположение (RU)')),
                ('location_kg', models.CharField(blank=True, max_length=200, verbose_name='Расположение (KG)')),
                ('location_en', models.CharField(blank=True, max_length=200, verbose_name='Расположение (EN)')),
                ('staff_count', models.PositiveIntegerField(default=0, verbose_name='Количество сотрудников')),
                ('icon', models.CharField(blank=True, default='🏛️', max_length=50, verbose_name='Иконка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leadership_structure.organizationstructure', verbose_name='Родительская структура')),
            ],
            options={
                'verbose_name': 'Организационная структура',
                'verbose_name_plural': 'Организационная структура',
                'ordering': ['order', 'name'],
            },
        ),
    ]
