# Generated by Django 5.1.2 on 2025-12-19 05:56

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('military_faculty', '0006_management_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutfaculty',
            name='text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutfaculty',
            name='text_kg',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutfaculty',
            name='text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=300, verbose_name='Название (Русский)')),
                ('name_kg', models.CharField(max_length=300, verbose_name='Название (Кыргызча)')),
                ('name_en', models.CharField(max_length=300, verbose_name='Название (English)')),
                ('description_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('description_kg', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tab', models.ForeignKey(limit_choices_to={'key': 'departments'}, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='military_faculty.tabcategory', verbose_name='Таб')),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедры',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Имя (Русский)')),
                ('name_kg', models.CharField(max_length=200, verbose_name='Имя (Кыргызча)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Имя (English)')),
                ('position_ru', models.CharField(max_length=200, verbose_name='Должность (Русский)')),
                ('position_kg', models.CharField(max_length=200, verbose_name='Должность (Кыргызча)')),
                ('position_en', models.CharField(max_length=200, verbose_name='Должность (English)')),
                ('resume', models.FileField(blank=True, null=True, upload_to='pedagogical_faculty/departments/resumes/', verbose_name='Резюме (PDF)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='military_faculty.department', verbose_name='Кафедра')),
            ],
            options={
                'verbose_name': 'Сотрудник кафедры',
                'verbose_name_plural': 'Сотрудники кафедры',
                'ordering': ['department', 'order'],
            },
        ),
    ]
