# Generated by Django 5.1.2 on 2025-10-12 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='about_photos/', verbose_name='Фото для секции о нас')),
                ('description_ru', models.CharField(blank=True, max_length=500, verbose_name='Описание на русском')),
                ('description_en', models.CharField(blank=True, max_length=500, verbose_name='Описание на английском')),
                ('description_ky', models.CharField(blank=True, max_length=500, verbose_name='Описание на кыргызском')),
            ],
            options={
                'verbose_name': 'Фото для секции о нас',
                'verbose_name_plural': 'Фото для секции о нас',
            },
        ),
        migrations.CreateModel(
            name='aboutStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleInt', models.CharField(max_length=200, verbose_name='цифры типа 15+')),
                ('description_ru', models.CharField(max_length=500, verbose_name='Описание на русском')),
                ('description_en', models.CharField(max_length=500, verbose_name='Описание на английском')),
                ('description_ky', models.CharField(max_length=500, verbose_name='Описание на кыргызском')),
                ('emoji', models.CharField(max_length=50, verbose_name='эмодзи')),
            ],
            options={
                'verbose_name': 'Статистика на главной',
                'verbose_name_plural': 'Статистики на главной',
            },
        ),
    ]
