# Generated by Django 5.1.2 on 2025-10-12 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveBigIntegerField(max_length=4, verbose_name='Год')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Заголовок шага истории(русский)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Заголовок шага истории(английский)')),
                ('title_ky', models.CharField(max_length=200, verbose_name='Заголовок шага истории(киргизский)')),
                ('description_ru', models.TextField(verbose_name='Описание на русском')),
                ('description_en', models.TextField(verbose_name='Описание на английском')),
                ('description_ky', models.TextField(verbose_name='Описание на кыргызском')),
                ('buildings', models.PositiveBigIntegerField(verbose_name='количество корпусов')),
                ('students', models.PositiveBigIntegerField(verbose_name='количество студентов')),
                ('programs', models.PositiveBigIntegerField(verbose_name='количество программ')),
                ('achievements_ru', models.JSONField(blank=True, verbose_name='Достижения на русском')),
                ('achievements_en', models.JSONField(blank=True, verbose_name='Достижения на английском')),
                ('achievements_ky', models.JSONField(blank=True, verbose_name='Достижения на кыргызском')),
            ],
            options={
                'verbose_name': 'Шаг истории',
                'verbose_name_plural': 'Шаги истории',
            },
        ),
        migrations.CreateModel(
            name='ImportantDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveBigIntegerField(max_length=4, verbose_name='Год')),
                ('titleInt', models.CharField(max_length=200, verbose_name='Заголовок важной даты типа 15+')),
                ('description_ru', models.TextField(verbose_name='Описание на русском')),
                ('description_en', models.TextField(verbose_name='Описание на английском')),
                ('description_ky', models.TextField(verbose_name='Описание на кыргызском')),
            ],
            options={
                'verbose_name': 'Важная веха',
                'verbose_name_plural': 'Важные вехи',
            },
        ),
    ]
