# Generated by Django 5.1.2 on 2025-10-12 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_historystep_importantdates'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200, verbose_name='категории name(русский)')),
                ('name_en', models.CharField(max_length=200, verbose_name='категории name(английский)')),
                ('name_ky', models.CharField(max_length=200, verbose_name='категории name(киргизский)')),
            ],
            options={
                'verbose_name': 'Категория миссии',
                'verbose_name_plural': 'Категории миссии',
            },
        ),
        migrations.AlterField(
            model_name='historystep',
            name='year',
            field=models.PositiveBigIntegerField(verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='importantdates',
            name='year',
            field=models.PositiveBigIntegerField(verbose_name='Год'),
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Заголовок миссии(русский)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Заголовок миссии(английский)')),
                ('title_ky', models.CharField(max_length=200, verbose_name='Заголовок миссии(киргизский)')),
                ('description_ru', models.TextField(verbose_name='Описание на русском')),
                ('description_en', models.TextField(verbose_name='Описание на английском')),
                ('description_ky', models.TextField(verbose_name='Описание на кыргызском')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='main_page.missioncategory', verbose_name='Категория миссии')),
            ],
            options={
                'verbose_name': 'Миссия',
                'verbose_name_plural': 'Миссии',
            },
        ),
    ]
