# Generated by Django 5.1.2 on 2025-10-12 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_missioncategory_alter_historystep_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccreditationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название (русский)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Название (английский)')),
                ('name_ky', models.CharField(max_length=200, verbose_name='Название (киргизский)')),
            ],
            options={
                'verbose_name': 'Тип аккредитации',
                'verbose_name_plural': 'Типы аккредитации',
            },
        ),
        migrations.CreateModel(
            name='Accreditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_ru', models.CharField(max_length=255)),
                ('organization_en', models.CharField(max_length=255)),
                ('organization_ky', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='accreditation_logos/')),
                ('validity_ru', models.CharField(max_length=255)),
                ('validity_en', models.CharField(max_length=255)),
                ('validity_ky', models.CharField(max_length=255)),
                ('description_ru', models.TextField()),
                ('description_en', models.TextField()),
                ('description_ky', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='accreditation_photos/')),
                ('certificate_number', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accreditation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accreditations', to='main_page.accreditationtype')),
            ],
        ),
    ]
