# Generated by Django 5.1.2 on 2025-10-12 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_accreditationtype_accreditation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accreditation',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Аккредитация', 'verbose_name_plural': 'Аккредитации'},
        ),
    ]
