# Generated by Django 5.2.5 on 2025-10-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_alter_accreditation_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyAchievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveBigIntegerField(verbose_name='год ')),
                ('title_ru', models.CharField(max_length=500, verbose_name='заголовок на русском')),
                ('title_en', models.CharField(max_length=500, verbose_name='заголовок на английском')),
                ('title_ky', models.CharField(max_length=500, verbose_name='заголовок на киргизском')),
                ('description_ru', models.TextField(verbose_name='описание на русском')),
                ('description_en', models.TextField(verbose_name='описание на английском')),
                ('description_ky', models.TextField(verbose_name='описание на киргизском')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
            },
        ),
        migrations.CreateModel(
            name='AcademyStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleInt', models.CharField(max_length=100, verbose_name='заголовок-цифры типа 15+')),
                ('title_ru', models.CharField(max_length=250, verbose_name='заголовок на русском')),
                ('title_en', models.CharField(max_length=250, verbose_name='заголовок на английском')),
                ('title_ky', models.CharField(max_length=250, verbose_name='заголовок на киргизском')),
                ('description_ru', models.TextField(verbose_name='описание на русском')),
                ('description_en', models.TextField(verbose_name='описание на английском')),
                ('description_ky', models.TextField(verbose_name='описание на киргизском')),
            ],
            options={
                'verbose_name': 'Статистика академии',
                'verbose_name_plural': 'Статистики академии',
            },
        ),
    ]
