# Generated by Django 5.2.5 on 2025-10-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_academyachievements_academystatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='academystatistics',
            name='emoji',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='эмодзи'),
        ),
    ]
