# Generated by Django 5.2.5 on 2025-10-12 11:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_academystatistics_emoji'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyInfrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=5, verbose_name='эмодзи')),
                ('titleInt', models.CharField(max_length=20, verbose_name='заголовок-цифра типа 1000+')),
                ('description_ru', models.CharField(max_length=250, verbose_name='описание на русском')),
                ('description_en', models.CharField(max_length=250, verbose_name='описание на английском')),
                ('description_ky', models.CharField(max_length=250, verbose_name='описание на киргизском')),
            ],
        ),
        migrations.AlterField(
            model_name='academystatistics',
            name='emoji',
            field=models.CharField(default=django.utils.timezone.now, max_length=5, verbose_name='эмодзи'),
            preserve_default=False,
        ),
    ]
