# Generated by Django 5.1.2 on 2025-10-13 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_academyinfrastructure_alter_academystatistics_emoji'),
    ]

    operations = [
        migrations.CreateModel(
            name='BachelorProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название программы (русский)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Название программы (английский)')),
                ('name_ky', models.CharField(max_length=200, verbose_name='Название программы (киргизский)')),
                ('description_ru', models.TextField(verbose_name='Описание программы (русский)')),
                ('description_en', models.TextField(verbose_name='Описание программы (английский)')),
                ('description_ky', models.TextField(verbose_name='Описание программы (киргизский)')),
                ('duration', models.PositiveBigIntegerField(verbose_name='Продолжительность программы (в годах)')),
                ('Offline', models.BooleanField(default=False, verbose_name='очное или нет')),
                ('emoji', models.CharField(blank=True, max_length=5, verbose_name='эмодзи')),
                ('mainDiscipline_ru', models.JSONField(max_length=200, verbose_name='Основные дисциплины (русский)')),
                ('mainDiscipline_en', models.JSONField(max_length=200, verbose_name='Основные дисциплины (английский)')),
                ('mainDiscipline_ky', models.JSONField(max_length=200, verbose_name='Основные дисциплины (киргизский)')),
                ('CareerPerspectives_ru', models.JSONField(max_length=200, verbose_name='Перспективы карьеры (русский)')),
                ('CareerPerspectives_en', models.JSONField(max_length=200, verbose_name='Перспективы карьеры (английский)')),
                ('CareerPerspectives_ky', models.JSONField(max_length=200, verbose_name='Перспективы карьеры (киргизский)')),
            ],
            options={
                'verbose_name': 'Бакалаврская программа',
                'verbose_name_plural': 'Бакалаврские программы',
            },
        ),
        migrations.AlterModelOptions(
            name='academyinfrastructure',
            options={'verbose_name': 'Инфраструктура', 'verbose_name_plural': 'Инфраструктуры'},
        ),
    ]
