# Generated by Django 5.1.2 on 2025-10-13 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0009_bachelorprogram_alter_academyinfrastructure_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BachelorProgram',
        ),
    ]
