# Generated by Django 5.2.7 on 2025-10-23 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0010_delete_bachelorprogram"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aboutphotos",
            old_name="description_ky",
            new_name="description_kg",
        ),
        migrations.RenameField(
            model_name="aboutstatistics",
            old_name="description_ky",
            new_name="description_kg",
        ),
        migrations.RenameField(
            model_name="academyachievements",
            old_name="description_ky",
            new_name="description_kg",
        ),
        migrations.RenameField(
            model_name="academyachievements",
            old_name="title_ky",
            new_name="title_kg",
        ),
        migrations.RenameField(
            model_name="academystatistics",
            old_name="description_ky",
            new_name="description_kg",
        ),
        migrations.RenameField(
            model_name="academystatistics",
            old_name="title_ky",
            new_name="title_kg",
        ),
        migrations.RenameField(
            model_name="accreditation",
            old_name="description_ky",
            new_name="description_kg",
        ),
        migrations.RenameField(
            model_name="accreditation",
            old_name="organization_ky",
            new_name="organization_kg",
        ),
        migrations.RenameField(
            model_name="accreditation",
            old_name="validity_ky",
            new_name="validity_kg",
        ),
        migrations.RenameField(
            model_name="accreditationtype",
            old_name="name_ky",
            new_name="name_kg",
        ),
        migrations.RenameField(
            model_name="historystep",
            old_name="achievements_ky",
            new_name="achievements_kg",
        ),
        migrations.RenameField(
            model_name="historystep",
            old_name="description_ky",
            new_name="description_kg",
        ),
        migrations.RenameField(
            model_name="historystep",
            old_name="title_ky",
            new_name="title_kg",
        ),
        migrations.RenameField(
            model_name="importantdates",
            old_name="description_ky",
            new_name="description_kg",
        ),
        migrations.RenameField(
            model_name="mission",
            old_name="description_ky",
            new_name="description_kg",
        ),
        migrations.RenameField(
            model_name="mission",
            old_name="title_ky",
            new_name="title_kg",
        ),
        migrations.RenameField(
            model_name="missioncategory",
            old_name="name_ky",
            new_name="name_kg",
        ),
    ]
