# Generated by Django 5.1.2 on 2025-10-23 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/', verbose_name='Изображение')),
                ('category', models.CharField(choices=[('conference', 'Конференция'), ('seminar', 'Семинар'), ('workshop', 'Мастер-класс'), ('lecture', 'Лекция'), ('exhibition', 'Выставка'), ('competition', 'Соревнование'), ('festival', 'Фестиваль'), ('sports', 'Спортивное мероприятие'), ('cultural', 'Культурное мероприятие'), ('educational', 'Образовательное мероприятие')], max_length=20, verbose_name='Категория')),
                ('department', models.CharField(choices=[('science', 'Научный отдел'), ('education', 'Учебный отдел'), ('culture', 'Культурный центр'), ('sports', 'Спортивный клуб'), ('students', 'Студенческий совет'), ('international', 'Международный отдел'), ('administration', 'Администрация')], max_length=20, verbose_name='Отдел')),
                ('format', models.CharField(choices=[('offline', 'Оффлайн'), ('online', 'Онлайн'), ('hybrid', 'Гибридный')], default='offline', max_length=10, verbose_name='Формат')),
                ('start_date', models.DateTimeField(verbose_name='Дата и время начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата и время окончания')),
                ('organizer_name', models.CharField(blank=True, max_length=200, verbose_name='Имя организатора')),
                ('organizer_contact', models.CharField(blank=True, max_length=200, verbose_name='Контакт организатора')),
                ('audience', models.CharField(blank=True, max_length=200, verbose_name='Целевая аудитория')),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимум участников')),
                ('registration_required', models.BooleanField(default=False, verbose_name='Требуется регистрация')),
                ('registration_link', models.URLField(blank=True, verbose_name='Ссылка на регистрацию')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемое')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EventTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('ky', 'Кыргызча')], max_length=2, verbose_name='Язык')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('full_description', models.TextField(blank=True, verbose_name='Полное описание')),
                ('location', models.CharField(max_length=200, verbose_name='Местоположение')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='events.event')),
            ],
            options={
                'verbose_name': 'Перевод мероприятия',
                'verbose_name_plural': 'Переводы мероприятий',
                'unique_together': {('event', 'language')},
            },
        ),
    ]
