# Generated by Django 5.1.2 on 2025-10-23 13:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='audience',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='format',
        ),
        migrations.RemoveField(
            model_name='event',
            name='max_participants',
        ),
        migrations.RemoveField(
            model_name='event',
            name='organizer_contact',
        ),
        migrations.RemoveField(
            model_name='event',
            name='organizer_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='registration_link',
        ),
        migrations.RemoveField(
            model_name='event',
            name='registration_required',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_date',
        ),
        migrations.AddField(
            model_name='event',
            name='audience_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Аудитория (английский)'),
        ),
        migrations.AddField(
            model_name='event',
            name='audience_ky',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Аудитория (кыргызский)'),
        ),
        migrations.AddField(
            model_name='event',
            name='audience_ru',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Аудитория (русский)'),
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата мероприятия'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_en',
            field=models.TextField(default='', verbose_name='Описание (английский)'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_ky',
            field=models.TextField(default='', verbose_name='Описание (кыргызский)'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_ru',
            field=models.TextField(default='', verbose_name='Описание (русский)'),
        ),
        migrations.AddField(
            model_name='event',
            name='duration_en',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Продолжительность (английский)'),
        ),
        migrations.AddField(
            model_name='event',
            name='duration_ky',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Продолжительность (кыргызский)'),
        ),
        migrations.AddField(
            model_name='event',
            name='duration_ru',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Продолжительность (русский)'),
        ),
        migrations.AddField(
            model_name='event',
            name='format_en',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Формат (английский)'),
        ),
        migrations.AddField(
            model_name='event',
            name='format_ky',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Формат (кыргызский)'),
        ),
        migrations.AddField(
            model_name='event',
            name='format_ru',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Формат (русский)'),
        ),
        migrations.AddField(
            model_name='event',
            name='full_description_en',
            field=models.TextField(blank=True, default='', verbose_name='Полное описание (английский)'),
        ),
        migrations.AddField(
            model_name='event',
            name='full_description_ky',
            field=models.TextField(blank=True, default='', verbose_name='Полное описание (кыргызский)'),
        ),
        migrations.AddField(
            model_name='event',
            name='full_description_ru',
            field=models.TextField(blank=True, default='', verbose_name='Полное описание (русский)'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_en',
            field=models.CharField(default='', max_length=300, verbose_name='Место проведения (английский)'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_ky',
            field=models.CharField(default='', max_length=300, verbose_name='Место проведения (кыргызский)'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_ru',
            field=models.CharField(default='', max_length=300, verbose_name='Место проведения (русский)'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer_contact_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Контакты организатора (английский)'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer_contact_ky',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Контакты организатора (кыргызский)'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer_contact_ru',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Контакты организатора (русский)'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer_name_en',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Имя организатора (английский)'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer_name_ky',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Имя организатора (кыргызский)'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer_name_ru',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Имя организатора (русский)'),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Время мероприятия'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_en',
            field=models.CharField(default='', max_length=200, verbose_name='Заголовок (английский)'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_ky',
            field=models.CharField(default='', max_length=200, verbose_name='Заголовок (кыргызский)'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_ru',
            field=models.CharField(default='', max_length=200, verbose_name='Заголовок (русский)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('conference', 'Конференция'), ('seminar', 'Семинар'), ('workshop', 'Воркшоп'), ('lecture', 'Лекция'), ('exhibition', 'Выставка'), ('competition', 'Соревнование'), ('festival', 'Фестиваль'), ('sports', 'Спорт'), ('cultural', 'Культурное мероприятие'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='event',
            name='department',
            field=models.CharField(choices=[('computer_science', 'Факультет компьютерных наук'), ('engineering', 'Инженерный факультет'), ('business', 'Бизнес факультет'), ('medicine', 'Медицинский факультет'), ('arts', 'Факультет искусств'), ('science', 'Естественнонаучный факультет'), ('law', 'Юридический факультет'), ('international', 'Международный отдел'), ('student_union', 'Студенческий союз')], default='computer_science', max_length=20, verbose_name='Факультет/Отдел'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='event',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок отображения'),
        ),
        migrations.DeleteModel(
            name='EventTranslation',
        ),
    ]
