# Generated by Django 5.1.2 on 2025-10-27 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options_remove_event_audience_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='audience_ky',
            new_name='audience_kg',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='description_ky',
            new_name='description_kg',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='duration_ky',
            new_name='duration_kg',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='format_ky',
            new_name='format_kg',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='full_description_ky',
            new_name='full_description_kg',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='location_ky',
            new_name='location_kg',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='organizer_contact_ky',
            new_name='organizer_contact_kg',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='organizer_name_ky',
            new_name='organizer_name_kg',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='title_ky',
            new_name='title_kg',
        ),
    ]
