# Generated by Django 5.1.2 on 2025-12-03 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DepartmentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Ключ категории"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=200, verbose_name="Название (Русский)"),
                ),
                (
                    "name_kg",
                    models.CharField(
                        max_length=200, verbose_name="Название (Кыргызча)"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(max_length=200, verbose_name="Название (English)"),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Например: blue-500, green-600",
                        max_length=50,
                        verbose_name="Цвет",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Категория кафедры",
                "verbose_name_plural": "Категории кафедр",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="DepartmentFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature_ru", models.TextField(verbose_name="Особенность (Русский)")),
                ("feature_kg", models.TextField(verbose_name="Особенность (Кыргызча)")),
                ("feature_en", models.TextField(verbose_name="Особенность (English)")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="general_departments.departmentcategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Особенность кафедры",
                "verbose_name_plural": "Особенности кафедр",
                "ordering": ["category", "order"],
            },
        ),
        migrations.CreateModel(
            name="DepartmentInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description_ru", models.TextField(verbose_name="Описание (Русский)")),
                (
                    "description_kg",
                    models.TextField(verbose_name="Описание (Кыргызча)"),
                ),
                ("description_en", models.TextField(verbose_name="Описание (English)")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="info",
                        to="general_departments.departmentcategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Описание кафедры",
                "verbose_name_plural": "Описания кафедр",
            },
        ),
    ]
