# Generated by Django 5.1.2 on 2025-12-21 07:54

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TabCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='Ключ')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Заголовок (Русский)')),
                ('name_kg', models.CharField(max_length=200, verbose_name='Заголовок (Кыргызча)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Заголовок (English)')),
                ('color', models.CharField(blank=True, help_text='Например: blue-500, green-600', max_length=50, verbose_name='Цвет')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Категория кафедры',
                'verbose_name_plural': 'Категории кафедр',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Фото')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Имя (Русский)')),
                ('name_kg', models.CharField(max_length=200, verbose_name='Имя (Кыргызча)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Имя (English)')),
                ('role_ru', models.CharField(max_length=200, verbose_name='Роль (Русский)')),
                ('role_kg', models.CharField(max_length=200, verbose_name='Роль (Кыргызча)')),
                ('role_en', models.CharField(max_length=200, verbose_name='Роль (English)')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tab', models.ForeignKey(limit_choices_to={'key': 'management'}, on_delete=django.db.models.deletion.CASCADE, related_name='management', to='general_departments.tabcategory', verbose_name='Таб')),
            ],
            options={
                'verbose_name': 'Руководство',
                'verbose_name_plural': 'Руководство',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_ru', models.TextField(verbose_name='Описание(Русский)')),
                ('description_kg', models.TextField(verbose_name='Описание(Кыргызча)')),
                ('description_en', models.TextField(verbose_name='Описание(English)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='general_departments.tabcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Описание кафедры',
                'verbose_name_plural': 'Описания кафедр',
            },
        ),
    ]
