# Generated by Django 5.1.2 on 2025-12-21 11:14

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_departments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='management',
            name='tab',
        ),
        migrations.RemoveField(
            model_name='tabcategory',
            name='key',
        ),
        migrations.AddField(
            model_name='management',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='management', to='general_departments.tabcategory', verbose_name='Кафедра'),
        ),
        migrations.AlterField(
            model_name='departmentinfo',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание(English)'),
        ),
        migrations.AlterField(
            model_name='departmentinfo',
            name='description_kg',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание(Кыргызча)'),
        ),
        migrations.AlterField(
            model_name='departmentinfo',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание(Русский)'),
        ),
    ]
