# Generated by Django 5.1.2 on 2025-10-28 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Infrastructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "badge",
                    models.CharField(
                        default="Спортивная инфраструктура",
                        max_length=100,
                        verbose_name="Бейдж",
                    ),
                ),
                (
                    "stat_1_value",
                    models.CharField(
                        default="25+",
                        max_length=50,
                        verbose_name="Статистика 1 - Значение",
                    ),
                ),
                (
                    "stat_1_icon",
                    models.CharField(
                        default="🏟️", max_length=10, verbose_name="Статистика 1 - Иконка"
                    ),
                ),
                (
                    "stat_2_value",
                    models.CharField(
                        default="5000+",
                        max_length=50,
                        verbose_name="Статистика 2 - Значение",
                    ),
                ),
                (
                    "stat_2_icon",
                    models.CharField(
                        default="👥",
                        max_length=10,
                        verbose_name="Статистика 2 - Иконка",
                    ),
                ),
                (
                    "stat_3_value",
                    models.CharField(
                        default="100%",
                        max_length=50,
                        verbose_name="Статистика 3 - Значение",
                    ),
                ),
                (
                    "stat_3_icon",
                    models.CharField(
                        default="⚡",
                        max_length=10,
                        verbose_name="Статистика 3 - Иконка",
                    ),
                ),
                (
                    "stat_4_value",
                    models.CharField(
                        default="15+",
                        max_length=50,
                        verbose_name="Статистика 4 - Значение",
                    ),
                ),
                (
                    "stat_4_icon",
                    models.CharField(
                        default="🎯",
                        max_length=10,
                        verbose_name="Статистика 4 - Иконка",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Спортивная инфраструктура",
                "verbose_name_plural": "Спортивная инфраструктура",
            },
        ),
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "athlete_name",
                    models.CharField(
                        max_length=200, verbose_name="Имя спортсмена/команды"
                    ),
                ),
                ("sport", models.CharField(max_length=100, verbose_name="Вид спорта")),
                (
                    "competition",
                    models.CharField(max_length=200, verbose_name="Соревнование"),
                ),
                (
                    "result",
                    models.CharField(
                        help_text="Например: 1 место, Золото, Участник",
                        max_length=100,
                        verbose_name="Результат",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата достижения")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="sports/achievements/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("individual", "Индивидуальные"),
                            ("team", "Командные"),
                            ("international", "Международные"),
                            ("olympic", "Олимпийские"),
                            ("coaching", "Тренерские"),
                        ],
                        db_index=True,
                        default="individual",
                        max_length=20,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='JSON объект с дополнительной информацией: {"distance": "200м", "time": "1:54.32"}',
                        verbose_name="Дополнительные детали",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Активно"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Спортивное достижение",
                "verbose_name_plural": "Спортивные достижения",
                "ordering": ["-date", "order"],
                "indexes": [
                    models.Index(
                        fields=["-date", "is_active"],
                        name="sports_achi_date_5b2a26_idx",
                    ),
                    models.Index(
                        fields=["category", "is_active"],
                        name="sports_achi_categor_285991_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InfrastructureCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Уникальный идентификатор категории: stadiums, pools, gyms",
                        verbose_name="Идентификатор",
                    ),
                ),
                (
                    "icon",
                    models.CharField(default="🏟️", max_length=10, verbose_name="Иконка"),
                ),
                (
                    "color",
                    models.CharField(
                        default="from-blue-500 to-cyan-500",
                        help_text="Tailwind классы градиента",
                        max_length=50,
                        verbose_name="Цвет градиента",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Порядок"
                    ),
                ),
                (
                    "infrastructure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="sports.infrastructure",
                        verbose_name="Инфраструктура",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория инфраструктуры",
                "verbose_name_plural": "Категории инфраструктуры",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="InfrastructureCategoryTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("ru", "Русский"),
                            ("en", "English"),
                            ("kg", "Кыргызча"),
                        ],
                        max_length=2,
                        verbose_name="Язык",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название категории"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="sports.infrastructurecategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Перевод категории",
                "verbose_name_plural": "Переводы категорий",
            },
        ),
        migrations.CreateModel(
            name="InfrastructureObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="sports/infrastructure/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Список характеристик: ["Вместимость: 1500", "Синтетическое покрытие"]',
                        verbose_name="Характеристики",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Порядок"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Активно"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objects",
                        to="sports.infrastructurecategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Объект инфраструктуры",
                "verbose_name_plural": "Объекты инфраструктуры",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="InfrastructureObjectTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("ru", "Русский"),
                            ("en", "English"),
                            ("kg", "Кыргызча"),
                        ],
                        max_length=2,
                        verbose_name="Язык",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "infrastructure_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="sports.infrastructureobject",
                        verbose_name="Объект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Перевод объекта",
                "verbose_name_plural": "Переводы объектов",
            },
        ),
        migrations.CreateModel(
            name="InfrastructureTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("ru", "Русский"),
                            ("en", "English"),
                            ("kg", "Кыргызча"),
                        ],
                        max_length=2,
                        verbose_name="Язык",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "stat_1_label",
                    models.CharField(
                        max_length=100, verbose_name="Статистика 1 - Подпись"
                    ),
                ),
                (
                    "stat_2_label",
                    models.CharField(
                        max_length=100, verbose_name="Статистика 2 - Подпись"
                    ),
                ),
                (
                    "stat_3_label",
                    models.CharField(
                        max_length=100, verbose_name="Статистика 3 - Подпись"
                    ),
                ),
                (
                    "stat_4_label",
                    models.CharField(
                        max_length=100, verbose_name="Статистика 4 - Подпись"
                    ),
                ),
                (
                    "infrastructure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="sports.infrastructure",
                        verbose_name="Инфраструктура",
                    ),
                ),
            ],
            options={
                "verbose_name": "Перевод инфраструктуры",
                "verbose_name_plural": "Переводы инфраструктуры",
            },
        ),
        migrations.CreateModel(
            name="SportSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sport_type",
                    models.CharField(
                        choices=[
                            ("game", "Игровые виды спорта"),
                            ("combat", "Единоборства"),
                            ("winter", "Зимние виды спорта"),
                            ("water", "Водные виды спорта"),
                            ("athletics", "Легкая атлетика"),
                            ("gymnastics", "Гимнастика"),
                            ("team", "Командные виды"),
                            ("individual", "Индивидуальные виды"),
                        ],
                        db_index=True,
                        default="individual",
                        max_length=20,
                        verbose_name="Тип спорта",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="sports/sections/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "coach_name",
                    models.CharField(max_length=200, verbose_name="ФИО тренера"),
                ),
                (
                    "coach_rank",
                    models.CharField(
                        blank=True,
                        help_text="Например: Мастер спорта, Заслуженный тренер",
                        max_length=200,
                        verbose_name="Звание тренера",
                    ),
                ),
                (
                    "coach_contacts",
                    models.CharField(
                        blank=True,
                        help_text="Телефон, email",
                        max_length=200,
                        verbose_name="Контакты тренера",
                    ),
                ),
                (
                    "schedule",
                    models.CharField(
                        help_text="Краткое расписание, например: Пн, Ср, Пт 18:00-20:00",
                        max_length=200,
                        verbose_name="Расписание",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Активна"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Спортивная секция",
                "verbose_name_plural": "Спортивные секции",
                "ordering": ["order", "coach_name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "order"],
                        name="sports_spor_is_acti_7e9f11_idx",
                    ),
                    models.Index(
                        fields=["sport_type", "is_active"],
                        name="sports_spor_sport_t_fc8cd1_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SportSectionTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("ru", "Русский"),
                            ("en", "English"),
                            ("kg", "Кыргызча"),
                        ],
                        max_length=2,
                        verbose_name="Язык",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название секции"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "contact_info",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Контактная информация"
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="sports.sportsection",
                        verbose_name="Секция",
                    ),
                ),
            ],
            options={
                "verbose_name": "Перевод секции",
                "verbose_name_plural": "Переводы секций",
            },
        ),
        migrations.CreateModel(
            name="TrainingSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("monday", "Понедельник"),
                            ("tuesday", "Вторник"),
                            ("wednesday", "Среда"),
                            ("thursday", "Четверг"),
                            ("friday", "Пятница"),
                            ("saturday", "Суббота"),
                            ("sunday", "Воскресенье"),
                        ],
                        max_length=10,
                        verbose_name="День недели",
                    ),
                ),
                ("time_start", models.TimeField(verbose_name="Время начала")),
                ("time_end", models.TimeField(verbose_name="Время окончания")),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Место проведения"
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_schedules",
                        to="sports.sportsection",
                        verbose_name="Секция",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расписание тренировки",
                "verbose_name_plural": "Расписание тренировок",
                "ordering": ["section", "day_of_week", "time_start"],
            },
        ),
        migrations.CreateModel(
            name="AchievementTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("ru", "Русский"),
                            ("en", "English"),
                            ("kg", "Кыргызча"),
                        ],
                        max_length=2,
                        verbose_name="Язык",
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание достижения")),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="sports.achievement",
                        verbose_name="Достижение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Перевод достижения",
                "verbose_name_plural": "Переводы достижений",
                "unique_together": {("achievement", "language")},
            },
        ),
        migrations.AddIndex(
            model_name="infrastructurecategory",
            index=models.Index(
                fields=["infrastructure", "order"],
                name="sports_infr_infrast_8c12cd_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="infrastructurecategory",
            unique_together={("infrastructure", "slug")},
        ),
        migrations.AlterUniqueTogether(
            name="infrastructurecategorytranslation",
            unique_together={("category", "language")},
        ),
        migrations.AddIndex(
            model_name="infrastructureobject",
            index=models.Index(
                fields=["category", "is_active", "order"],
                name="sports_infr_categor_9fca9b_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="infrastructureobjecttranslation",
            unique_together={("infrastructure_object", "language")},
        ),
        migrations.AlterUniqueTogether(
            name="infrastructuretranslation",
            unique_together={("infrastructure", "language")},
        ),
        migrations.AlterUniqueTogether(
            name="sportsectiontranslation",
            unique_together={("section", "language")},
        ),
    ]
