# Generated by Django 5.1.2 on 2025-10-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sports", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="infrastructurecategorytranslation",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="infrastructurecategorytranslation",
            name="category",
        ),
        migrations.AlterUniqueTogether(
            name="infrastructureobjecttranslation",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="infrastructureobjecttranslation",
            name="infrastructure_object",
        ),
        migrations.AlterUniqueTogether(
            name="infrastructuretranslation",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="infrastructuretranslation",
            name="infrastructure",
        ),
        migrations.AlterUniqueTogether(
            name="sportsectiontranslation",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="sportsectiontranslation",
            name="section",
        ),
        migrations.AddField(
            model_name="achievement",
            name="description_en",
            field=models.TextField(default="", verbose_name="Описание достижения (EN)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="achievement",
            name="description_kg",
            field=models.TextField(default="", verbose_name="Описание достижения (KG)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="achievement",
            name="description_ru",
            field=models.TextField(default="", verbose_name="Описание достижения (RU)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="infrastructure",
            name="description_en",
            field=models.TextField(default="", verbose_name="Описание (EN)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="infrastructure",
            name="description_kg",
            field=models.TextField(default="", verbose_name="Описание (KG)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="infrastructure",
            name="description_ru",
            field=models.TextField(default="", verbose_name="Описание (RU)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="infrastructure",
            name="name_en",
            field=models.CharField(
                default="", max_length=200, verbose_name="Название (EN)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="infrastructure",
            name="name_kg",
            field=models.CharField(
                default="", max_length=200, verbose_name="Название (KG)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="infrastructure",
            name="name_ru",
            field=models.CharField(
                default="", max_length=200, verbose_name="Название (RU)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="infrastructure",
            name="stat_1_label_en",
            field=models.CharField(
                default="", max_length=100, verbose_name="Статистика 1 - Подпись (EN)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="infrastructure",
            name="stat_1_label_kg",
            field=models.CharField(
                default="", max_length=100, verbose_name="Статистика 1 - Подпись (KG)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="infrastructure",
            name="stat_1_label_ru",
            field=models.CharField(
                default="", max_length=100, verbose_name="Статистика 1 - Подпись (RU)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="infrastructure",
            name="stat_2_label_en",
            field=models.CharField(
                default="", max_length=100, verbose_name="Статистика 2 - Подпись (EN)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="infrastructure",
            name="stat_2_label_kg",
            field=models.CharField(
                default="", max_length=100, verbose_name="Статистика 2 - Подпись (KG)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="infrastructure",
            name="stat_2_label_ru",
            field=models.CharField(
                default="", max_length=100, verbose_name="Статистика 2 - Подпись (RU)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="infrastructure",
            name="stat_3_label_en",
            field=models.CharField(
                default="", max_length=100, verbose_name="Статистика 3 - Подпись (EN)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="infrastructure",
            name="stat_3_label_kg",
            field=models.CharField(
                default="", max_length=100, verbose_name="Статистика 3 - Подпись (KG)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="infrastructure",
            name="stat_3_label_ru",
            field=models.CharField(
                default="", max_length=100, verbose_name="Статистика 3 - Подпись (RU)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="infrastructure",
            name="stat_4_label_en",
            field=models.CharField(
                default="", max_length=100, verbose_name="Статистика 4 - Подпись (EN)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="infrastructure",
            name="stat_4_label_kg",
            field=models.CharField(
                default="", max_length=100, verbose_name="Статистика 4 - Подпись (KG)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="infrastructure",
            name="stat_4_label_ru",
            field=models.CharField(
                default="", max_length=100, verbose_name="Статистика 4 - Подпись (RU)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="infrastructurecategory",
            name="name_en",
            field=models.CharField(
                default="", max_length=100, verbose_name="Название категории (EN)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="infrastructurecategory",
            name="name_kg",
            field=models.CharField(
                default="", max_length=100, verbose_name="Название категории (KG)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="infrastructurecategory",
            name="name_ru",
            field=models.CharField(
                default="", max_length=100, verbose_name="Название категории (RU)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="infrastructureobject",
            name="description_en",
            field=models.TextField(default="", verbose_name="Описание (EN)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="infrastructureobject",
            name="description_kg",
            field=models.TextField(default="", verbose_name="Описание (KG)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="infrastructureobject",
            name="description_ru",
            field=models.TextField(default="", verbose_name="Описание (RU)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="infrastructureobject",
            name="name_en",
            field=models.CharField(
                default="", max_length=200, verbose_name="Название (EN)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="infrastructureobject",
            name="name_kg",
            field=models.CharField(
                default="", max_length=200, verbose_name="Название (KG)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="infrastructureobject",
            name="name_ru",
            field=models.CharField(
                default="", max_length=200, verbose_name="Название (RU)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sportsection",
            name="contact_info_en",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Контактная информация (EN)"
            ),
        ),
        migrations.AddField(
            model_name="sportsection",
            name="contact_info_kg",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Контактная информация (KG)"
            ),
        ),
        migrations.AddField(
            model_name="sportsection",
            name="contact_info_ru",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Контактная информация (RU)"
            ),
        ),
        migrations.AddField(
            model_name="sportsection",
            name="description_en",
            field=models.TextField(default="", verbose_name="Описание (EN)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sportsection",
            name="description_kg",
            field=models.TextField(default="", verbose_name="Описание (KG)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sportsection",
            name="description_ru",
            field=models.TextField(default="", verbose_name="Описание (RU)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sportsection",
            name="name_en",
            field=models.CharField(
                default="", max_length=200, verbose_name="Название секции (EN)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sportsection",
            name="name_kg",
            field=models.CharField(
                default="", max_length=200, verbose_name="Название секции (KG)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sportsection",
            name="name_ru",
            field=models.CharField(
                default="", max_length=200, verbose_name="Название секции (RU)"
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="AchievementTranslation",
        ),
        migrations.DeleteModel(
            name="InfrastructureCategoryTranslation",
        ),
        migrations.DeleteModel(
            name="InfrastructureObjectTranslation",
        ),
        migrations.DeleteModel(
            name="InfrastructureTranslation",
        ),
        migrations.DeleteModel(
            name="SportSectionTranslation",
        ),
    ]
