# Generated by Django 5.1.2 on 2025-10-28 19:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sports", "0004_copy_existing_data_to_ru"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="infrastructure",
            name="stat_1_icon",
        ),
        migrations.RemoveField(
            model_name="infrastructure",
            name="stat_1_label_en",
        ),
        migrations.RemoveField(
            model_name="infrastructure",
            name="stat_1_label_kg",
        ),
        migrations.RemoveField(
            model_name="infrastructure",
            name="stat_1_label_ru",
        ),
        migrations.RemoveField(
            model_name="infrastructure",
            name="stat_1_value",
        ),
        migrations.RemoveField(
            model_name="infrastructure",
            name="stat_2_icon",
        ),
        migrations.RemoveField(
            model_name="infrastructure",
            name="stat_2_label_en",
        ),
        migrations.RemoveField(
            model_name="infrastructure",
            name="stat_2_label_kg",
        ),
        migrations.RemoveField(
            model_name="infrastructure",
            name="stat_2_label_ru",
        ),
        migrations.RemoveField(
            model_name="infrastructure",
            name="stat_2_value",
        ),
        migrations.RemoveField(
            model_name="infrastructure",
            name="stat_3_icon",
        ),
        migrations.RemoveField(
            model_name="infrastructure",
            name="stat_3_label_en",
        ),
        migrations.RemoveField(
            model_name="infrastructure",
            name="stat_3_label_kg",
        ),
        migrations.RemoveField(
            model_name="infrastructure",
            name="stat_3_label_ru",
        ),
        migrations.RemoveField(
            model_name="infrastructure",
            name="stat_3_value",
        ),
        migrations.RemoveField(
            model_name="infrastructure",
            name="stat_4_icon",
        ),
        migrations.RemoveField(
            model_name="infrastructure",
            name="stat_4_label_en",
        ),
        migrations.RemoveField(
            model_name="infrastructure",
            name="stat_4_label_kg",
        ),
        migrations.RemoveField(
            model_name="infrastructure",
            name="stat_4_label_ru",
        ),
        migrations.RemoveField(
            model_name="infrastructure",
            name="stat_4_value",
        ),
        migrations.AddField(
            model_name="infrastructure",
            name="badge_en",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Бейдж/заголовка (EN)"
            ),
        ),
        migrations.AddField(
            model_name="infrastructure",
            name="badge_kg",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Бейдж/заголовка (KG)"
            ),
        ),
        migrations.AddField(
            model_name="infrastructure",
            name="badge_ru",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Бейдж/заголовка (RU)"
            ),
        ),
        migrations.AddField(
            model_name="infrastructure",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sportsection",
            name="coach_rank_en",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Звание тренера (EN)"
            ),
        ),
        migrations.AddField(
            model_name="sportsection",
            name="coach_rank_kg",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Звание тренера (KG)"
            ),
        ),
        migrations.AddField(
            model_name="sportsection",
            name="coach_rank_ru",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Звание тренера (RU)"
            ),
        ),
        migrations.AddField(
            model_name="sportsection",
            name="schedule_en",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Расписание (EN)"
            ),
        ),
        migrations.AddField(
            model_name="sportsection",
            name="schedule_kg",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Расписание (KG)"
            ),
        ),
        migrations.AddField(
            model_name="sportsection",
            name="schedule_ru",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Расписание (RU)"
            ),
        ),
        migrations.AddField(
            model_name="trainingschedule",
            name="location_en",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Место проведения (EN)"
            ),
        ),
        migrations.AddField(
            model_name="trainingschedule",
            name="location_kg",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Место проведения (KG)"
            ),
        ),
        migrations.AddField(
            model_name="trainingschedule",
            name="location_ru",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Место проведения (RU)"
            ),
        ),
        migrations.CreateModel(
            name="InfrastructureStatistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label_ru",
                    models.CharField(max_length=100, verbose_name="Подпись (RU)"),
                ),
                (
                    "label_kg",
                    models.CharField(max_length=100, verbose_name="Подпись (KG)"),
                ),
                (
                    "label_en",
                    models.CharField(max_length=100, verbose_name="Подпись (EN)"),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Например: 25+, 5000+",
                        max_length=50,
                        verbose_name="Значение",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="📊", max_length=10, verbose_name="Иконка"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Порядок"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "infrastructure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to="sports.infrastructure",
                        verbose_name="Инфраструктура",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статистика инфраструктуры",
                "verbose_name_plural": "Статистика инфраструктуры",
                "ordering": ["infrastructure", "order"],
                "indexes": [
                    models.Index(
                        fields=["infrastructure", "order"],
                        name="sports_infr_infrast_3d6093_idx",
                    )
                ],
            },
        ),
    ]
