# Generated by Django 5.1.2 on 2025-10-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sports", "0005_remove_infrastructure_stat_1_icon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="athlete_name_en",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Имя спортсмена/команды (EN)"
            ),
        ),
        migrations.AddField(
            model_name="achievement",
            name="athlete_name_kg",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Имя спортсмена/команды (KG)"
            ),
        ),
        migrations.AddField(
            model_name="achievement",
            name="athlete_name_ru",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Имя спортсмена/команды (RU)"
            ),
        ),
        migrations.AddField(
            model_name="sportsection",
            name="coach_name_en",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="ФИО тренера (EN)"
            ),
        ),
        migrations.AddField(
            model_name="sportsection",
            name="coach_name_kg",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="ФИО тренера (KG)"
            ),
        ),
        migrations.AddField(
            model_name="sportsection",
            name="coach_name_ru",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="ФИО тренера (RU)"
            ),
        ),
    ]
