# Generated by Django 5.1.2 on 2025-10-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sports", "0009_translate_existing_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="competition_en",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Соревнование (EN)"
            ),
        ),
        migrations.AddField(
            model_name="achievement",
            name="competition_kg",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Соревнование (KG)"
            ),
        ),
        migrations.AddField(
            model_name="achievement",
            name="competition_ru",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Соревнование (RU)"
            ),
        ),
        migrations.AddField(
            model_name="achievement",
            name="result_en",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Результат (EN)"
            ),
        ),
        migrations.AddField(
            model_name="achievement",
            name="result_kg",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Результат (KG)"
            ),
        ),
        migrations.AddField(
            model_name="achievement",
            name="result_ru",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Результат (RU)"
            ),
        ),
        migrations.AddField(
            model_name="achievement",
            name="sport_en",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Вид спорта (EN)"
            ),
        ),
        migrations.AddField(
            model_name="achievement",
            name="sport_kg",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Вид спорта (KG)"
            ),
        ),
        migrations.AddField(
            model_name="achievement",
            name="sport_ru",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Вид спорта (RU)"
            ),
        ),
    ]
