# Generated by Django 5.1.2 on 2025-10-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sports", "0012_remove_achievement_athlete_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SportType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly id, e.g. 'game'",
                        max_length=100,
                        unique=True,
                        verbose_name="Идентификатор",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Название (RU)"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Название (EN)"
                    ),
                ),
                (
                    "name_kg",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Название (KG)"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="Иконка/emoji",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        db_index=True, default=0, verbose_name="Порядок"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Активно"
                    ),
                ),
            ],
            options={
                "verbose_name": "Вид спорта",
                "verbose_name_plural": "Виды спорта",
                "ordering": ("order", "slug"),
            },
        ),
    ]
