# Generated by Django 5.1.2 on 2025-10-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sports", "0016_consolidate_contacts_and_drop_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sportsection",
            options={
                "ordering": ["order", "name_ru"],
                "verbose_name": "Спортивная секция",
                "verbose_name_plural": "Спортивные секции",
            },
        ),
        migrations.AddField(
            model_name="sportsection",
            name="coach_name",
            field=models.CharField(
                default="", max_length=200, verbose_name="ФИО тренера"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sportsection",
            name="coach_rank",
            field=models.CharField(
                blank=True,
                help_text="Например: Мастер спорта, Заслуженный тренер",
                max_length=200,
                verbose_name="Звание тренера",
            ),
        ),
        migrations.AddField(
            model_name="sportsection",
            name="contact_info_en",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Контактная информация (EN)"
            ),
        ),
        migrations.AddField(
            model_name="sportsection",
            name="contact_info_kg",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Контактная информация (KG)"
            ),
        ),
        migrations.AddField(
            model_name="sportsection",
            name="contact_info_ru",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Контактная информация (RU)"
            ),
        ),
        migrations.AddField(
            model_name="sportsection",
            name="schedule",
            field=models.CharField(
                default="",
                help_text="Краткое расписание, например: Пн, Ср, Пт 18:00-20:00",
                max_length=200,
                verbose_name="Расписание",
            ),
            preserve_default=False,
        ),
    ]
