# Generated by Django 5.1.2 on 2025-10-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sports", "0017_alter_sportsection_options_sportsection_coach_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sportsection",
            name="coach_name",
        ),
        migrations.RemoveField(
            model_name="sportsection",
            name="coach_rank",
        ),
        migrations.RemoveField(
            model_name="sportsection",
            name="contact_info_en",
        ),
        migrations.RemoveField(
            model_name="sportsection",
            name="contact_info_kg",
        ),
        migrations.RemoveField(
            model_name="sportsection",
            name="contact_info_ru",
        ),
        migrations.RemoveField(
            model_name="sportsection",
            name="schedule",
        ),
        migrations.AlterField(
            model_name="sportsection",
            name="coach_name_en",
            field=models.CharField(max_length=200, verbose_name="ФИО тренера (EN)"),
        ),
        migrations.AlterField(
            model_name="sportsection",
            name="coach_name_kg",
            field=models.CharField(max_length=200, verbose_name="ФИО тренера (KG)"),
        ),
        migrations.AlterField(
            model_name="sportsection",
            name="coach_name_ru",
            field=models.CharField(max_length=200, verbose_name="ФИО тренера (RU)"),
        ),
        migrations.AlterField(
            model_name="sportsection",
            name="schedule_en",
            field=models.CharField(max_length=200, verbose_name="Расписание (EN)"),
        ),
        migrations.AlterField(
            model_name="sportsection",
            name="schedule_kg",
            field=models.CharField(max_length=200, verbose_name="Расписание (KG)"),
        ),
        migrations.AlterField(
            model_name="sportsection",
            name="schedule_ru",
            field=models.CharField(max_length=200, verbose_name="Расписание (RU)"),
        ),
    ]
