# Generated by Django 5.1.2 on 2025-10-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstranslation',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('kg', 'Кыргызча')], max_length=2, verbose_name='Язык'),
        ),
    ]
