# Generated by Django 5.1.2 on 2025-10-27 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newstranslation_language'),
        ('news', '0002_update_language_code'),
    ]

    operations = [
    ]
