# Generated by Django 5.1.2 on 2026-01-14 12:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_image_newsimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Изображение'),
        ),
    ]
