# Generated by Django 5.1.2 on 2025-10-08 13:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название (RU)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Название (EN)')),
                ('name_kg', models.CharField(max_length=100, verbose_name='Название (KG)')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Категория клуба',
                'verbose_name_plural': 'Категории клубов',
                'ordering': ['order', 'name_ru'],
            },
        ),
        migrations.CreateModel(
            name='ClubStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='Значение')),
                ('label_ru', models.CharField(max_length=200, verbose_name='Метка (RU)')),
                ('label_en', models.CharField(max_length=200, verbose_name='Метка (EN)')),
                ('label_kg', models.CharField(max_length=200, verbose_name='Метка (KG)')),
                ('icon', models.CharField(default='📊', max_length=10, verbose_name='Иконка')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Статистика клубов',
                'verbose_name_plural': 'Статистика клубов',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='🎯', max_length=10, verbose_name='Иконка (эмодзи)')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('recruiting', 'Набор'), ('inactive', 'Неактивен')], default='active', max_length=20, verbose_name='Статус')),
                ('members_count', models.IntegerField(default=0, verbose_name='Количество участников')),
                ('join_link', models.URLField(help_text='Ссылка на форму регистрации или Telegram группу', max_length=500, validators=[django.core.validators.URLValidator()], verbose_name='Ссылка для присоединения')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название (RU)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Название (EN)')),
                ('name_kg', models.CharField(max_length=200, verbose_name='Название (KG)')),
                ('short_description_ru', models.CharField(max_length=300, verbose_name='Краткое описание (RU)')),
                ('short_description_en', models.CharField(max_length=300, verbose_name='Краткое описание (EN)')),
                ('short_description_kg', models.CharField(max_length=300, verbose_name='Краткое описание (KG)')),
                ('description_ru', models.TextField(verbose_name='Описание (RU)')),
                ('description_en', models.TextField(verbose_name='Описание (EN)')),
                ('description_kg', models.TextField(verbose_name='Описание (KG)')),
                ('goals_ru', models.TextField(help_text='Основные цели клуба', verbose_name='Цели и задачи (RU)')),
                ('goals_en', models.TextField(help_text='Основные цели клуба', verbose_name='Цели и задачи (EN)')),
                ('goals_kg', models.TextField(help_text='Основные цели клуба', verbose_name='Цели и задачи (KG)')),
                ('motivation_ru', models.TextField(help_text='Почему стоит вступить в клуб', verbose_name='Мотивация для вступления (RU)')),
                ('motivation_en', models.TextField(help_text='Почему стоит вступить в клуб', verbose_name='Мотивация для вступления (EN)')),
                ('motivation_kg', models.TextField(help_text='Почему стоит вступить в клуб', verbose_name='Мотивация для вступления (KG)')),
                ('meetings_ru', models.CharField(help_text='Например: Каждую среду 19:00', max_length=200, verbose_name='Расписание встреч (RU)')),
                ('meetings_en', models.CharField(help_text='Например: Every Wednesday 7 PM', max_length=200, verbose_name='Расписание встреч (EN)')),
                ('meetings_kg', models.CharField(help_text='Например: Ар шаршемби саат 19:00', max_length=200, verbose_name='Расписание встреч (KG)')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Список тегов для поиска', verbose_name='Теги')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='student_clubs.clubcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Клуб',
                'verbose_name_plural': 'Клубы',
                'ordering': ['order', '-members_count', 'name_ru'],
            },
        ),
        migrations.CreateModel(
            name='ClubLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200, verbose_name='ФИО (RU)')),
                ('name_en', models.CharField(max_length=200, verbose_name='ФИО (EN)')),
                ('name_kg', models.CharField(max_length=200, verbose_name='ФИО (KG)')),
                ('role_ru', models.CharField(max_length=200, verbose_name='Роль (RU)')),
                ('role_en', models.CharField(max_length=200, verbose_name='Роль (EN)')),
                ('role_kg', models.CharField(max_length=200, verbose_name='Роль (KG)')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='club_leaders/', verbose_name='Фото')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='student_clubs.club', verbose_name='Клуб')),
            ],
            options={
                'verbose_name': 'Руководитель клуба',
                'verbose_name_plural': 'Руководители клубов',
                'ordering': ['order', 'name_ru'],
            },
        ),
    ]
