# Generated by Django 5.1.2 on 2025-10-12 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_clubs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name_ru",
                    models.CharField(max_length=200, verbose_name="ФИО (RU)"),
                ),
                (
                    "full_name_en",
                    models.CharField(max_length=200, verbose_name="ФИО (EN)"),
                ),
                (
                    "full_name_kg",
                    models.CharField(max_length=200, verbose_name="ФИО (KG)"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Телефон"
                    ),
                ),
                (
                    "faculty_ru",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Факультет (RU)",
                    ),
                ),
                (
                    "faculty_en",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Факультет (EN)",
                    ),
                ),
                (
                    "faculty_kg",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Факультет (KG)",
                    ),
                ),
                (
                    "year_of_study",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                        ],
                        null=True,
                        verbose_name="Курс",
                    ),
                ),
                (
                    "major_ru",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Специальность (RU)",
                    ),
                ),
                (
                    "major_en",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Специальность (EN)",
                    ),
                ),
                (
                    "major_kg",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Специальность (KG)",
                    ),
                ),
                (
                    "bio_ru",
                    models.TextField(blank=True, null=True, verbose_name="О себе (RU)"),
                ),
                (
                    "bio_en",
                    models.TextField(blank=True, null=True, verbose_name="О себе (EN)"),
                ),
                (
                    "bio_kg",
                    models.TextField(blank=True, null=True, verbose_name="О себе (KG)"),
                ),
                (
                    "interests",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Список интересов для рекомендаций клубов",
                        verbose_name="Интересы",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="student_profiles/",
                        verbose_name="Фото профиля",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль студента",
                "verbose_name_plural": "Профили студентов",
                "ordering": ["full_name_ru"],
            },
        ),
        migrations.CreateModel(
            name="ClubMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "На рассмотрении"),
                            ("approved", "Участник"),
                            ("leader", "Руководитель"),
                            ("rejected", "Отклонено"),
                            ("left", "Покинул клуб"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата присоединения"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "motivation_text",
                    models.TextField(
                        blank=True,
                        help_text="Почему студент хочет вступить в клуб",
                        null=True,
                        verbose_name="Мотивация для вступления",
                    ),
                ),
                (
                    "role_ru",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Роль в клубе (RU)",
                    ),
                ),
                (
                    "role_en",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Роль в клубе (EN)",
                    ),
                ),
                (
                    "role_kg",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Роль в клубе (KG)",
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="student_clubs.club",
                        verbose_name="Клуб",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="student_clubs.studentprofile",
                        verbose_name="Студент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Членство в клубе",
                "verbose_name_plural": "Членство в клубах",
                "ordering": ["-joined_at"],
                "unique_together": {("student", "club")},
            },
        ),
    ]
