# Generated by Django 5.2.7 on 2025-10-13 07:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_clubs", "0002_studentprofile_clubmembership"),
    ]

    operations = [
        migrations.CreateModel(
            name="CouncilInitiative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="🚀",
                        max_length=30,
                        verbose_name="Icon (emoji or class)",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Sort Order")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="in_progress",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=200, verbose_name="Title (RU)"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=200, verbose_name="Title (EN)"),
                ),
                (
                    "title_kg",
                    models.CharField(max_length=200, verbose_name="Title (KG)"),
                ),
                ("description_ru", models.TextField(verbose_name="Description (RU)")),
                ("description_en", models.TextField(verbose_name="Description (EN)")),
                ("description_kg", models.TextField(verbose_name="Description (KG)")),
                (
                    "goals_ru",
                    models.TextField(blank=True, null=True, verbose_name="Goals (RU)"),
                ),
                (
                    "goals_en",
                    models.TextField(blank=True, null=True, verbose_name="Goals (EN)"),
                ),
                (
                    "goals_kg",
                    models.TextField(blank=True, null=True, verbose_name="Goals (KG)"),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End Date"),
                ),
            ],
            options={
                "verbose_name": "Student Council Initiative",
                "verbose_name_plural": "Student Council Initiatives",
                "ordering": ["order", "status", "start_date"],
            },
        ),
        migrations.CreateModel(
            name="CouncilMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="student_council/members/",
                        verbose_name="Avatar",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Sort Order")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("president", "President"),
                            ("vice_president", "Vice President"),
                            ("secretary", "Secretary"),
                            ("treasurer", "Treasurer"),
                            ("member", "Member"),
                        ],
                        default="member",
                        max_length=20,
                        verbose_name="Role",
                    ),
                ),
                ("name_ru", models.CharField(max_length=100, verbose_name="Name (RU)")),
                ("name_en", models.CharField(max_length=100, verbose_name="Name (EN)")),
                ("name_kg", models.CharField(max_length=100, verbose_name="Name (KG)")),
                (
                    "position_ru",
                    models.CharField(max_length=200, verbose_name="Position (RU)"),
                ),
                (
                    "position_en",
                    models.CharField(max_length=200, verbose_name="Position (EN)"),
                ),
                (
                    "position_kg",
                    models.CharField(max_length=200, verbose_name="Position (KG)"),
                ),
                (
                    "department_ru",
                    models.CharField(max_length=200, verbose_name="Department (RU)"),
                ),
                (
                    "department_en",
                    models.CharField(max_length=200, verbose_name="Department (EN)"),
                ),
                (
                    "department_kg",
                    models.CharField(max_length=200, verbose_name="Department (KG)"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Phone"
                    ),
                ),
                (
                    "instagram",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                        verbose_name="Instagram",
                    ),
                ),
                (
                    "linkedin",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                        verbose_name="LinkedIn",
                    ),
                ),
                (
                    "bio_ru",
                    models.TextField(
                        blank=True, null=True, verbose_name="Biography (RU)"
                    ),
                ),
                (
                    "bio_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Biography (EN)"
                    ),
                ),
                (
                    "bio_kg",
                    models.TextField(
                        blank=True, null=True, verbose_name="Biography (KG)"
                    ),
                ),
                (
                    "achievements_ru",
                    models.TextField(
                        blank=True, null=True, verbose_name="Achievements (RU)"
                    ),
                ),
                (
                    "achievements_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Achievements (EN)"
                    ),
                ),
                (
                    "achievements_kg",
                    models.TextField(
                        blank=True, null=True, verbose_name="Achievements (KG)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Council Member",
                "verbose_name_plural": "Student Council Members",
                "ordering": ["order", "role", "name_ru"],
            },
        ),
        migrations.CreateModel(
            name="CouncilStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Statistic Key"
                    ),
                ),
                (
                    "value",
                    models.CharField(max_length=50, verbose_name="Statistic Value"),
                ),
                (
                    "label_ru",
                    models.CharField(max_length=100, verbose_name="Label (RU)"),
                ),
                (
                    "label_en",
                    models.CharField(max_length=100, verbose_name="Label (EN)"),
                ),
                (
                    "label_kg",
                    models.CharField(max_length=100, verbose_name="Label (KG)"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Sort Order")),
            ],
            options={
                "verbose_name": "Student Council Statistic",
                "verbose_name_plural": "Student Council Statistics",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="DisabilityContactPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="👤",
                        max_length=30,
                        verbose_name="Icon (emoji or class)",
                    ),
                ),
                ("name_ru", models.CharField(max_length=100, verbose_name="Name (RU)")),
                ("name_en", models.CharField(max_length=100, verbose_name="Name (EN)")),
                ("name_kg", models.CharField(max_length=100, verbose_name="Name (KG)")),
                (
                    "position_ru",
                    models.CharField(max_length=200, verbose_name="Position (RU)"),
                ),
                (
                    "position_en",
                    models.CharField(max_length=200, verbose_name="Position (EN)"),
                ),
                (
                    "position_kg",
                    models.CharField(max_length=200, verbose_name="Position (KG)"),
                ),
                ("phone", models.CharField(max_length=50, verbose_name="Phone Number")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "hours_ru",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Office Hours (RU)",
                    ),
                ),
                (
                    "hours_en",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Office Hours (EN)",
                    ),
                ),
                (
                    "hours_kg",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Office Hours (KG)",
                    ),
                ),
                (
                    "location_ru",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Location (RU)",
                    ),
                ),
                (
                    "location_en",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Location (EN)",
                    ),
                ),
                (
                    "location_kg",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Location (KG)",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Sort Order")),
            ],
            options={
                "verbose_name": "Disability Contact Person",
                "verbose_name_plural": "Disability Contact People",
                "ordering": ["order", "name_ru"],
            },
        ),
        migrations.CreateModel(
            name="DisabilityEmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=200, verbose_name="Title (RU)"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=200, verbose_name="Title (EN)"),
                ),
                (
                    "title_kg",
                    models.CharField(max_length=200, verbose_name="Title (KG)"),
                ),
                ("description_ru", models.TextField(verbose_name="Description (RU)")),
                ("description_en", models.TextField(verbose_name="Description (EN)")),
                ("description_kg", models.TextField(verbose_name="Description (KG)")),
                (
                    "phone",
                    models.CharField(max_length=50, verbose_name="Emergency Phone"),
                ),
                (
                    "phone_link",
                    models.CharField(
                        max_length=50, verbose_name="Emergency Phone Link (tel:)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Disability Emergency Contact",
                "verbose_name_plural": "Disability Emergency Contacts",
            },
        ),
        migrations.CreateModel(
            name="DisabilityResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="📚",
                        max_length=30,
                        verbose_name="Icon (emoji or class)",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=200, verbose_name="Resource Name (RU)"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=200, verbose_name="Resource Name (EN)"),
                ),
                (
                    "name_kg",
                    models.CharField(max_length=200, verbose_name="Resource Name (KG)"),
                ),
                ("description_ru", models.TextField(verbose_name="Description (RU)")),
                ("description_en", models.TextField(verbose_name="Description (EN)")),
                ("description_kg", models.TextField(verbose_name="Description (KG)")),
                (
                    "url",
                    models.URLField(
                        max_length=500,
                        validators=[django.core.validators.URLValidator()],
                        verbose_name="Resource URL",
                    ),
                ),
                (
                    "type_ru",
                    models.CharField(
                        choices=[
                            ("guide", "Guide"),
                            ("tool", "Tool"),
                            ("service", "Service"),
                            ("document", "Document"),
                            ("video", "Video"),
                        ],
                        default="guide",
                        max_length=30,
                        verbose_name="Resource Type (RU)",
                    ),
                ),
                (
                    "type_en",
                    models.CharField(
                        choices=[
                            ("guide", "Guide"),
                            ("tool", "Tool"),
                            ("service", "Service"),
                            ("document", "Document"),
                            ("video", "Video"),
                        ],
                        default="guide",
                        max_length=30,
                        verbose_name="Resource Type (EN)",
                    ),
                ),
                (
                    "type_kg",
                    models.CharField(
                        choices=[
                            ("guide", "Guide"),
                            ("tool", "Tool"),
                            ("service", "Service"),
                            ("document", "Document"),
                            ("video", "Video"),
                        ],
                        default="guide",
                        max_length=30,
                        verbose_name="Resource Type (KG)",
                    ),
                ),
                (
                    "format_ru",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("website", "Website"),
                            ("app", "Application"),
                            ("video", "Video"),
                            ("text", "Text"),
                        ],
                        default="website",
                        max_length=30,
                        verbose_name="Format (RU)",
                    ),
                ),
                (
                    "format_en",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("website", "Website"),
                            ("app", "Application"),
                            ("video", "Video"),
                            ("text", "Text"),
                        ],
                        default="website",
                        max_length=30,
                        verbose_name="Format (EN)",
                    ),
                ),
                (
                    "format_kg",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("website", "Website"),
                            ("app", "Application"),
                            ("video", "Video"),
                            ("text", "Text"),
                        ],
                        default="website",
                        max_length=30,
                        verbose_name="Format (KG)",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Sort Order")),
            ],
            options={
                "verbose_name": "Disability Resource",
                "verbose_name_plural": "Disability Resources",
                "ordering": ["order", "name_ru"],
            },
        ),
        migrations.CreateModel(
            name="DisabilitySupportService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="🌟",
                        max_length=30,
                        verbose_name="Icon (emoji or class)",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Sort Order")),
                (
                    "title_ru",
                    models.CharField(max_length=200, verbose_name="Title (RU)"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=200, verbose_name="Title (EN)"),
                ),
                (
                    "title_kg",
                    models.CharField(max_length=200, verbose_name="Title (KG)"),
                ),
                ("description_ru", models.TextField(verbose_name="Description (RU)")),
                ("description_en", models.TextField(verbose_name="Description (EN)")),
                ("description_kg", models.TextField(verbose_name="Description (KG)")),
                (
                    "features_ru",
                    models.TextField(
                        blank=True,
                        help_text="Enter features separated by new lines",
                        null=True,
                        verbose_name="Features (RU)",
                    ),
                ),
                (
                    "features_en",
                    models.TextField(
                        blank=True,
                        help_text="Enter features separated by new lines",
                        null=True,
                        verbose_name="Features (EN)",
                    ),
                ),
                (
                    "features_kg",
                    models.TextField(
                        blank=True,
                        help_text="Enter features separated by new lines",
                        null=True,
                        verbose_name="Features (KG)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disability Support Service",
                "verbose_name_plural": "Disability Support Services",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ScholarshipProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=200, verbose_name="Название программы (RU)"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=200, verbose_name="Название программы (EN)"
                    ),
                ),
                (
                    "name_kg",
                    models.CharField(
                        max_length=200, verbose_name="Название программы (KG)"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(verbose_name="Описание программы (RU)"),
                ),
                (
                    "description_en",
                    models.TextField(verbose_name="Описание программы (EN)"),
                ),
                (
                    "description_kg",
                    models.TextField(verbose_name="Описание программы (KG)"),
                ),
                (
                    "eligibility_criteria_ru",
                    models.TextField(verbose_name="Критерии отбора (RU)"),
                ),
                (
                    "eligibility_criteria_en",
                    models.TextField(verbose_name="Критерии отбора (EN)"),
                ),
                (
                    "eligibility_criteria_kg",
                    models.TextField(verbose_name="Критерии отбора (KG)"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сумма стипендии"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="KGS", max_length=10, verbose_name="Валюта"
                    ),
                ),
                (
                    "application_deadline",
                    models.DateField(verbose_name="Дедлайн подачи заявок"),
                ),
                (
                    "application_link",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка для подачи заявки"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Контактный email",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Контактный телефон",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Scholarship Program",
                "verbose_name_plural": "Scholarship Programs",
                "ordering": ["name_ru"],
            },
        ),
        migrations.CreateModel(
            name="VisaSupportContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name_ru",
                    models.CharField(max_length=200, verbose_name="ФИО (RU)"),
                ),
                (
                    "full_name_en",
                    models.CharField(max_length=200, verbose_name="ФИО (EN)"),
                ),
                (
                    "full_name_kg",
                    models.CharField(max_length=200, verbose_name="ФИО (KG)"),
                ),
                (
                    "position_ru",
                    models.CharField(max_length=200, verbose_name="Должность (RU)"),
                ),
                (
                    "position_en",
                    models.CharField(max_length=200, verbose_name="Должность (EN)"),
                ),
                (
                    "position_kg",
                    models.CharField(max_length=200, verbose_name="Должность (KG)"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Телефон"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="visa_support/",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "office_location_ru",
                    models.CharField(
                        max_length=200, verbose_name="Расположение офиса (RU)"
                    ),
                ),
                (
                    "office_location_en",
                    models.CharField(
                        max_length=200, verbose_name="Расположение офиса (EN)"
                    ),
                ),
                (
                    "office_location_kg",
                    models.CharField(
                        max_length=200, verbose_name="Расположение офиса (KG)"
                    ),
                ),
                (
                    "office_hours_ru",
                    models.CharField(max_length=200, verbose_name="Часы приема (RU)"),
                ),
                (
                    "office_hours_en",
                    models.CharField(max_length=200, verbose_name="Часы приема (EN)"),
                ),
                (
                    "office_hours_kg",
                    models.CharField(max_length=200, verbose_name="Часы приема (KG)"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Visa Support Contact",
                "verbose_name_plural": "Visa Support Contacts",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="VisaSupportService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=200, verbose_name="Заголовок (RU)"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=200, verbose_name="Заголовок (EN)"),
                ),
                (
                    "title_kg",
                    models.CharField(max_length=200, verbose_name="Заголовок (KG)"),
                ),
                ("description_ru", models.TextField(verbose_name="Описание (RU)")),
                ("description_en", models.TextField(verbose_name="Описание (EN)")),
                ("description_kg", models.TextField(verbose_name="Описание (KG)")),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, verbose_name="Выделенный сервис"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Иконка (класс)",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Visa Support Service",
                "verbose_name_plural": "Visa Support Services",
                "ordering": ["order"],
            },
        ),
        migrations.AlterModelOptions(
            name="club",
            options={
                "ordering": ["order", "-members_count", "name_ru"],
                "verbose_name": "Club",
                "verbose_name_plural": "Clubs",
            },
        ),
        migrations.AlterModelOptions(
            name="clubcategory",
            options={
                "ordering": ["order", "name_ru"],
                "verbose_name": "Club Category",
                "verbose_name_plural": "Club Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="clubleader",
            options={
                "ordering": ["order", "name_ru"],
                "verbose_name": "Club Leader",
                "verbose_name_plural": "Club Leaders",
            },
        ),
        migrations.AlterModelOptions(
            name="clubmembership",
            options={
                "ordering": ["-joined_at"],
                "verbose_name": "Club Membership",
                "verbose_name_plural": "Club Memberships",
            },
        ),
        migrations.AlterModelOptions(
            name="clubstats",
            options={
                "ordering": ["order"],
                "verbose_name": "Club Statistics",
                "verbose_name_plural": "Club Statistics",
            },
        ),
        migrations.AlterModelOptions(
            name="studentprofile",
            options={
                "ordering": ["full_name_ru"],
                "verbose_name": "Student Profile",
                "verbose_name_plural": "Student Profiles",
            },
        ),
        migrations.CreateModel(
            name="CouncilEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="📅",
                        max_length=30,
                        verbose_name="Icon (emoji or class)",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Sort Order")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("ongoing", "Ongoing"),
                            ("past", "Past"),
                        ],
                        default="upcoming",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=200, verbose_name="Title (RU)"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=200, verbose_name="Title (EN)"),
                ),
                (
                    "title_kg",
                    models.CharField(max_length=200, verbose_name="Title (KG)"),
                ),
                ("description_ru", models.TextField(verbose_name="Description (RU)")),
                ("description_en", models.TextField(verbose_name="Description (EN)")),
                ("description_kg", models.TextField(verbose_name="Description (KG)")),
                ("date", models.DateTimeField(verbose_name="Event Date and Time")),
                (
                    "location_ru",
                    models.CharField(max_length=200, verbose_name="Location (RU)"),
                ),
                (
                    "location_en",
                    models.CharField(max_length=200, verbose_name="Location (EN)"),
                ),
                (
                    "location_kg",
                    models.CharField(max_length=200, verbose_name="Location (KG)"),
                ),
                (
                    "registration_link",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                        verbose_name="Registration Link",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="student_council/events/",
                        verbose_name="Event Image",
                    ),
                ),
                (
                    "initiative",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="student_clubs.councilinitiative",
                        verbose_name="Related Initiative",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Council Event",
                "verbose_name_plural": "Student Council Events",
                "ordering": ["order", "status", "date"],
            },
        ),
        migrations.AddField(
            model_name="councilinitiative",
            name="lead_members",
            field=models.ManyToManyField(
                blank=True,
                related_name="led_initiatives",
                to="student_clubs.councilmember",
                verbose_name="Lead Members",
            ),
        ),
        migrations.CreateModel(
            name="ScholarshipRequiredDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=200, verbose_name="Название документа (RU)"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=200, verbose_name="Название документа (EN)"
                    ),
                ),
                (
                    "name_kg",
                    models.CharField(
                        max_length=200, verbose_name="Название документа (KG)"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание документа (RU)"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание документа (EN)"
                    ),
                ),
                (
                    "description_kg",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание документа (KG)"
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=True, verbose_name="Обязательный"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Порядок"),
                ),
                (
                    "scholarship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="required_documents",
                        to="student_clubs.scholarshipprogram",
                        verbose_name="Стипендиальная программа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Required Document",
                "verbose_name_plural": "Required Documents",
                "ordering": ["scholarship", "order"],
            },
        ),
    ]
