# Generated by Django 5.2.7 on 2025-10-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_clubs", "0003_councilinitiative_councilmember_councilstats_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialCommunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        max_length=200, verbose_name="Community Title (RU)"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=200, verbose_name="Community Title (EN)"
                    ),
                ),
                (
                    "title_kg",
                    models.CharField(
                        max_length=200, verbose_name="Community Title (KG)"
                    ),
                ),
                ("description_ru", models.TextField(verbose_name="Description (RU)")),
                ("description_en", models.TextField(verbose_name="Description (EN)")),
                ("description_kg", models.TextField(verbose_name="Description (KG)")),
                (
                    "members_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Members Count"
                    ),
                ),
                (
                    "posts_count",
                    models.PositiveIntegerField(default=0, verbose_name="Posts Count"),
                ),
                (
                    "network",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("twitter", "Twitter/X"),
                            ("telegram", "Telegram"),
                            ("whatsapp", "WhatsApp"),
                            ("vk", "VKontakte"),
                            ("youtube", "YouTube"),
                            ("tiktok", "TikTok"),
                            ("linkedin", "LinkedIn"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Social Network",
                    ),
                ),
                ("url", models.URLField(verbose_name="Community URL")),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="social_communities/",
                        verbose_name="Banner Image",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, verbose_name="Featured Community"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, verbose_name="Verified Community"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Order"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Social Community",
                "verbose_name_plural": "Social Communities",
                "ordering": ["order", "-members_count"],
            },
        ),
        migrations.CreateModel(
            name="SocialNetworkAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "network",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("twitter", "Twitter/X"),
                            ("telegram", "Telegram"),
                            ("whatsapp", "WhatsApp"),
                            ("vk", "VKontakte"),
                            ("youtube", "YouTube"),
                            ("tiktok", "TikTok"),
                            ("linkedin", "LinkedIn"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Social Network",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=200, verbose_name="Account Name (RU)"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=200, verbose_name="Account Name (EN)"),
                ),
                (
                    "name_kg",
                    models.CharField(max_length=200, verbose_name="Account Name (KG)"),
                ),
                (
                    "description_ru",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description (RU)"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description (EN)"
                    ),
                ),
                (
                    "description_kg",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description (KG)"
                    ),
                ),
                ("url", models.URLField(verbose_name="Profile URL")),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Username"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="E.g. 'fa-facebook', 'fa-instagram'",
                        max_length=50,
                        null=True,
                        verbose_name="Icon Class (FontAwesome)",
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#000000",
                        help_text="E.g. #3b5998 for Facebook",
                        max_length=7,
                        verbose_name="Brand Color (Hex)",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Featured Account"),
                ),
                (
                    "is_official",
                    models.BooleanField(default=True, verbose_name="Official Account"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Order"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Social Network Account",
                "verbose_name_plural": "Social Network Accounts",
                "ordering": ["order", "network"],
            },
        ),
        migrations.CreateModel(
            name="StudentContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=200, verbose_name="Title (RU)"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=200, verbose_name="Title (EN)"),
                ),
                (
                    "title_kg",
                    models.CharField(max_length=200, verbose_name="Title (KG)"),
                ),
                ("description_ru", models.TextField(verbose_name="Description (RU)")),
                ("description_en", models.TextField(verbose_name="Description (EN)")),
                ("description_kg", models.TextField(verbose_name="Description (KG)")),
                (
                    "contact_name_ru",
                    models.CharField(max_length=200, verbose_name="Contact Name (RU)"),
                ),
                (
                    "contact_name_en",
                    models.CharField(max_length=200, verbose_name="Contact Name (EN)"),
                ),
                (
                    "contact_name_kg",
                    models.CharField(max_length=200, verbose_name="Contact Name (KG)"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=50, verbose_name="Phone")),
                (
                    "office_location_ru",
                    models.CharField(
                        max_length=200, verbose_name="Office Location (RU)"
                    ),
                ),
                (
                    "office_location_en",
                    models.CharField(
                        max_length=200, verbose_name="Office Location (EN)"
                    ),
                ),
                (
                    "office_location_kg",
                    models.CharField(
                        max_length=200, verbose_name="Office Location (KG)"
                    ),
                ),
                (
                    "office_hours_ru",
                    models.CharField(max_length=200, verbose_name="Office Hours (RU)"),
                ),
                (
                    "office_hours_en",
                    models.CharField(max_length=200, verbose_name="Office Hours (EN)"),
                ),
                (
                    "office_hours_kg",
                    models.CharField(max_length=200, verbose_name="Office Hours (KG)"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Featured Contact"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contact_info/",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Order"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Student Contact Info",
                "verbose_name_plural": "Student Contact Info",
                "ordering": ["order"],
            },
        ),
    ]
