# Generated by Django 5.2.7 on 2025-10-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_clubs", "0004_socialcommunity_socialnetworkaccount_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="disabilityemergencycontact",
            options={
                "ordering": ["order", "title_ru"],
                "verbose_name": "Disability Emergency Contact",
                "verbose_name_plural": "Disability Emergency Contacts",
            },
        ),
        migrations.AddField(
            model_name="disabilityemergencycontact",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Display order"),
        ),
    ]
