# Generated by Django 5.2.7 on 2025-10-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_clubs", "0005_alter_disabilityemergencycontact_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisabilityPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=200, verbose_name="Title (RU)"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=200, verbose_name="Title (EN)"),
                ),
                (
                    "title_kg",
                    models.CharField(max_length=200, verbose_name="Title (KG)"),
                ),
                ("description_ru", models.TextField(verbose_name="Description (RU)")),
                ("description_en", models.TextField(verbose_name="Description (EN)")),
                ("description_kg", models.TextField(verbose_name="Description (KG)")),
                ("order", models.IntegerField(default=0, verbose_name="Sort Order")),
            ],
            options={
                "verbose_name": "Disability Page Content",
                "verbose_name_plural": "Disability Page Content",
                "ordering": ["order", "id"],
            },
        ),
    ]
