# Generated by Django 5.2.7 on 2025-10-15 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_clubs", "0006_disabilitypage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeDeadline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.CharField(max_length=100, verbose_name="Дата дедлайна"),
                ),
                (
                    "program_ru",
                    models.CharField(max_length=255, verbose_name="Программа (RU)"),
                ),
                (
                    "program_en",
                    models.CharField(max_length=255, verbose_name="Программа (EN)"),
                ),
                (
                    "program_kg",
                    models.CharField(max_length=255, verbose_name="Программа (KG)"),
                ),
                (
                    "days_left_ru",
                    models.CharField(max_length=100, verbose_name="Осталось дней (RU)"),
                ),
                (
                    "days_left_en",
                    models.CharField(max_length=100, verbose_name="Осталось дней (EN)"),
                ),
                (
                    "days_left_kg",
                    models.CharField(max_length=100, verbose_name="Осталось дней (KG)"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок отображения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Дедлайн программы обмена",
                "verbose_name_plural": "Дедлайны программ обмена",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ExchangeDurationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=100, verbose_name="Название (RU)"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=100, verbose_name="Название (EN)"),
                ),
                (
                    "name_kg",
                    models.CharField(max_length=100, verbose_name="Название (KG)"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Код типа длительности"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип длительности программы обмена",
                "verbose_name_plural": "Типы длительности программ обмена",
            },
        ),
        migrations.CreateModel(
            name="ExchangePageStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="🌍", max_length=20, verbose_name="Иконка (emoji)"
                    ),
                ),
                (
                    "value_ru",
                    models.CharField(max_length=50, verbose_name="Значение (RU)"),
                ),
                (
                    "value_en",
                    models.CharField(max_length=50, verbose_name="Значение (EN)"),
                ),
                (
                    "value_kg",
                    models.CharField(max_length=50, verbose_name="Значение (KG)"),
                ),
                (
                    "label_ru",
                    models.CharField(max_length=100, verbose_name="Подпись (RU)"),
                ),
                (
                    "label_en",
                    models.CharField(max_length=100, verbose_name="Подпись (EN)"),
                ),
                (
                    "label_kg",
                    models.CharField(max_length=100, verbose_name="Подпись (KG)"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок отображения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Статистика страницы обмена",
                "verbose_name_plural": "Статистика страницы обмена",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ExchangeRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=100, verbose_name="Название (RU)"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=100, verbose_name="Название (EN)"),
                ),
                (
                    "name_kg",
                    models.CharField(max_length=100, verbose_name="Название (KG)"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Код региона"
                    ),
                ),
            ],
            options={
                "verbose_name": "Регион обмена",
                "verbose_name_plural": "Регионы обмена",
            },
        ),
        migrations.CreateModel(
            name="ExchangeProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "university_ru",
                    models.CharField(max_length=255, verbose_name="Университет (RU)"),
                ),
                (
                    "university_en",
                    models.CharField(max_length=255, verbose_name="Университет (EN)"),
                ),
                (
                    "university_kg",
                    models.CharField(max_length=255, verbose_name="Университет (KG)"),
                ),
                (
                    "country_ru",
                    models.CharField(max_length=100, verbose_name="Страна (RU)"),
                ),
                (
                    "country_en",
                    models.CharField(max_length=100, verbose_name="Страна (EN)"),
                ),
                (
                    "country_kg",
                    models.CharField(max_length=100, verbose_name="Страна (KG)"),
                ),
                (
                    "duration_ru",
                    models.CharField(max_length=100, verbose_name="Длительность (RU)"),
                ),
                (
                    "duration_en",
                    models.CharField(max_length=100, verbose_name="Длительность (EN)"),
                ),
                (
                    "duration_kg",
                    models.CharField(max_length=100, verbose_name="Длительность (KG)"),
                ),
                ("description_ru", models.TextField(verbose_name="Описание (RU)")),
                ("description_en", models.TextField(verbose_name="Описание (EN)")),
                ("description_kg", models.TextField(verbose_name="Описание (KG)")),
                (
                    "cost",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Стоимость"
                    ),
                ),
                (
                    "language_ru",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Язык обучения (RU)",
                    ),
                ),
                (
                    "language_en",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Язык обучения (EN)",
                    ),
                ),
                (
                    "language_kg",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Язык обучения (KG)",
                    ),
                ),
                (
                    "grants_available_ru",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Доступные гранты (RU)",
                    ),
                ),
                (
                    "grants_available_en",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Доступные гранты (EN)",
                    ),
                ),
                (
                    "grants_available_kg",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Доступные гранты (KG)",
                    ),
                ),
                (
                    "deadline",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Срок подачи",
                    ),
                ),
                (
                    "available_spots",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Доступные места"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="🎓", max_length=20, verbose_name="Иконка (emoji)"
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="Веб-сайт"),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("low", "Низкая"),
                            ("medium", "Средняя"),
                            ("high", "Высокая"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Сложность поступления",
                    ),
                ),
                (
                    "difficulty_label_ru",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Метка сложности (RU)",
                    ),
                ),
                (
                    "difficulty_label_en",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Метка сложности (EN)",
                    ),
                ),
                (
                    "difficulty_label_kg",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Метка сложности (KG)",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, verbose_name="Избранная программа"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Активная программа"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок отображения"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "duration_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="student_clubs.exchangedurationtype",
                        verbose_name="Тип длительности",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="student_clubs.exchangeregion",
                        verbose_name="Регион",
                    ),
                ),
            ],
            options={
                "verbose_name": "Программа обмена",
                "verbose_name_plural": "Программы обмена",
                "ordering": ["order", "university_en"],
            },
        ),
        migrations.CreateModel(
            name="ExchangeProgramBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_ru",
                    models.CharField(max_length=255, verbose_name="Преимущество (RU)"),
                ),
                (
                    "text_en",
                    models.CharField(max_length=255, verbose_name="Преимущество (EN)"),
                ),
                (
                    "text_kg",
                    models.CharField(max_length=255, verbose_name="Преимущество (KG)"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок отображения"
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benefits",
                        to="student_clubs.exchangeprogram",
                        verbose_name="Программа обмена",
                    ),
                ),
            ],
            options={
                "verbose_name": "Преимущество программы обмена",
                "verbose_name_plural": "Преимущества программ обмена",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ExchangeProgramCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=255, verbose_name="Название курса (RU)"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=255, verbose_name="Название курса (EN)"
                    ),
                ),
                (
                    "name_kg",
                    models.CharField(
                        max_length=255, verbose_name="Название курса (KG)"
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="available_courses",
                        to="student_clubs.exchangeprogram",
                        verbose_name="Программа обмена",
                    ),
                ),
            ],
            options={
                "verbose_name": "Доступный курс программы обмена",
                "verbose_name_plural": "Доступные курсы программ обмена",
            },
        ),
        migrations.CreateModel(
            name="ExchangeProgramRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_ru",
                    models.CharField(max_length=255, verbose_name="Требование (RU)"),
                ),
                (
                    "text_en",
                    models.CharField(max_length=255, verbose_name="Требование (EN)"),
                ),
                (
                    "text_kg",
                    models.CharField(max_length=255, verbose_name="Требование (KG)"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок отображения"
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="student_clubs.exchangeprogram",
                        verbose_name="Программа обмена",
                    ),
                ),
            ],
            options={
                "verbose_name": "Требование программы обмена",
                "verbose_name_plural": "Требования программ обмена",
                "ordering": ["order"],
            },
        ),
    ]
