# Generated by Django 5.2.7 on 2025-10-15 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student_clubs", "0007_exchangedeadline_exchangedurationtype_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exchangedeadline",
            options={
                "ordering": ["order"],
                "verbose_name": "Exchange Deadline",
                "verbose_name_plural": "Exchange Deadlines",
            },
        ),
        migrations.AlterModelOptions(
            name="exchangedurationtype",
            options={
                "verbose_name": "Exchange Duration Type",
                "verbose_name_plural": "Exchange Duration Types",
            },
        ),
        migrations.AlterModelOptions(
            name="exchangepagestat",
            options={
                "ordering": ["order"],
                "verbose_name": "Exchange Page Stat",
                "verbose_name_plural": "Exchange Page Stats",
            },
        ),
        migrations.AlterModelOptions(
            name="exchangeprogram",
            options={
                "ordering": ["order", "university_en"],
                "verbose_name": "Exchange Program",
                "verbose_name_plural": "Exchange Programs",
            },
        ),
        migrations.AlterModelOptions(
            name="exchangeprogrambenefit",
            options={
                "ordering": ["order"],
                "verbose_name": "Exchange Program Benefit",
                "verbose_name_plural": "Exchange Program Benefits",
            },
        ),
        migrations.AlterModelOptions(
            name="exchangeprogramcourse",
            options={
                "verbose_name": "Exchange Program Course",
                "verbose_name_plural": "Exchange Program Courses",
            },
        ),
        migrations.AlterModelOptions(
            name="exchangeprogramrequirement",
            options={
                "ordering": ["order"],
                "verbose_name": "Exchange Program Requirement",
                "verbose_name_plural": "Exchange Program Requirements",
            },
        ),
        migrations.AlterModelOptions(
            name="exchangeregion",
            options={
                "verbose_name": "Exchange Region",
                "verbose_name_plural": "Exchange Regions",
            },
        ),
    ]
