# Generated by Django 5.2.7 on 2025-10-15 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_clubs", "0008_alter_exchangedeadline_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportantUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=255, verbose_name="Title (RU)"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=255, verbose_name="Title (EN)"),
                ),
                (
                    "title_kg",
                    models.CharField(max_length=255, verbose_name="Title (KG)"),
                ),
                ("description_ru", models.TextField(verbose_name="Description (RU)")),
                ("description_en", models.TextField(verbose_name="Description (EN)")),
                ("description_kg", models.TextField(verbose_name="Description (KG)")),
                (
                    "date",
                    models.CharField(
                        help_text="Display date (e.g., 'Oct 15, 2023')",
                        max_length=100,
                        verbose_name="Display Date",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Order"
                    ),
                ),
                ("actual_date", models.DateTimeField(verbose_name="Actual Date")),
            ],
            options={
                "verbose_name": "Important Update",
                "verbose_name_plural": "Important Updates",
                "ordering": ["order", "-actual_date"],
            },
        ),
        migrations.CreateModel(
            name="InstructionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_ru", models.CharField(max_length=100, verbose_name="Name (RU)")),
                ("name_en", models.CharField(max_length=100, verbose_name="Name (EN)")),
                ("name_kg", models.CharField(max_length=100, verbose_name="Name (KG)")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Category Code"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Order"
                    ),
                ),
            ],
            options={
                "verbose_name": "Instruction Category",
                "verbose_name_plural": "Instruction Categories",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="InstructionDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_ru", models.CharField(max_length=255, verbose_name="Name (RU)")),
                ("name_en", models.CharField(max_length=255, verbose_name="Name (EN)")),
                ("name_kg", models.CharField(max_length=255, verbose_name="Name (KG)")),
                ("description_ru", models.TextField(verbose_name="Description (RU)")),
                ("description_en", models.TextField(verbose_name="Description (EN)")),
                ("description_kg", models.TextField(verbose_name="Description (KG)")),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF"),
                            ("DOC", "DOC"),
                            ("DOCX", "DOCX"),
                            ("XLS", "XLS"),
                            ("XLSX", "XLSX"),
                            ("PPT", "PPT"),
                            ("PPTX", "PPTX"),
                            ("ZIP", "ZIP"),
                        ],
                        max_length=10,
                        verbose_name="File Format",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="instructions/", verbose_name="Document File"
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        help_text="File size (e.g., '2.5 MB')",
                        max_length=20,
                        verbose_name="File Size",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0", max_length=20, verbose_name="Version"
                    ),
                ),
                (
                    "pages",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Number of Pages"
                    ),
                ),
                (
                    "downloads",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Download Count"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of tags",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Order"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="student_clubs.instructioncategory",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instruction Document",
                "verbose_name_plural": "Instruction Documents",
                "ordering": ["order", "-updated_at"],
            },
        ),
    ]
