# Generated by Django 5.2.7 on 2025-10-15 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_clubs", "0009_importantupdate_instructioncategory_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EbilimQuickLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=200, verbose_name="Name (Russian)"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=200, verbose_name="Name (English)"),
                ),
                (
                    "name_kg",
                    models.CharField(max_length=200, verbose_name="Name (Kyrgyz)"),
                ),
                (
                    "url",
                    models.URLField(
                        validators=[django.core.validators.URLValidator()],
                        verbose_name="URL",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="Emoji or icon code",
                        max_length=50,
                        verbose_name="Icon",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Order")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={
                "verbose_name": "E-learning Quick Link",
                "verbose_name_plural": "E-learning Quick Links",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="EbilimStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, verbose_name="Key")),
                ("value", models.CharField(max_length=100, verbose_name="Value")),
                (
                    "label_ru",
                    models.CharField(max_length=200, verbose_name="Label (Russian)"),
                ),
                (
                    "label_en",
                    models.CharField(max_length=200, verbose_name="Label (English)"),
                ),
                (
                    "label_kg",
                    models.CharField(max_length=200, verbose_name="Label (Kyrgyz)"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Order")),
            ],
            options={
                "verbose_name": "E-learning Statistic",
                "verbose_name_plural": "E-learning Statistics",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="EbilimSystemStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("maintenance", "Maintenance"),
                            ("issues", "Issues"),
                        ],
                        default="online",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "last_update",
                    models.DateTimeField(auto_now=True, verbose_name="Last Update"),
                ),
                (
                    "message_ru",
                    models.CharField(
                        max_length=200, verbose_name="Status Message (Russian)"
                    ),
                ),
                (
                    "message_en",
                    models.CharField(
                        max_length=200, verbose_name="Status Message (English)"
                    ),
                ),
                (
                    "message_kg",
                    models.CharField(
                        max_length=200, verbose_name="Status Message (Kyrgyz)"
                    ),
                ),
                (
                    "support_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Support Email"
                    ),
                ),
                (
                    "support_phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Support Phone"
                    ),
                ),
            ],
            options={
                "verbose_name": "E-learning System Status",
                "verbose_name_plural": "E-learning System Statuses",
            },
        ),
    ]
