# Generated by Django 5.1.2 on 2025-10-27 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_clubs', '0010_ebilimquicklink_ebilimstat_ebilimsystemstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EbilimQuickLink',
        ),
        migrations.DeleteModel(
            name='EbilimStat',
        ),
        migrations.DeleteModel(
            name='EbilimSystemStatus',
        ),
    ]
