# Generated by Django 5.1.2 on 2025-10-23 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_value', models.PositiveIntegerField(verbose_name='Конечное значение')),
                ('icon', models.CharField(help_text='Эмодзи или код иконки, например: 🎓, 🏆, ⚽', max_length=50, verbose_name='Иконка')),
                ('duration', models.PositiveIntegerField(default=2000, help_text='Время анимации счетчика в миллисекундах', verbose_name='Длительность анимации (мс)')),
                ('delay', models.PositiveIntegerField(default=0, help_text='Задержка перед началом анимации в миллисекундах', verbose_name='Задержка анимации (мс)')),
                ('color', models.CharField(choices=[('blue', 'Синий'), ('green', 'Зеленый'), ('red', 'Красный'), ('purple', 'Фиолетовый'), ('orange', 'Оранжевый'), ('cyan', 'Голубой')], default='blue', max_length=50, verbose_name='Цветовая схема')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Факт',
                'verbose_name_plural': 'Факты',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FactTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('kg', 'Кыргызча')], max_length=2, verbose_name='Язык')),
                ('label', models.CharField(max_length=200, verbose_name='Подпись')),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='facts.fact')),
            ],
            options={
                'verbose_name': 'Перевод факта',
                'verbose_name_plural': 'Переводы фактов',
                'unique_together': {('fact', 'language')},
            },
        ),
    ]
