# Generated by Django 5.1.2 on 2025-10-04 02:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accreditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('name_kg', models.CharField(blank=True, max_length=200, verbose_name='Название (KG)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Название (EN)')),
                ('organization', models.CharField(max_length=200, verbose_name='Аккредитующая организация')),
                ('organization_kg', models.CharField(blank=True, max_length=200, verbose_name='Аккредитующая организация (KG)')),
                ('organization_en', models.CharField(blank=True, max_length=200, verbose_name='Аккредитующая организация (EN)')),
                ('accreditation_type', models.CharField(choices=[('national', 'Национальная'), ('international', 'Международная'), ('institutional', 'Институциональная'), ('programmatic', 'Программная')], max_length=20, verbose_name='Тип аккредитации')),
                ('accreditation_type_kg', models.CharField(blank=True, max_length=100, verbose_name='Тип аккредитации (KG)')),
                ('accreditation_type_en', models.CharField(blank=True, max_length=100, verbose_name='Тип аккредитации (EN)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('description_kg', models.TextField(blank=True, verbose_name='Описание (KG)')),
                ('description_en', models.TextField(blank=True, verbose_name='Описание (EN)')),
                ('certificate_image', models.ImageField(blank=True, upload_to='accreditations/certificates/', verbose_name='Сертификат')),
                ('organization_logo', models.ImageField(blank=True, upload_to='accreditations/logos/', verbose_name='Логотип организации')),
                ('issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('certificate_number', models.CharField(blank=True, max_length=100, verbose_name='Номер сертификата')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Аккредитация',
                'verbose_name_plural': 'Аккредитации',
                'ordering': ['order', '-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='DownloadableDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Название документа (русский)')),
                ('title_kg', models.CharField(max_length=255, verbose_name='Название документа (кыргызский)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Название документа (английский)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (русский)')),
                ('description_kg', models.TextField(blank=True, verbose_name='Описание (кыргызский)')),
                ('description_en', models.TextField(blank=True, verbose_name='Описание (английский)')),
                ('file', models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])], verbose_name='Файл документа')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер файла (байты)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Документ для скачивания',
                'verbose_name_plural': 'Документы для скачивания',
                'ordering': ['title_ru'],
            },
        ),
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('name_kg', models.CharField(blank=True, max_length=200, verbose_name='ФИО (KG)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='ФИО (EN)')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('position_kg', models.CharField(blank=True, max_length=200, verbose_name='Должность (KG)')),
                ('position_en', models.CharField(blank=True, max_length=200, verbose_name='Должность (EN)')),
                ('degree', models.CharField(max_length=200, verbose_name='Ученая степень')),
                ('degree_kg', models.CharField(blank=True, max_length=200, verbose_name='Ученая степень (KG)')),
                ('degree_en', models.CharField(blank=True, max_length=200, verbose_name='Ученая степень (EN)')),
                ('experience', models.CharField(max_length=100, verbose_name='Опыт работы')),
                ('experience_kg', models.CharField(blank=True, max_length=100, verbose_name='Опыт работы (KG)')),
                ('experience_en', models.CharField(blank=True, max_length=100, verbose_name='Опыт работы (EN)')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('bio_kg', models.TextField(blank=True, verbose_name='Биография (KG)')),
                ('bio_en', models.TextField(blank=True, verbose_name='Биография (EN)')),
                ('achievements', models.JSONField(blank=True, default=list, verbose_name='Достижения')),
                ('achievements_kg', models.JSONField(blank=True, default=list, verbose_name='Достижения (KG)')),
                ('achievements_en', models.JSONField(blank=True, default=list, verbose_name='Достижения (EN)')),
                ('department', models.CharField(blank=True, max_length=50, verbose_name='Департамент(RU)')),
                ('department_kg', models.CharField(blank=True, max_length=200, verbose_name='Департамент (KG)')),
                ('department_en', models.CharField(blank=True, max_length=200, verbose_name='Департамент (EN)')),
                ('specialization', models.TextField(blank=True, verbose_name='Специализация')),
                ('specialization_kg', models.TextField(blank=True, verbose_name='Специализация (KG)')),
                ('specialization_en', models.TextField(blank=True, verbose_name='Специализация (EN)')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('image', models.ImageField(blank=True, upload_to='leadership/photos/', verbose_name='Фото')),
                ('leadership_type', models.CharField(choices=[('director', 'Директор'), ('deputy_director', 'Заместитель директора'), ('department_head', 'Заведующий кафедрой'), ('dean', 'Декан'), ('vice_dean', 'Заместитель декана')], max_length=20, verbose_name='Тип руководства')),
                ('is_director', models.BooleanField(default=False, verbose_name='Является директором')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Руководитель',
                'verbose_name_plural': 'Руководство',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(help_text='Название подразделения на русском языке', max_length=200, verbose_name='Название (Русский)')),
                ('name_en', models.CharField(blank=True, help_text='Department name in English', max_length=200, verbose_name='Name (English)')),
                ('name_ky', models.CharField(blank=True, help_text='Department name in Kyrgyz', max_length=200, verbose_name='Аталышы (Кыргызча)')),
                ('head_name_ru', models.CharField(blank=True, help_text='ФИО руководителя на русском языке', max_length=200, verbose_name='Руководитель (Русский)')),
                ('head_name_en', models.CharField(blank=True, help_text='Head name in English', max_length=200, verbose_name='Head (English)')),
                ('head_name_ky', models.CharField(blank=True, help_text='Head name in Kyrgyz', max_length=200, verbose_name='Башчы (Кыргызча)')),
                ('structure_type', models.CharField(choices=[('leadership', 'Руководство'), ('faculties', 'Факультеты'), ('administrative', 'Административные подразделения'), ('support', 'Вспомогательные подразделения')], help_text='Категория организационной структуры', max_length=20, verbose_name='Тип подразделения')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('icon', models.CharField(default='🏢', help_text='Emoji иконка для отображения', max_length=10, verbose_name='Иконка')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать подразделение на сайте', verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='about_section.organizationstructure', verbose_name='Родительское подразделение')),
            ],
            options={
                'verbose_name': 'Организационная структура',
                'verbose_name_plural': 'Организационная структура',
                'ordering': ['structure_type', 'order', 'name_ru'],
            },
        ),
    ]
