# Generated by Django 5.1.2 on 2025-10-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=500, verbose_name="Title (Russian)"),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Title (English)"
                    ),
                ),
                (
                    "title_kg",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Title (Kyrgyz)"
                    ),
                ),
                (
                    "authors_ru",
                    models.CharField(max_length=500, verbose_name="Authors (Russian)"),
                ),
                (
                    "authors_en",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Authors (English)"
                    ),
                ),
                (
                    "authors_kg",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Authors (Kyrgyz)"
                    ),
                ),
                (
                    "journal",
                    models.CharField(max_length=255, verbose_name="Journal/Conference"),
                ),
                ("year", models.IntegerField(verbose_name="Publication Year")),
                (
                    "citation_count",
                    models.IntegerField(default=0, verbose_name="Citation Count"),
                ),
                (
                    "impact_factor",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Impact Factor"
                    ),
                ),
                ("abstract_ru", models.TextField(verbose_name="Abstract (Russian)")),
                (
                    "abstract_en",
                    models.TextField(blank=True, verbose_name="Abstract (English)"),
                ),
                (
                    "abstract_kg",
                    models.TextField(blank=True, verbose_name="Abstract (Kyrgyz)"),
                ),
                (
                    "doi",
                    models.CharField(blank=True, max_length=100, verbose_name="DOI"),
                ),
                ("url", models.URLField(blank=True, verbose_name="External URL")),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, upload_to="publications/", verbose_name="PDF File"
                    ),
                ),
                (
                    "publication_type",
                    models.CharField(
                        choices=[
                            ("article", "Journal Article"),
                            ("conference", "Conference Paper"),
                            ("book", "Book/Chapter"),
                            ("patent", "Patent"),
                        ],
                        default="article",
                        max_length=50,
                        verbose_name="Publication Type",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Featured"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("order", models.IntegerField(default=0, verbose_name="Order")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Publication",
                "verbose_name_plural": "Publications",
                "ordering": ["-year", "-order", "title_ru"],
            },
        ),
        migrations.CreateModel(
            name="PublicationStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label_ru",
                    models.CharField(max_length=255, verbose_name="Label (Russian)"),
                ),
                (
                    "label_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Label (English)"
                    ),
                ),
                (
                    "label_kg",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Label (Kyrgyz)"
                    ),
                ),
                ("value", models.IntegerField(verbose_name="Value")),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Icon Class"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Order")),
            ],
            options={
                "verbose_name": "Publication Statistic",
                "verbose_name_plural": "Publication Statistics",
                "ordering": ["order"],
            },
        ),
    ]
