# Generated by Django 5.1.2 on 2025-10-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("science", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publication",
            name="authors_en",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="authors_kg",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="authors_ru",
        ),
        migrations.AddField(
            model_name="publication",
            name="author_en",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="Author (English)"
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="author_kg",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="Author (Kyrgyz)"
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="author_ru",
            field=models.CharField(
                default="", max_length=500, verbose_name="Author (Russian)"
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="publications/images/",
                verbose_name="Publication Cover Image",
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="publication_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Publication Date"
            ),
        ),
    ]
