# Generated by Django 5.1.2 on 2025-10-12 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("science", "0002_remove_publication_authors_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VestnikStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label_ru",
                    models.CharField(max_length=255, verbose_name="Label (Russian)"),
                ),
                (
                    "label_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Label (English)"
                    ),
                ),
                (
                    "label_kg",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Label (Kyrgyz)"
                    ),
                ),
                ("value", models.IntegerField(verbose_name="Value")),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Icon Class"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Order")),
            ],
            options={
                "verbose_name": "Vestnik Statistic",
                "verbose_name_plural": "Vestnik Statistics",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="VestnikIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=500, verbose_name="Title (Russian)"),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Title (English)"
                    ),
                ),
                (
                    "title_kg",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Title (Kyrgyz)"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(verbose_name="Description (Russian)"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Description (English)"),
                ),
                (
                    "description_kg",
                    models.TextField(blank=True, verbose_name="Description (Kyrgyz)"),
                ),
                ("volume_number", models.IntegerField(verbose_name="Volume Number")),
                ("issue_number", models.IntegerField(verbose_name="Issue Number")),
                ("year", models.IntegerField(verbose_name="Year")),
                ("publication_date", models.DateField(verbose_name="Publication Date")),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="vestnik/covers/",
                        verbose_name="Cover Image",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, upload_to="vestnik/issues/", verbose_name="PDF File"
                    ),
                ),
                (
                    "issn_print",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="ISSN (Print)"
                    ),
                ),
                (
                    "issn_online",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="ISSN (Online)"
                    ),
                ),
                (
                    "doi_prefix",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="DOI Prefix"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Featured"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Published"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Order")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Vestnik Issue",
                "verbose_name_plural": "Vestnik Issues",
                "ordering": ["-year", "-volume_number", "-issue_number", "order"],
                "unique_together": {("volume_number", "issue_number", "year")},
            },
        ),
        migrations.CreateModel(
            name="VestnikArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=500, verbose_name="Title (Russian)"),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Title (English)"
                    ),
                ),
                (
                    "title_kg",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Title (Kyrgyz)"
                    ),
                ),
                (
                    "author_ru",
                    models.CharField(max_length=500, verbose_name="Authors (Russian)"),
                ),
                (
                    "author_en",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Authors (English)"
                    ),
                ),
                (
                    "author_kg",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Authors (Kyrgyz)"
                    ),
                ),
                ("abstract_ru", models.TextField(verbose_name="Abstract (Russian)")),
                (
                    "abstract_en",
                    models.TextField(blank=True, verbose_name="Abstract (English)"),
                ),
                (
                    "abstract_kg",
                    models.TextField(blank=True, verbose_name="Abstract (Kyrgyz)"),
                ),
                (
                    "keywords_ru",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated keywords",
                        verbose_name="Keywords (Russian)",
                    ),
                ),
                (
                    "keywords_en",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated keywords",
                        verbose_name="Keywords (English)",
                    ),
                ),
                (
                    "keywords_kg",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated keywords",
                        verbose_name="Keywords (Kyrgyz)",
                    ),
                ),
                ("pages_from", models.IntegerField(verbose_name="Page From")),
                ("pages_to", models.IntegerField(verbose_name="Page To")),
                (
                    "doi",
                    models.CharField(blank=True, max_length=100, verbose_name="DOI"),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        upload_to="vestnik/articles/",
                        verbose_name="Article PDF",
                    ),
                ),
                (
                    "article_type",
                    models.CharField(
                        choices=[
                            ("research", "Research Article"),
                            ("review", "Review Article"),
                            ("case_study", "Case Study"),
                            ("editorial", "Editorial"),
                            ("letter", "Letter to Editor"),
                        ],
                        default="research",
                        max_length=50,
                        verbose_name="Article Type",
                    ),
                ),
                (
                    "citation_count",
                    models.IntegerField(default=0, verbose_name="Citation Count"),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Order in Issue"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="science.vestnikissue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vestnik Article",
                "verbose_name_plural": "Vestnik Articles",
                "ordering": ["issue", "order", "pages_from"],
            },
        ),
    ]
