# Generated by Django 5.1.2 on 2025-10-12 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("science", "0003_vestnikstats_vestnikissue_vestnikarticle"),
    ]

    operations = [
        migrations.CreateModel(
            name="NTSCommitteeRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=100, verbose_name="Name (Russian)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Name (English)"
                    ),
                ),
                (
                    "name_kg",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Name (Kyrgyz)"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(blank=True, verbose_name="Description (Russian)"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Description (English)"),
                ),
                (
                    "description_kg",
                    models.TextField(blank=True, verbose_name="Description (Kyrgyz)"),
                ),
            ],
            options={
                "verbose_name": "NTS Committee Role",
                "verbose_name_plural": "NTS Committee Roles",
            },
        ),
        migrations.CreateModel(
            name="NTSResearchDirection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=200, verbose_name="Name (Russian)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Name (English)"
                    ),
                ),
                (
                    "name_kg",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Name (Kyrgyz)"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(blank=True, verbose_name="Description (Russian)"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Description (English)"),
                ),
                (
                    "description_kg",
                    models.TextField(blank=True, verbose_name="Description (Kyrgyz)"),
                ),
            ],
            options={
                "verbose_name": "NTS Research Direction",
                "verbose_name_plural": "NTS Research Directions",
            },
        ),
        migrations.CreateModel(
            name="ScopusDocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=100, verbose_name="Name (Russian)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Name (English)"
                    ),
                ),
                (
                    "name_kg",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Name (Kyrgyz)"
                    ),
                ),
                ("count", models.PositiveIntegerField(verbose_name="Document Count")),
                ("percentage", models.FloatField(verbose_name="Percentage of Total")),
                (
                    "color",
                    models.CharField(
                        default="#4C9BE8", max_length=20, verbose_name="Chart Color"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
            ],
            options={
                "verbose_name": "Scopus Document Type",
                "verbose_name_plural": "Scopus Document Types",
                "ordering": ["-count"],
            },
        ),
        migrations.CreateModel(
            name="ScopusMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=50, verbose_name="Value")),
                (
                    "label_ru",
                    models.CharField(max_length=100, verbose_name="Label (Russian)"),
                ),
                (
                    "label_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Label (English)"
                    ),
                ),
                (
                    "label_kg",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Label (Kyrgyz)"
                    ),
                ),
                (
                    "icon",
                    models.CharField(default="📊", max_length=20, verbose_name="Icon"),
                ),
                (
                    "description_ru",
                    models.CharField(
                        max_length=255, verbose_name="Description (Russian)"
                    ),
                ),
                (
                    "description_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Description (English)"
                    ),
                ),
                (
                    "description_kg",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Description (Kyrgyz)"
                    ),
                ),
                (
                    "trend",
                    models.CharField(
                        default="stable", max_length=20, verbose_name="Trend"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
            ],
            options={
                "verbose_name": "Scopus Metric",
                "verbose_name_plural": "Scopus Metrics",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ScopusPublication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Title")),
                ("authors", models.CharField(max_length=500, verbose_name="Authors")),
                (
                    "journal",
                    models.CharField(max_length=255, verbose_name="Journal/Conference"),
                ),
                ("year", models.IntegerField(verbose_name="Publication Year")),
                (
                    "citation_count",
                    models.IntegerField(default=0, verbose_name="Citation Count"),
                ),
                (
                    "document_type",
                    models.CharField(max_length=100, verbose_name="Document Type"),
                ),
                (
                    "subject_area",
                    models.CharField(max_length=100, verbose_name="Subject Area"),
                ),
                ("url", models.URLField(blank=True, verbose_name="URL")),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Is Featured"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
            ],
            options={
                "verbose_name": "Scopus Publication",
                "verbose_name_plural": "Scopus Publications",
                "ordering": ["-year", "order", "-citation_count"],
            },
        ),
        migrations.CreateModel(
            name="ScopusStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=50, verbose_name="Value")),
                (
                    "label_ru",
                    models.CharField(max_length=100, verbose_name="Label (Russian)"),
                ),
                (
                    "label_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Label (English)"
                    ),
                ),
                (
                    "label_kg",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Label (Kyrgyz)"
                    ),
                ),
                (
                    "icon",
                    models.CharField(default="📊", max_length=20, verbose_name="Icon"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
            ],
            options={
                "verbose_name": "Scopus Stats Item",
                "verbose_name_plural": "Scopus Stats",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="NTSCommitteeMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=100, verbose_name="Name (Russian)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Name (English)"
                    ),
                ),
                (
                    "name_kg",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Name (Kyrgyz)"
                    ),
                ),
                (
                    "position_ru",
                    models.CharField(max_length=200, verbose_name="Position (Russian)"),
                ),
                (
                    "position_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Position (English)"
                    ),
                ),
                (
                    "position_kg",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Position (Kyrgyz)"
                    ),
                ),
                (
                    "bio_ru",
                    models.TextField(blank=True, verbose_name="Biography (Russian)"),
                ),
                (
                    "bio_en",
                    models.TextField(blank=True, verbose_name="Biography (English)"),
                ),
                (
                    "bio_kg",
                    models.TextField(blank=True, verbose_name="Biography (Kyrgyz)"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=50, verbose_name="Phone"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="nts_committee/", verbose_name="Photo"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="science.ntscommitteerole",
                    ),
                ),
                (
                    "research_direction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="science.ntsresearchdirection",
                    ),
                ),
            ],
            options={
                "verbose_name": "NTS Committee Member",
                "verbose_name_plural": "NTS Committee Members",
                "ordering": ["order", "name_ru"],
            },
        ),
    ]
