# Generated by Django 5.1.2 on 2025-10-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("science", "0004_ntscommitteerole_ntsresearchdirection_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NTSCommitteeSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_key",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Section Key"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=200, verbose_name="Title (Russian)"),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Title (English)"
                    ),
                ),
                (
                    "title_kg",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Title (Kyrgyz)"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(verbose_name="Description (Russian)"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Description (English)"),
                ),
                (
                    "description_kg",
                    models.TextField(blank=True, verbose_name="Description (Kyrgyz)"),
                ),
            ],
            options={
                "verbose_name": "NTS Committee Section",
                "verbose_name_plural": "NTS Committee Sections",
            },
        ),
        migrations.CreateModel(
            name="ScopusSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_key",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Section Key"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=200, verbose_name="Title (Russian)"),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Title (English)"
                    ),
                ),
                (
                    "title_kg",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Title (Kyrgyz)"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(verbose_name="Description (Russian)"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Description (English)"),
                ),
                (
                    "description_kg",
                    models.TextField(blank=True, verbose_name="Description (Kyrgyz)"),
                ),
            ],
            options={
                "verbose_name": "Scopus Section",
                "verbose_name_plural": "Scopus Sections",
            },
        ),
        migrations.RemoveField(
            model_name="scopuspublication",
            name="authors",
        ),
        migrations.RemoveField(
            model_name="scopuspublication",
            name="journal",
        ),
        migrations.RemoveField(
            model_name="scopuspublication",
            name="title",
        ),
        migrations.AddField(
            model_name="scopuspublication",
            name="abstract_en",
            field=models.TextField(
                blank=True, default="", verbose_name="Abstract (English)"
            ),
        ),
        migrations.AddField(
            model_name="scopuspublication",
            name="abstract_kg",
            field=models.TextField(
                blank=True, default="", verbose_name="Abstract (Kyrgyz)"
            ),
        ),
        migrations.AddField(
            model_name="scopuspublication",
            name="abstract_ru",
            field=models.TextField(
                blank=True, default="", verbose_name="Abstract (Russian)"
            ),
        ),
        migrations.AddField(
            model_name="scopuspublication",
            name="authors_en",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="Authors (English)"
            ),
        ),
        migrations.AddField(
            model_name="scopuspublication",
            name="authors_kg",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="Authors (Kyrgyz)"
            ),
        ),
        migrations.AddField(
            model_name="scopuspublication",
            name="authors_ru",
            field=models.CharField(
                default="", max_length=500, verbose_name="Authors (Russian)"
            ),
        ),
        migrations.AddField(
            model_name="scopuspublication",
            name="doi",
            field=models.CharField(blank=True, max_length=100, verbose_name="DOI"),
        ),
        migrations.AddField(
            model_name="scopuspublication",
            name="journal_en",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Journal/Conference (English)",
            ),
        ),
        migrations.AddField(
            model_name="scopuspublication",
            name="journal_kg",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Journal/Conference (Kyrgyz)",
            ),
        ),
        migrations.AddField(
            model_name="scopuspublication",
            name="journal_ru",
            field=models.CharField(
                default="", max_length=255, verbose_name="Journal/Conference (Russian)"
            ),
        ),
        migrations.AddField(
            model_name="scopuspublication",
            name="title_en",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="Title (English)"
            ),
        ),
        migrations.AddField(
            model_name="scopuspublication",
            name="title_kg",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="Title (Kyrgyz)"
            ),
        ),
        migrations.AddField(
            model_name="scopuspublication",
            name="title_ru",
            field=models.CharField(
                default="", max_length=500, verbose_name="Title (Russian)"
            ),
        ),
    ]
