# Generated by Django 5.2.7 on 2025-10-13 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("science", "0005_ntscommitteesection_scopussection_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConferenceNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        max_length=500, verbose_name="Conference Title (Russian)"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="Conference Title (English)",
                    ),
                ),
                (
                    "title_kg",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="Conference Title (Kyrgyz)",
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(verbose_name="Description (Russian)"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Description (English)"),
                ),
                (
                    "description_kg",
                    models.TextField(blank=True, verbose_name="Description (Kyrgyz)"),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                ("end_date", models.DateField(verbose_name="End Date")),
                (
                    "registration_deadline",
                    models.DateField(verbose_name="Registration Deadline"),
                ),
                ("location", models.CharField(max_length=255, verbose_name="Location")),
                (
                    "organizer",
                    models.CharField(max_length=255, verbose_name="Organizer"),
                ),
                (
                    "website",
                    models.URLField(blank=True, verbose_name="Conference Website"),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        upload_to="conferences/",
                        verbose_name="Information File",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Contact Email"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Contact Phone"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={
                "verbose_name": "Conference Notice",
                "verbose_name_plural": "Conference Notices",
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="DissertationCouncil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=255, verbose_name="Name (Russian)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Name (English)"
                    ),
                ),
                (
                    "name_kg",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Name (Kyrgyz)"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(verbose_name="Description (Russian)"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Description (English)"),
                ),
                (
                    "description_kg",
                    models.TextField(blank=True, verbose_name="Description (Kyrgyz)"),
                ),
                (
                    "order_number",
                    models.CharField(max_length=50, verbose_name="Order Number"),
                ),
                ("from_date", models.DateField(verbose_name="Active From")),
                ("to_date", models.DateField(verbose_name="Active To")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={
                "verbose_name": "Dissertation Council",
                "verbose_name_plural": "Dissertation Councils",
            },
        ),
        migrations.CreateModel(
            name="DissertationSecretary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=255, verbose_name="Full Name (Russian)"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Full Name (English)"
                    ),
                ),
                (
                    "name_kg",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Full Name (Kyrgyz)"
                    ),
                ),
                (
                    "position_ru",
                    models.CharField(max_length=255, verbose_name="Position (Russian)"),
                ),
                (
                    "position_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Position (English)"
                    ),
                ),
                (
                    "position_kg",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Position (Kyrgyz)"
                    ),
                ),
                ("bio_ru", models.TextField(verbose_name="Bio (Russian)")),
                ("bio_en", models.TextField(blank=True, verbose_name="Bio (English)")),
                ("bio_kg", models.TextField(blank=True, verbose_name="Bio (Kyrgyz)")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Phone"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="dissertation/secretary/",
                        verbose_name="Photo",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={
                "verbose_name": "Dissertation Secretary",
                "verbose_name_plural": "Dissertation Secretaries",
            },
        ),
        migrations.CreateModel(
            name="DissertationSpecialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, verbose_name="Specialization Code"),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=255, verbose_name="Name (Russian)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Name (English)"
                    ),
                ),
                (
                    "name_kg",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Name (Kyrgyz)"
                    ),
                ),
                (
                    "degree_ru",
                    models.CharField(max_length=100, verbose_name="Degree (Russian)"),
                ),
                (
                    "degree_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Degree (English)"
                    ),
                ),
                (
                    "degree_kg",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Degree (Kyrgyz)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Dissertation Specialization",
                "verbose_name_plural": "Dissertation Specializations",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ScientificDirection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=255, verbose_name="Name (Russian)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Name (English)"
                    ),
                ),
                (
                    "name_kg",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Name (Kyrgyz)"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(verbose_name="Description (Russian)"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Description (English)"),
                ),
                (
                    "description_kg",
                    models.TextField(blank=True, verbose_name="Description (Kyrgyz)"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("order", models.IntegerField(default=0, verbose_name="Order")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Scientific Direction",
                "verbose_name_plural": "Scientific Directions",
                "ordering": ["order", "name_ru"],
            },
        ),
        migrations.CreateModel(
            name="ScopusAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scopus_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Scopus ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="First Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Last Name"
                    ),
                ),
                ("h_index", models.IntegerField(default=0, verbose_name="H-index")),
            ],
            options={
                "verbose_name": "Scopus Author",
                "verbose_name_plural": "Scopus Authors",
            },
        ),
        migrations.CreateModel(
            name="ScopusJournal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scopus_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Scopus ID"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "publisher",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Publisher"
                    ),
                ),
                (
                    "issn",
                    models.CharField(blank=True, max_length=50, verbose_name="ISSN"),
                ),
                (
                    "eissn",
                    models.CharField(blank=True, max_length=50, verbose_name="E-ISSN"),
                ),
                (
                    "source_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Source ID"
                    ),
                ),
                (
                    "cite_score",
                    models.FloatField(blank=True, null=True, verbose_name="CiteScore"),
                ),
                ("sjr", models.FloatField(blank=True, null=True, verbose_name="SJR")),
                ("snip", models.FloatField(blank=True, null=True, verbose_name="SNIP")),
            ],
            options={
                "verbose_name": "Scopus Journal",
                "verbose_name_plural": "Scopus Journals",
            },
        ),
        migrations.CreateModel(
            name="ScopusPublisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scopus_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Scopus ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Scopus Publisher",
                "verbose_name_plural": "Scopus Publishers",
            },
        ),
        migrations.CreateModel(
            name="Vestnik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        max_length=255, verbose_name="Journal Title (Russian)"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Journal Title (English)",
                    ),
                ),
                (
                    "title_kg",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Journal Title (Kyrgyz)",
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(verbose_name="Description (Russian)"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Description (English)"),
                ),
                (
                    "description_kg",
                    models.TextField(blank=True, verbose_name="Description (Kyrgyz)"),
                ),
                ("issn", models.CharField(max_length=20, verbose_name="ISSN")),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="vestnik/", verbose_name="Journal Logo"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={
                "verbose_name": "Vestnik Journal",
                "verbose_name_plural": "Vestnik Journals",
            },
        ),
        migrations.CreateModel(
            name="DissertationCouncilAdminStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=255, verbose_name="Full Name (Russian)"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Full Name (English)"
                    ),
                ),
                (
                    "name_kg",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Full Name (Kyrgyz)"
                    ),
                ),
                (
                    "position_ru",
                    models.CharField(max_length=255, verbose_name="Position (Russian)"),
                ),
                (
                    "position_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Position (English)"
                    ),
                ),
                (
                    "position_kg",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Position (Kyrgyz)"
                    ),
                ),
                ("bio_ru", models.TextField(blank=True, verbose_name="Bio (Russian)")),
                ("bio_en", models.TextField(blank=True, verbose_name="Bio (English)")),
                ("bio_kg", models.TextField(blank=True, verbose_name="Bio (Kyrgyz)")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Phone"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="dissertation/staff/",
                        verbose_name="Photo",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "council",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_staff",
                        to="science.dissertationcouncil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Council Admin Staff",
                "verbose_name_plural": "Council Admin Staff",
            },
        ),
        migrations.CreateModel(
            name="DissertationCouncilDocuments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=255, verbose_name="Document Name (Russian)"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Document Name (English)",
                    ),
                ),
                (
                    "name_kg",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Document Name (Kyrgyz)",
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(blank=True, verbose_name="Description (Russian)"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Description (English)"),
                ),
                (
                    "description_kg",
                    models.TextField(blank=True, verbose_name="Description (Kyrgyz)"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="dissertation/documents/",
                        verbose_name="Document File",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "council",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="science.dissertationcouncil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dissertation Council Document",
                "verbose_name_plural": "Dissertation Council Documents",
            },
        ),
        migrations.AddField(
            model_name="dissertationcouncil",
            name="secretary",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="councils",
                to="science.dissertationsecretary",
            ),
        ),
        migrations.CreateModel(
            name="DissertationDefense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        max_length=500, verbose_name="Dissertation Title (Russian)"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="Dissertation Title (English)",
                    ),
                ),
                (
                    "title_kg",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="Dissertation Title (Kyrgyz)",
                    ),
                ),
                (
                    "applicant_ru",
                    models.CharField(
                        max_length=255, verbose_name="Applicant Name (Russian)"
                    ),
                ),
                (
                    "applicant_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Applicant Name (English)",
                    ),
                ),
                (
                    "applicant_kg",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Applicant Name (Kyrgyz)",
                    ),
                ),
                ("abstract_ru", models.TextField(verbose_name="Abstract (Russian)")),
                (
                    "abstract_en",
                    models.TextField(blank=True, verbose_name="Abstract (English)"),
                ),
                (
                    "abstract_kg",
                    models.TextField(blank=True, verbose_name="Abstract (Kyrgyz)"),
                ),
                (
                    "defense_date",
                    models.DateTimeField(verbose_name="Defense Date and Time"),
                ),
                (
                    "dissertation_file",
                    models.FileField(
                        blank=True,
                        upload_to="dissertation/files/",
                        verbose_name="Dissertation File",
                    ),
                ),
                (
                    "abstract_file",
                    models.FileField(
                        blank=True,
                        upload_to="dissertation/abstracts/",
                        verbose_name="Abstract File",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "council",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="defenses",
                        to="science.dissertationcouncil",
                    ),
                ),
                (
                    "specializations",
                    models.ManyToManyField(
                        related_name="defenses", to="science.dissertationspecialization"
                    ),
                ),
            ],
            options={
                "verbose_name": "Dissertation Defense",
                "verbose_name_plural": "Dissertation Defenses",
                "ordering": ["-defense_date"],
            },
        ),
        migrations.AddField(
            model_name="dissertationcouncil",
            name="specializations",
            field=models.ManyToManyField(
                related_name="councils", to="science.dissertationspecialization"
            ),
        ),
        migrations.CreateModel(
            name="ScopusPublicationAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seq", models.IntegerField(default=0, verbose_name="Sequence")),
                (
                    "is_corresponding",
                    models.BooleanField(default=False, verbose_name="Is Corresponding"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="science.scopusauthor",
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publication_authors",
                        to="science.scopuspublication",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scopus Publication Author",
                "verbose_name_plural": "Scopus Publication Authors",
                "ordering": ["seq"],
            },
        ),
    ]
