# Generated by Django 5.2.7 on 2025-10-14 11:20

import django.db.models.deletion
from django.db import migrations, models


def create_and_map_document_types(apps, schema_editor):
    ScopusDocumentType = apps.get_model("science", "ScopusDocumentType")
    connection = schema_editor.connection

    # common types to ensure exist
    common = ["Article", "Review", "Conference Paper", "Book", "Patent"]
    type_map = {}
    for label in common:
        obj, _ = ScopusDocumentType.objects.get_or_create(
            code=label,
            defaults={
                "label_ru": label,
                "label_en": label,
                "label_kg": "",
            },
        )
        type_map[label] = obj.pk

    # Map existing publication.document_type values (raw column) to FK ids
    with connection.cursor() as cursor:
        cursor.execute("SELECT id, document_type FROM science_scopuspublication")
        rows = cursor.fetchall()
        for pub_id, docval in rows:
            if docval is None:
                continue
            # if numeric already, skip
            try:
                int(docval)
                continue
            except Exception:
                pass
            doc_type_id = None
            if docval in type_map:
                doc_type_id = type_map[docval]
            else:
                # try to find by code or label
                row = ScopusDocumentType.objects.filter(code=docval).first()
                if row:
                    doc_type_id = row.pk
                else:
                    row = ScopusDocumentType.objects.filter(label_ru=docval).first()
                    if row:
                        doc_type_id = row.pk
            if doc_type_id:
                # SQLite's debug_sql may attempt to format query+params using % which
                # can raise TypeError when params are not all strings. Ensure we
                # pass an int and use a simple parameterized execute which is safe.
                try:
                    doc_type_int = int(doc_type_id)
                except Exception:
                    # fallback: skip mapping this row
                    continue
                cursor.execute(
                    "UPDATE science_scopuspublication SET document_type = ? WHERE id = ?",
                    (doc_type_int, pub_id),
                )


class Migration(migrations.Migration):

    dependencies = [
        ("science", "0006_conferencenotice_dissertationcouncil_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ntscommitteemember",
            options={
                "ordering": ["order", "full_name_ru"],
                "verbose_name": "NTS Committee Member",
                "verbose_name_plural": "NTS Committee Members",
            },
        ),
        migrations.AlterModelOptions(
            name="ntscommitteerole",
            options={
                "ordering": ["order", "name_ru"],
                "verbose_name": "NTS Committee Role",
                "verbose_name_plural": "NTS Committee Roles",
            },
        ),
        migrations.AlterModelOptions(
            name="ntscommitteesection",
            options={
                "ordering": ["order", "title_ru"],
                "verbose_name": "NTS Committee Section",
                "verbose_name_plural": "NTS Committee Sections",
            },
        ),
        migrations.AlterModelOptions(
            name="ntsresearchdirection",
            options={
                "ordering": ["order", "name_ru"],
                "verbose_name": "NTS Research Direction",
                "verbose_name_plural": "NTS Research Directions",
            },
        ),
        migrations.AlterModelOptions(
            name="scopusdocumenttype",
            options={
                "verbose_name": "Scopus Document Type",
                "verbose_name_plural": "Scopus Document Types",
            },
        ),
        migrations.AlterModelOptions(
            name="scopusmetrics",
            options={
                "verbose_name": "Scopus Metrics",
                "verbose_name_plural": "Scopus Metrics",
            },
        ),
        migrations.AlterModelOptions(
            name="scopuspublication",
            options={
                "verbose_name": "Scopus Publication",
                "verbose_name_plural": "Scopus Publications",
            },
        ),
        migrations.AlterModelOptions(
            name="scopuspublicationauthor",
            options={
                "ordering": ["author_position"],
                "verbose_name": "Scopus Publication Author",
                "verbose_name_plural": "Scopus Publication Authors",
            },
        ),
        migrations.AlterModelOptions(
            name="scopussection",
            options={
                "ordering": ["order"],
                "verbose_name": "Scopus Section",
                "verbose_name_plural": "Scopus Sections",
            },
        ),
        migrations.AlterModelOptions(
            name="scopusstats",
            options={
                "ordering": ["order"],
                "verbose_name": "Scopus Statistic",
                "verbose_name_plural": "Scopus Statistics",
            },
        ),
        migrations.RemoveField(
            model_name="ntscommitteemember",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="ntscommitteemember",
            name="name_kg",
        ),
        migrations.RemoveField(
            model_name="ntscommitteemember",
            name="name_ru",
        ),
        migrations.RemoveField(
            model_name="ntscommitteemember",
            name="position_en",
        ),
        migrations.RemoveField(
            model_name="ntscommitteemember",
            name="position_kg",
        ),
        migrations.RemoveField(
            model_name="ntscommitteemember",
            name="position_ru",
        ),
        migrations.RemoveField(
            model_name="ntscommitteemember",
            name="research_direction",
        ),
        migrations.RemoveField(
            model_name="ntscommitteerole",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="ntscommitteerole",
            name="description_kg",
        ),
        migrations.RemoveField(
            model_name="ntscommitteerole",
            name="description_ru",
        ),
        migrations.RemoveField(
            model_name="ntscommitteesection",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="ntscommitteesection",
            name="description_kg",
        ),
        migrations.RemoveField(
            model_name="ntscommitteesection",
            name="description_ru",
        ),
        migrations.RemoveField(
            model_name="ntscommitteesection",
            name="section_key",
        ),
        migrations.RemoveField(
            model_name="ntsresearchdirection",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="ntsresearchdirection",
            name="description_kg",
        ),
        migrations.RemoveField(
            model_name="ntsresearchdirection",
            name="description_ru",
        ),
        migrations.RemoveField(
            model_name="scopusauthor",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="scopusauthor",
            name="h_index",
        ),
        migrations.RemoveField(
            model_name="scopusauthor",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="scopusauthor",
            name="name",
        ),
        migrations.RemoveField(
            model_name="scopusdocumenttype",
            name="color",
        ),
        migrations.RemoveField(
            model_name="scopusdocumenttype",
            name="count",
        ),
        migrations.RemoveField(
            model_name="scopusdocumenttype",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="scopusdocumenttype",
            name="name_kg",
        ),
        migrations.RemoveField(
            model_name="scopusdocumenttype",
            name="name_ru",
        ),
        migrations.RemoveField(
            model_name="scopusdocumenttype",
            name="order",
        ),
        migrations.RemoveField(
            model_name="scopusdocumenttype",
            name="percentage",
        ),
        migrations.RemoveField(
            model_name="scopusjournal",
            name="cite_score",
        ),
        migrations.RemoveField(
            model_name="scopusjournal",
            name="eissn",
        ),
        migrations.RemoveField(
            model_name="scopusjournal",
            name="scopus_id",
        ),
        migrations.RemoveField(
            model_name="scopusjournal",
            name="sjr",
        ),
        migrations.RemoveField(
            model_name="scopusjournal",
            name="snip",
        ),
        migrations.RemoveField(
            model_name="scopusjournal",
            name="source_id",
        ),
        migrations.RemoveField(
            model_name="scopusjournal",
            name="title",
        ),
        migrations.RemoveField(
            model_name="scopusmetrics",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="scopusmetrics",
            name="description_kg",
        ),
        migrations.RemoveField(
            model_name="scopusmetrics",
            name="description_ru",
        ),
        migrations.RemoveField(
            model_name="scopusmetrics",
            name="icon",
        ),
        migrations.RemoveField(
            model_name="scopusmetrics",
            name="label_en",
        ),
        migrations.RemoveField(
            model_name="scopusmetrics",
            name="label_kg",
        ),
        migrations.RemoveField(
            model_name="scopusmetrics",
            name="label_ru",
        ),
        migrations.RemoveField(
            model_name="scopusmetrics",
            name="order",
        ),
        migrations.RemoveField(
            model_name="scopusmetrics",
            name="trend",
        ),
        migrations.RemoveField(
            model_name="scopusmetrics",
            name="value",
        ),
        migrations.RemoveField(
            model_name="scopuspublication",
            name="authors_en",
        ),
        migrations.RemoveField(
            model_name="scopuspublication",
            name="authors_kg",
        ),
        migrations.RemoveField(
            model_name="scopuspublication",
            name="authors_ru",
        ),
        migrations.RemoveField(
            model_name="scopuspublication",
            name="citation_count",
        ),
        migrations.RemoveField(
            model_name="scopuspublication",
            name="is_featured",
        ),
        migrations.RemoveField(
            model_name="scopuspublication",
            name="journal_en",
        ),
        migrations.RemoveField(
            model_name="scopuspublication",
            name="journal_kg",
        ),
        migrations.RemoveField(
            model_name="scopuspublication",
            name="journal_ru",
        ),
        migrations.RemoveField(
            model_name="scopuspublication",
            name="order",
        ),
        migrations.RemoveField(
            model_name="scopuspublication",
            name="subject_area",
        ),
        migrations.RemoveField(
            model_name="scopuspublicationauthor",
            name="is_corresponding",
        ),
        migrations.RemoveField(
            model_name="scopuspublicationauthor",
            name="seq",
        ),
        migrations.RemoveField(
            model_name="scopuspublisher",
            name="name",
        ),
        migrations.RemoveField(
            model_name="scopuspublisher",
            name="scopus_id",
        ),
        migrations.RemoveField(
            model_name="scopussection",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="scopussection",
            name="description_kg",
        ),
        migrations.RemoveField(
            model_name="scopussection",
            name="description_ru",
        ),
        migrations.RemoveField(
            model_name="scopussection",
            name="section_key",
        ),
        migrations.RemoveField(
            model_name="scopusstats",
            name="icon",
        ),
        migrations.AddField(
            model_name="ntscommitteemember",
            name="full_name_en",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Full Name (English)",
            ),
        ),
        migrations.AddField(
            model_name="ntscommitteemember",
            name="full_name_kg",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Full Name (Kyrgyz)",
            ),
        ),
        migrations.AddField(
            model_name="ntscommitteemember",
            name="full_name_ru",
            field=models.CharField(
                default="", max_length=255, verbose_name="Full Name (Russian)"
            ),
        ),
        migrations.AddField(
            model_name="ntscommitteemember",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="science.ntscommitteesection",
            ),
        ),
        migrations.AddField(
            model_name="ntscommitteerole",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ntscommitteesection",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ntscommitteesection",
            name="research_direction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="science.ntsresearchdirection",
            ),
        ),
        migrations.AddField(
            model_name="ntsresearchdirection",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="ntsresearchdirection",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scopusauthor",
            name="family_name_en",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Family Name (English)",
            ),
        ),
        migrations.AddField(
            model_name="scopusauthor",
            name="family_name_kg",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Family Name (Kyrgyz)",
            ),
        ),
        migrations.AddField(
            model_name="scopusauthor",
            name="family_name_ru",
            field=models.CharField(
                default="", max_length=255, verbose_name="Family Name (Russian)"
            ),
        ),
        migrations.AddField(
            model_name="scopusauthor",
            name="given_name_en",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Given Name (English)"
            ),
        ),
        migrations.AddField(
            model_name="scopusauthor",
            name="given_name_kg",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Given Name (Kyrgyz)"
            ),
        ),
        migrations.AddField(
            model_name="scopusauthor",
            name="given_name_ru",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Given Name (Russian)"
            ),
        ),
        migrations.AddField(
            model_name="scopusdocumenttype",
            name="code",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="scopusdocumenttype",
            name="label_en",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Label (English)"
            ),
        ),
        migrations.AddField(
            model_name="scopusdocumenttype",
            name="label_kg",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Label (Kyrgyz)"
            ),
        ),
        migrations.AddField(
            model_name="scopusdocumenttype",
            name="label_ru",
            field=models.CharField(
                default="", max_length=255, verbose_name="Label (Russian)"
            ),
        ),
        migrations.AddField(
            model_name="scopusjournal",
            name="title_en",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="Title (English)"
            ),
        ),
        migrations.AddField(
            model_name="scopusjournal",
            name="title_kg",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="Title (Kyrgyz)"
            ),
        ),
        migrations.AddField(
            model_name="scopusjournal",
            name="title_ru",
            field=models.CharField(
                default="", max_length=500, verbose_name="Title (Russian)"
            ),
        ),
        migrations.AddField(
            model_name="scopusmetrics",
            name="citation_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scopusmetrics",
            name="h_index",
            field=models.IntegerField(blank=True, null=True),
        ),
        # Create document types for existing string values and map publication.document_type -> id
        migrations.RunPython(
            code=create_and_map_document_types, reverse_code=migrations.RunPython.noop
        ),
        migrations.AddField(
            model_name="scopusmetrics",
            name="publication",
            field=models.OneToOneField(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metrics",
                to="science.scopuspublication",
            ),
        ),
        migrations.AddField(
            model_name="scopuspublication",
            name="journal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="science.scopusjournal",
            ),
        ),
        migrations.AddField(
            model_name="scopuspublicationauthor",
            name="author_position",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scopuspublisher",
            name="country",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="scopuspublisher",
            name="name_en",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Name (English)"
            ),
        ),
        migrations.AddField(
            model_name="scopuspublisher",
            name="name_kg",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Name (Kyrgyz)"
            ),
        ),
        migrations.AddField(
            model_name="scopuspublisher",
            name="name_ru",
            field=models.CharField(
                default="", max_length=255, verbose_name="Name (Russian)"
            ),
        ),
        migrations.AddField(
            model_name="scopussection",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="dissertationspecialization",
            name="code",
            field=models.CharField(
                default="", max_length=20, verbose_name="Specialization Code"
            ),
        ),
        migrations.AlterField(
            model_name="dissertationspecialization",
            name="name_en",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Name (English)"
            ),
        ),
        migrations.AlterField(
            model_name="dissertationspecialization",
            name="name_kg",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Name (Kyrgyz)"
            ),
        ),
        migrations.AlterField(
            model_name="dissertationspecialization",
            name="name_ru",
            field=models.CharField(
                default="", max_length=255, verbose_name="Name (Russian)"
            ),
        ),
        migrations.AlterField(
            model_name="ntscommitteemember",
            name="bio_en",
            field=models.TextField(blank=True, verbose_name="Bio (English)"),
        ),
        migrations.AlterField(
            model_name="ntscommitteemember",
            name="bio_kg",
            field=models.TextField(blank=True, verbose_name="Bio (Kyrgyz)"),
        ),
        migrations.AlterField(
            model_name="ntscommitteemember",
            name="bio_ru",
            field=models.TextField(blank=True, verbose_name="Bio (Russian)"),
        ),
        migrations.AlterField(
            model_name="ntscommitteemember",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="ntscommitteemember",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="ntscommitteemember",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="ntscommitteemember",
            name="phone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="ntscommitteemember",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="nts/members/"),
        ),
        migrations.AlterField(
            model_name="ntscommitteemember",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="science.ntscommitteerole",
            ),
        ),
        migrations.AlterField(
            model_name="ntscommitteerole",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Name (English)"
            ),
        ),
        migrations.AlterField(
            model_name="ntscommitteerole",
            name="name_kg",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Name (Kyrgyz)"
            ),
        ),
        migrations.AlterField(
            model_name="ntscommitteerole",
            name="name_ru",
            field=models.CharField(max_length=255, verbose_name="Name (Russian)"),
        ),
        migrations.AlterField(
            model_name="ntscommitteesection",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Title (English)"
            ),
        ),
        migrations.AlterField(
            model_name="ntscommitteesection",
            name="title_kg",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Title (Kyrgyz)"
            ),
        ),
        migrations.AlterField(
            model_name="ntscommitteesection",
            name="title_ru",
            field=models.CharField(max_length=255, verbose_name="Title (Russian)"),
        ),
        migrations.AlterField(
            model_name="ntsresearchdirection",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Name (English)"
            ),
        ),
        migrations.AlterField(
            model_name="ntsresearchdirection",
            name="name_kg",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Name (Kyrgyz)"
            ),
        ),
        migrations.AlterField(
            model_name="ntsresearchdirection",
            name="name_ru",
            field=models.CharField(max_length=255, verbose_name="Name (Russian)"),
        ),
        migrations.AlterField(
            model_name="scopusauthor",
            name="scopus_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="scopusjournal",
            name="issn",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="scopusjournal",
            name="publisher",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="scopuspublication",
            name="abstract_en",
            field=models.TextField(blank=True, verbose_name="Abstract (English)"),
        ),
        migrations.AlterField(
            model_name="scopuspublication",
            name="abstract_kg",
            field=models.TextField(blank=True, verbose_name="Abstract (Kyrgyz)"),
        ),
        migrations.AlterField(
            model_name="scopuspublication",
            name="abstract_ru",
            field=models.TextField(blank=True, verbose_name="Abstract (Russian)"),
        ),
        migrations.AlterField(
            model_name="scopuspublication",
            name="document_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="science.scopusdocumenttype",
            ),
        ),
        migrations.AlterField(
            model_name="scopuspublication",
            name="doi",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="scopuspublication",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=1000, verbose_name="Title (English)"
            ),
        ),
        migrations.AlterField(
            model_name="scopuspublication",
            name="title_kg",
            field=models.CharField(
                blank=True, max_length=1000, verbose_name="Title (Kyrgyz)"
            ),
        ),
        migrations.AlterField(
            model_name="scopuspublication",
            name="title_ru",
            field=models.CharField(max_length=1000, verbose_name="Title (Russian)"),
        ),
        migrations.AlterField(
            model_name="scopuspublication",
            name="url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="scopuspublication",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="scopuspublicationauthor",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publications",
                to="science.scopusauthor",
            ),
        ),
        migrations.AlterField(
            model_name="scopuspublicationauthor",
            name="publication",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authors",
                to="science.scopuspublication",
            ),
        ),
        migrations.AlterField(
            model_name="scopussection",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Title (English)"
            ),
        ),
        migrations.AlterField(
            model_name="scopussection",
            name="title_kg",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Title (Kyrgyz)"
            ),
        ),
        migrations.AlterField(
            model_name="scopussection",
            name="title_ru",
            field=models.CharField(max_length=255, verbose_name="Title (Russian)"),
        ),
        migrations.AlterField(
            model_name="scopusstats",
            name="label_en",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Label (English)"
            ),
        ),
        migrations.AlterField(
            model_name="scopusstats",
            name="label_kg",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Label (Kyrgyz)"
            ),
        ),
        migrations.AlterField(
            model_name="scopusstats",
            name="label_ru",
            field=models.CharField(max_length=255, verbose_name="Label (Russian)"),
        ),
        migrations.AlterField(
            model_name="scopusstats",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="scopusstats",
            name="value",
            field=models.IntegerField(),
        ),
    ]
