# Generated by Django 5.2.7 on 2025-10-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("science", "0008_ntscommitteesection_description_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scopussection",
            name="description_en",
            field=models.TextField(blank=True, verbose_name="Description (English)"),
        ),
        migrations.AddField(
            model_name="scopussection",
            name="description_kg",
            field=models.TextField(blank=True, verbose_name="Description (Kyrgyz)"),
        ),
        migrations.AddField(
            model_name="scopussection",
            name="description_ru",
            field=models.TextField(blank=True, verbose_name="Description (Russian)"),
        ),
        migrations.AddField(
            model_name="scopussection",
            name="section_key",
            field=models.CharField(
                blank=True,
                help_text="Optional stable key for identifying this section (e.g. 'header', 'footer')",
                max_length=100,
                verbose_name="Section Key",
            ),
        ),
    ]
