# Generated by Django 5.2.7 on 2025-10-15 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("science", "0009_scopussection_description_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebOfScienceSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_key",
                    models.CharField(
                        help_text="Unique key for identifying this section (e.g., 'title', 'subtitle', 'titleIcon')",
                        max_length=100,
                        unique=True,
                        verbose_name="Section Key",
                    ),
                ),
                ("text_ru", models.TextField(verbose_name="Text (Russian)")),
                (
                    "text_en",
                    models.TextField(blank=True, verbose_name="Text (English)"),
                ),
                ("text_kg", models.TextField(blank=True, verbose_name="Text (Kyrgyz)")),
                ("order", models.IntegerField(default=0, verbose_name="Order")),
            ],
            options={
                "verbose_name": "Web of Science Section",
                "verbose_name_plural": "Web of Science Sections",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="WebOfScienceTimeRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Unique key for this time range, e.g., '1year', '3years', '5years'",
                        max_length=50,
                        verbose_name="Key",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=100, verbose_name="Title (Russian)"),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Title (English)"
                    ),
                ),
                (
                    "title_kg",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Title (Kyrgyz)"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Order")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Is Default"),
                ),
            ],
            options={
                "verbose_name": "Web of Science Time Range",
                "verbose_name_plural": "Web of Science Time Ranges",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="WebOfScienceJournalQuartile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quartile", models.CharField(max_length=10, verbose_name="Quartile")),
                ("count", models.IntegerField(verbose_name="Publication Count")),
                ("order", models.IntegerField(default=0, verbose_name="Order")),
                (
                    "time_range",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_quartiles",
                        to="science.webofsciencetimerange",
                    ),
                ),
            ],
            options={
                "verbose_name": "Web of Science Journal Quartile",
                "verbose_name_plural": "Web of Science Journal Quartiles",
                "ordering": ["time_range", "order"],
            },
        ),
        migrations.CreateModel(
            name="WebOfScienceCollaboration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country_ru",
                    models.CharField(max_length=100, verbose_name="Country (Russian)"),
                ),
                (
                    "country_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Country (English)"
                    ),
                ),
                (
                    "country_kg",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Country (Kyrgyz)"
                    ),
                ),
                (
                    "flag",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Flag Emoji"
                    ),
                ),
                (
                    "institutions",
                    models.IntegerField(verbose_name="Number of Institutions"),
                ),
                (
                    "publications",
                    models.IntegerField(verbose_name="Number of Publications"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Order")),
                (
                    "time_range",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaborations",
                        to="science.webofsciencetimerange",
                    ),
                ),
            ],
            options={
                "verbose_name": "Web of Science Collaboration",
                "verbose_name_plural": "Web of Science Collaborations",
                "ordering": ["time_range", "order"],
            },
        ),
        migrations.CreateModel(
            name="WebOfScienceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=100, verbose_name="Name (Russian)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Name (English)"
                    ),
                ),
                (
                    "name_kg",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Name (Kyrgyz)"
                    ),
                ),
                ("count", models.IntegerField(verbose_name="Publication Count")),
                ("order", models.IntegerField(default=0, verbose_name="Order")),
                (
                    "time_range",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="science.webofsciencetimerange",
                    ),
                ),
            ],
            options={
                "verbose_name": "Web of Science Category",
                "verbose_name_plural": "Web of Science Categories",
                "ordering": ["time_range", "order"],
            },
        ),
        migrations.CreateModel(
            name="WebOfScienceMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Unique key for this metric, e.g., 'publications', 'citations', 'hindex'",
                        max_length=50,
                        verbose_name="Key",
                    ),
                ),
                ("value", models.CharField(max_length=50, verbose_name="Value")),
                (
                    "label_ru",
                    models.CharField(max_length=100, verbose_name="Label (Russian)"),
                ),
                (
                    "label_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Label (English)"
                    ),
                ),
                (
                    "label_kg",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Label (Kyrgyz)"
                    ),
                ),
                (
                    "description_ru",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Description (Russian)"
                    ),
                ),
                (
                    "description_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Description (English)"
                    ),
                ),
                (
                    "description_kg",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Description (Kyrgyz)"
                    ),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=20, verbose_name="Icon"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Order")),
                (
                    "time_range",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="science.webofsciencetimerange",
                    ),
                ),
            ],
            options={
                "verbose_name": "Web of Science Metric",
                "verbose_name_plural": "Web of Science Metrics",
                "ordering": ["time_range", "order"],
                "unique_together": {("time_range", "key")},
            },
        ),
        migrations.CreateModel(
            name="WebOfScienceAdditionalMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Unique key for this metric, e.g., 'averageCitations', 'hotPapers'",
                        max_length=50,
                        verbose_name="Key",
                    ),
                ),
                ("value", models.CharField(max_length=50, verbose_name="Value")),
                (
                    "title_ru",
                    models.CharField(max_length=100, verbose_name="Title (Russian)"),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Title (English)"
                    ),
                ),
                (
                    "title_kg",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Title (Kyrgyz)"
                    ),
                ),
                (
                    "description_ru",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Description (Russian)"
                    ),
                ),
                (
                    "description_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Description (English)"
                    ),
                ),
                (
                    "description_kg",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Description (Kyrgyz)"
                    ),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=20, verbose_name="Icon"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Order")),
                (
                    "time_range",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_metrics",
                        to="science.webofsciencetimerange",
                    ),
                ),
            ],
            options={
                "verbose_name": "Web of Science Additional Metric",
                "verbose_name_plural": "Web of Science Additional Metrics",
                "ordering": ["time_range", "order"],
                "unique_together": {("time_range", "key")},
            },
        ),
    ]
