# Generated by Django 5.2.7 on 2025-10-15 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("science", "0010_webofsciencesection_webofsciencetimerange_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentScientificSocietyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label_ru",
                    models.CharField(max_length=100, verbose_name="Label (Russian)"),
                ),
                (
                    "label_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Label (English)"
                    ),
                ),
                (
                    "label_kg",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Label (Kyrgyz)"
                    ),
                ),
                ("value", models.CharField(max_length=255, verbose_name="Value")),
                (
                    "icon",
                    models.CharField(
                        help_text="Emoji or icon character",
                        max_length=10,
                        verbose_name="Icon (Emoji)",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Order")),
            ],
            options={
                "verbose_name": "Student Scientific Society Contact",
                "verbose_name_plural": "Student Scientific Society Contacts",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="StudentScientificSocietyEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=255, verbose_name="Name (Russian)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Name (English)"
                    ),
                ),
                (
                    "name_kg",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Name (Kyrgyz)"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(verbose_name="Description (Russian)"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Description (English)"),
                ),
                (
                    "description_kg",
                    models.TextField(blank=True, verbose_name="Description (Kyrgyz)"),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="Emoji or icon character",
                        max_length=10,
                        verbose_name="Icon (Emoji)",
                    ),
                ),
                ("date", models.DateField(verbose_name="Event Date")),
                (
                    "time",
                    models.CharField(
                        help_text="Time in text format (e.g. '14:00-16:00')",
                        max_length=50,
                        verbose_name="Event Time",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("upcoming", "Upcoming"), ("completed", "Completed")],
                        default="upcoming",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Order")),
            ],
            options={
                "verbose_name": "Student Scientific Society Event",
                "verbose_name_plural": "Student Scientific Society Events",
                "ordering": ["date", "order"],
            },
        ),
        migrations.CreateModel(
            name="StudentScientificSocietyFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=255, verbose_name="Title (Russian)"),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Title (English)"
                    ),
                ),
                (
                    "title_kg",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Title (Kyrgyz)"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(verbose_name="Description (Russian)"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Description (English)"),
                ),
                (
                    "description_kg",
                    models.TextField(blank=True, verbose_name="Description (Kyrgyz)"),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="Emoji or icon character",
                        max_length=10,
                        verbose_name="Icon (Emoji)",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Order")),
            ],
            options={
                "verbose_name": "Student Scientific Society Feature",
                "verbose_name_plural": "Student Scientific Society Features",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="StudentScientificSocietyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=255, verbose_name="Title (Russian)"),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Title (English)"
                    ),
                ),
                (
                    "title_kg",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Title (Kyrgyz)"
                    ),
                ),
                ("subtitle_ru", models.TextField(verbose_name="Subtitle (Russian)")),
                (
                    "subtitle_en",
                    models.TextField(blank=True, verbose_name="Subtitle (English)"),
                ),
                (
                    "subtitle_kg",
                    models.TextField(blank=True, verbose_name="Subtitle (Kyrgyz)"),
                ),
                (
                    "about_title_ru",
                    models.CharField(
                        max_length=255, verbose_name="About Title (Russian)"
                    ),
                ),
                (
                    "about_title_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="About Title (English)"
                    ),
                ),
                (
                    "about_title_kg",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="About Title (Kyrgyz)"
                    ),
                ),
                (
                    "about_description_ru",
                    models.TextField(verbose_name="About Description (Russian)"),
                ),
                (
                    "about_description_en",
                    models.TextField(
                        blank=True, verbose_name="About Description (English)"
                    ),
                ),
                (
                    "about_description_kg",
                    models.TextField(
                        blank=True, verbose_name="About Description (Kyrgyz)"
                    ),
                ),
                (
                    "projects_title_ru",
                    models.CharField(
                        max_length=255, verbose_name="Projects Title (Russian)"
                    ),
                ),
                (
                    "projects_title_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Projects Title (English)",
                    ),
                ),
                (
                    "projects_title_kg",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Projects Title (Kyrgyz)",
                    ),
                ),
                (
                    "events_title_ru",
                    models.CharField(
                        max_length=255, verbose_name="Events Title (Russian)"
                    ),
                ),
                (
                    "events_title_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Events Title (English)",
                    ),
                ),
                (
                    "events_title_kg",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Events Title (Kyrgyz)"
                    ),
                ),
                (
                    "join_title_ru",
                    models.CharField(
                        max_length=255, verbose_name="Join Title (Russian)"
                    ),
                ),
                (
                    "join_title_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Join Title (English)"
                    ),
                ),
                (
                    "join_title_kg",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Join Title (Kyrgyz)"
                    ),
                ),
                (
                    "leadership_title_ru",
                    models.CharField(
                        max_length=255, verbose_name="Leadership Title (Russian)"
                    ),
                ),
                (
                    "leadership_title_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Leadership Title (English)",
                    ),
                ),
                (
                    "leadership_title_kg",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Leadership Title (Kyrgyz)",
                    ),
                ),
                (
                    "contacts_title_ru",
                    models.CharField(
                        max_length=255, verbose_name="Contacts Title (Russian)"
                    ),
                ),
                (
                    "contacts_title_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Contacts Title (English)",
                    ),
                ),
                (
                    "contacts_title_kg",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Contacts Title (Kyrgyz)",
                    ),
                ),
                (
                    "upcoming_events_title_ru",
                    models.CharField(
                        max_length=255, verbose_name="Upcoming Events Title (Russian)"
                    ),
                ),
                (
                    "upcoming_events_title_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Upcoming Events Title (English)",
                    ),
                ),
                (
                    "upcoming_events_title_kg",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Upcoming Events Title (Kyrgyz)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Scientific Society Info",
                "verbose_name_plural": "Student Scientific Society Info",
            },
        ),
        migrations.CreateModel(
            name="StudentScientificSocietyJoinStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step", models.IntegerField(verbose_name="Step Number")),
                (
                    "title_ru",
                    models.CharField(max_length=255, verbose_name="Title (Russian)"),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Title (English)"
                    ),
                ),
                (
                    "title_kg",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Title (Kyrgyz)"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(verbose_name="Description (Russian)"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Description (English)"),
                ),
                (
                    "description_kg",
                    models.TextField(blank=True, verbose_name="Description (Kyrgyz)"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Order")),
            ],
            options={
                "verbose_name": "Student Scientific Society Join Step",
                "verbose_name_plural": "Student Scientific Society Join Steps",
                "ordering": ["order", "step"],
            },
        ),
        migrations.CreateModel(
            name="StudentScientificSocietyLeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=255, verbose_name="Name (Russian)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Name (English)"
                    ),
                ),
                (
                    "name_kg",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Name (Kyrgyz)"
                    ),
                ),
                (
                    "position_ru",
                    models.CharField(max_length=255, verbose_name="Position (Russian)"),
                ),
                (
                    "position_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Position (English)"
                    ),
                ),
                (
                    "position_kg",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Position (Kyrgyz)"
                    ),
                ),
                (
                    "department_ru",
                    models.CharField(
                        max_length=255, verbose_name="Department (Russian)"
                    ),
                ),
                (
                    "department_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Department (English)"
                    ),
                ),
                (
                    "department_kg",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Department (Kyrgyz)"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Order")),
            ],
            options={
                "verbose_name": "Student Scientific Society Leader",
                "verbose_name_plural": "Student Scientific Society Leaders",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="StudentScientificSocietyProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=255, verbose_name="Name (Russian)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Name (English)"
                    ),
                ),
                (
                    "name_kg",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Name (Kyrgyz)"
                    ),
                ),
                (
                    "short_description_ru",
                    models.TextField(verbose_name="Short Description (Russian)"),
                ),
                (
                    "short_description_en",
                    models.TextField(
                        blank=True, verbose_name="Short Description (English)"
                    ),
                ),
                (
                    "short_description_kg",
                    models.TextField(
                        blank=True, verbose_name="Short Description (Kyrgyz)"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(verbose_name="Description (Russian)"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Description (English)"),
                ),
                (
                    "description_kg",
                    models.TextField(blank=True, verbose_name="Description (Kyrgyz)"),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="Emoji or icon character",
                        max_length=10,
                        verbose_name="Icon (Emoji)",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Order")),
            ],
            options={
                "verbose_name": "Student Scientific Society Project",
                "verbose_name_plural": "Student Scientific Society Projects",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="StudentScientificSocietyStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label_ru",
                    models.CharField(max_length=100, verbose_name="Label (Russian)"),
                ),
                (
                    "label_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Label (English)"
                    ),
                ),
                (
                    "label_kg",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Label (Kyrgyz)"
                    ),
                ),
                ("value", models.CharField(max_length=50, verbose_name="Value")),
                ("order", models.IntegerField(default=0, verbose_name="Order")),
            ],
            options={
                "verbose_name": "Student Scientific Society Stat",
                "verbose_name_plural": "Student Scientific Society Stats",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="StudentScientificSocietyProjectTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=100, verbose_name="Name (Russian)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Name (English)"
                    ),
                ),
                (
                    "name_kg",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Name (Kyrgyz)"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="science.studentscientificsocietyproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Tag",
                "verbose_name_plural": "Project Tags",
            },
        ),
    ]
