# Generated by Django 5.2.7 on 2025-10-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("science", "0011_studentscientificsocietycontact_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ntsresearchdirection",
            name="description_en",
            field=models.TextField(
                blank=True, default="", verbose_name="Description (English)"
            ),
        ),
        migrations.AddField(
            model_name="ntsresearchdirection",
            name="description_kg",
            field=models.TextField(
                blank=True, default="", verbose_name="Description (Kyrgyz)"
            ),
        ),
        migrations.AddField(
            model_name="ntsresearchdirection",
            name="description_ru",
            field=models.TextField(
                blank=True, default="", verbose_name="Description (Russian)"
            ),
        ),
    ]
