# Generated by Django 5.1.2 on 2026-01-16 09:49

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0012_ntsresearchdirection_description_en_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS science_vestnikrelease CASCADE;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS science_vestnikyear CASCADE;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS science_vestnikarticle CASCADE;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS science_vestnikissue CASCADE;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS science_vestnikstats CASCADE;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS science_vestnik CASCADE;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='vestnikarticle',
                    name='issue',
                ),
                migrations.AlterUniqueTogether(
                    name='vestnikissue',
                    unique_together=None,
                ),
                migrations.DeleteModel(
                    name='VestnikArticle',
                ),
                migrations.DeleteModel(
                    name='VestnikIssue',
                ),
                migrations.DeleteModel(
                    name='VestnikStats',
                ),
                migrations.DeleteModel(
                    name='Vestnik',
                ),
            ],
        ),
        migrations.CreateModel(
            name='VestnikYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True, verbose_name='Year')),
            ],
            options={
                'verbose_name': 'Вестник год',
                'verbose_name_plural': 'Вестник годы',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='VestnikRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Title (Russian)')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Title (English)')),
                ('title_kg', models.CharField(blank=True, max_length=255, verbose_name='Title (Kyrgyz)')),
                ('description_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Description (Russian)')),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Description (English)')),
                ('description_kg', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Description (Kyrgyz)')),
                ('pdf', models.FileField(blank=True, upload_to='vestnik/releases/', verbose_name='PDF File')),
                ('vestnik_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='science.vestnikyear')),
            ],
            options={
                'verbose_name': 'Вестник выпуск',
                'verbose_name_plural': 'Вестник выпуски',
                'ordering': ['-vestnik_year__year'],
            },
        ),
    ]
