# Generated by Django 5.1.2 on 2026-01-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0013_vestnikrelease_vestnikyear_delete_vestnik_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vestnikrelease',
            old_name='pdf',
            new_name='pdf_en',
        ),
        migrations.AddField(
            model_name='vestnikrelease',
            name='pdf_kg',
            field=models.FileField(blank=True, upload_to='vestnik/releases/', verbose_name='PDF File'),
        ),
        migrations.AddField(
            model_name='vestnikrelease',
            name='pdf_ru',
            field=models.FileField(blank=True, upload_to='vestnik/releases/', verbose_name='PDF File'),
        ),
    ]
