# Generated by Django 5.1.2 on 2025-12-23 05:42

import ckeditor_uploader.fields
import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollegeDepartmentInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description_ru",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True, verbose_name="Описание(Русский)"
                    ),
                ),
                (
                    "description_kg",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True, verbose_name="Описание(Кыргызча)"
                    ),
                ),
                (
                    "description_en",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True, verbose_name="Описание(English)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Описание кафедры",
                "verbose_name_plural": "Описания кафедр",
            },
        ),
        migrations.CreateModel(
            name="CollegeManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="Фото"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=200, verbose_name="Имя (Русский)"),
                ),
                (
                    "name_kg",
                    models.CharField(max_length=200, verbose_name="Имя (Кыргызча)"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=200, verbose_name="Имя (English)"),
                ),
                (
                    "role_ru",
                    models.CharField(max_length=200, verbose_name="Роль (Русский)"),
                ),
                (
                    "role_kg",
                    models.CharField(max_length=200, verbose_name="Роль (Кыргызча)"),
                ),
                (
                    "role_en",
                    models.CharField(max_length=200, verbose_name="Роль (English)"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Номер телефона"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Руководство",
                "verbose_name_plural": "Руководство",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="CollegeTabCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=200, verbose_name="Заголовок (Русский)"
                    ),
                ),
                (
                    "name_kg",
                    models.CharField(
                        max_length=200, verbose_name="Заголовок (Кыргызча)"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=200, verbose_name="Заголовок (English)"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Например: blue-500, green-600",
                        max_length=50,
                        verbose_name="Цвет",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Категория кафедры",
                "verbose_name_plural": "Категории кафедр",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="MasterDepartmentInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description_ru",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True, verbose_name="Описание(Русский)"
                    ),
                ),
                (
                    "description_kg",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True, verbose_name="Описание(Кыргызча)"
                    ),
                ),
                (
                    "description_en",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True, verbose_name="Описание(English)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Описание кафедры",
                "verbose_name_plural": "Описания кафедр",
            },
        ),
        migrations.CreateModel(
            name="MasterManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="Фото"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=200, verbose_name="Имя (Русский)"),
                ),
                (
                    "name_kg",
                    models.CharField(max_length=200, verbose_name="Имя (Кыргызча)"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=200, verbose_name="Имя (English)"),
                ),
                (
                    "role_ru",
                    models.CharField(max_length=200, verbose_name="Роль (Русский)"),
                ),
                (
                    "role_kg",
                    models.CharField(max_length=200, verbose_name="Роль (Кыргызча)"),
                ),
                (
                    "role_en",
                    models.CharField(max_length=200, verbose_name="Роль (English)"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Номер телефона"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Руководство",
                "verbose_name_plural": "Руководство",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="MasterTabCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=200, verbose_name="Заголовок (Русский)"
                    ),
                ),
                (
                    "name_kg",
                    models.CharField(
                        max_length=200, verbose_name="Заголовок (Кыргызча)"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=200, verbose_name="Заголовок (English)"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Например: blue-500, green-600",
                        max_length=50,
                        verbose_name="Цвет",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Категория кафедры",
                "verbose_name_plural": "Категории кафедр",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PhdDepartmentInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description_ru",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True, verbose_name="Описание(Русский)"
                    ),
                ),
                (
                    "description_kg",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True, verbose_name="Описание(Кыргызча)"
                    ),
                ),
                (
                    "description_en",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True, verbose_name="Описание(English)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Описание кафедры",
                "verbose_name_plural": "Описания кафедр",
            },
        ),
        migrations.CreateModel(
            name="PhdManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="Фото"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=200, verbose_name="Имя (Русский)"),
                ),
                (
                    "name_kg",
                    models.CharField(max_length=200, verbose_name="Имя (Кыргызча)"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=200, verbose_name="Имя (English)"),
                ),
                (
                    "role_ru",
                    models.CharField(max_length=200, verbose_name="Роль (Русский)"),
                ),
                (
                    "role_kg",
                    models.CharField(max_length=200, verbose_name="Роль (Кыргызча)"),
                ),
                (
                    "role_en",
                    models.CharField(max_length=200, verbose_name="Роль (English)"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Номер телефона"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Руководство",
                "verbose_name_plural": "Руководство",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PhdTabCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=200, verbose_name="Заголовок (Русский)"
                    ),
                ),
                (
                    "name_kg",
                    models.CharField(
                        max_length=200, verbose_name="Заголовок (Кыргызча)"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=200, verbose_name="Заголовок (English)"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Например: blue-500, green-600",
                        max_length=50,
                        verbose_name="Цвет",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Категория кафедры",
                "verbose_name_plural": "Категории кафедр",
                "ordering": ["order"],
            },
        ),
        migrations.DeleteModel(
            name="CollegePrograms",
        ),
        migrations.DeleteModel(
            name="MasterPrograms",
        ),
        migrations.DeleteModel(
            name="PhdPrograms",
        ),
        migrations.AddField(
            model_name="collegemanagement",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="management",
                to="education.collegetabcategory",
                verbose_name="Кафедра",
            ),
        ),
        migrations.AddField(
            model_name="collegedepartmentinfo",
            name="category",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="info",
                to="education.collegetabcategory",
                verbose_name="Категория",
            ),
        ),
        migrations.AddField(
            model_name="mastermanagement",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="management",
                to="education.mastertabcategory",
                verbose_name="Кафедра",
            ),
        ),
        migrations.AddField(
            model_name="masterdepartmentinfo",
            name="category",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="info",
                to="education.mastertabcategory",
                verbose_name="Категория",
            ),
        ),
        migrations.AddField(
            model_name="phdmanagement",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="management",
                to="education.phdtabcategory",
                verbose_name="Кафедра",
            ),
        ),
        migrations.AddField(
            model_name="phddepartmentinfo",
            name="category",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="info",
                to="education.phdtabcategory",
                verbose_name="Категория",
            ),
        ),
    ]
