# Generated by Django 5.1.2 on 2025-10-13 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название (RU)')),
                ('name_ky', models.CharField(max_length=100, verbose_name='Название (KY)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Название (EN)')),
                ('description_ru', models.TextField(verbose_name='Описание (RU)')),
                ('description_ky', models.TextField(verbose_name='Описание (KY)')),
                ('description_en', models.TextField(verbose_name='Описание (EN)')),
                ('mission_ru', models.JSONField(verbose_name='Миссия (RU)')),
                ('mission_ky', models.JSONField(verbose_name='Миссия (KY)')),
                ('mission_en', models.JSONField(verbose_name='Миссия (EN)')),
                ('achievements_ru', models.JSONField(verbose_name='Достижения (RU)')),
                ('achievements_ky', models.JSONField(verbose_name='Достижения (KY)')),
                ('achievements_en', models.JSONField(verbose_name='Достижения (EN)')),
            ],
            options={
                'verbose_name': 'Факультет',
                'verbose_name_plural': 'Факультеты',
            },
        ),
        migrations.CreateModel(
            name='FacultyContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=100, verbose_name='Заголовок (RU)')),
                ('title_ky', models.CharField(max_length=100, verbose_name='Заголовок (KY)')),
                ('title_en', models.CharField(max_length=100, verbose_name='Заголовок (EN)')),
                ('value', models.CharField(max_length=200, verbose_name='Значение')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='education.faculty')),
            ],
            options={
                'verbose_name': 'Контакт факультета',
                'verbose_name_plural': 'Контакты факультетов',
            },
        ),
        migrations.CreateModel(
            name='FacultyPrograms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=10, verbose_name='Эмодзи')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название (RU)')),
                ('name_ky', models.CharField(max_length=100, verbose_name='Название (KY)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Название (EN)')),
                ('degree_ru', models.CharField(max_length=100, verbose_name='Степень на русском')),
                ('degree_en', models.CharField(max_length=100, verbose_name='Степень на английском')),
                ('degree_ky', models.CharField(max_length=100, verbose_name='Степень на киргизском')),
                ('description_ru', models.TextField(verbose_name='Описание (RU)')),
                ('description_ky', models.TextField(verbose_name='Описание (KY)')),
                ('description_en', models.TextField(verbose_name='Описание (EN)')),
                ('duration_years', models.IntegerField(verbose_name='Продолжительность (годы)')),
                ('offline', models.BooleanField(default=True, verbose_name='Очная форма')),
                ('tuition_fee', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стоимость обучения')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='education.faculty')),
            ],
            options={
                'verbose_name': 'Программа факультета',
                'verbose_name_plural': 'Программы факультетов',
            },
        ),
        migrations.CreateModel(
            name='FacultySpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название (RU)')),
                ('name_ky', models.CharField(max_length=100, verbose_name='Название (KY)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Название (EN)')),
                ('description_ru', models.TextField(verbose_name='Описание (RU)')),
                ('description_ky', models.TextField(verbose_name='Описание (KY)')),
                ('description_en', models.TextField(verbose_name='Описание (EN)')),
                ('features_ru', models.JSONField(verbose_name='Особенности (RU)')),
                ('features_ky', models.JSONField(verbose_name='Особенности (KY)')),
                ('features_en', models.JSONField(verbose_name='Особенности (EN)')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='education.faculty')),
            ],
            options={
                'verbose_name': 'Специализация факультета',
                'verbose_name_plural': 'Специализации факультетов',
            },
        ),
        migrations.CreateModel(
            name='FacultySports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название (RU)')),
                ('name_ky', models.CharField(max_length=100, verbose_name='Название (KY)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Название (EN)')),
                ('description_ru', models.TextField(verbose_name='Описание (RU)')),
                ('description_ky', models.TextField(verbose_name='Описание (KY)')),
                ('description_en', models.TextField(verbose_name='Описание (EN)')),
                ('emoji', models.CharField(max_length=10, verbose_name='Эмодзи')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sports', to='education.faculty')),
            ],
            options={
                'verbose_name': 'Спорт факультета',
                'verbose_name_plural': 'Спорт факультетов',
            },
        ),
        migrations.CreateModel(
            name='FacultyStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleInt', models.CharField(max_length=100, verbose_name='Заголовок (INT)')),
                ('meaning_ru', models.CharField(max_length=100, verbose_name='Значение (RU)')),
                ('meaning_ky', models.CharField(max_length=100, verbose_name='Значение (KY)')),
                ('meaning_en', models.CharField(max_length=100, verbose_name='Знач   ение (EN)')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='education.faculty')),
            ],
            options={
                'verbose_name': 'Статистика факультета',
                'verbose_name_plural': 'Статистика факультетов',
            },
        ),
        migrations.CreateModel(
            name='FacultyTeachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_ru', models.CharField(max_length=100, verbose_name='Полное имя (RU)')),
                ('full_name_ky', models.CharField(max_length=100, verbose_name='Полное имя (KY)')),
                ('full_name_en', models.CharField(max_length=100, verbose_name='Полное имя (EN)')),
                ('position_ru', models.CharField(max_length=100, verbose_name='Должность (RU)')),
                ('position_ky', models.CharField(max_length=100, verbose_name='Должность (KY)')),
                ('position_en', models.CharField(max_length=100, verbose_name='Должность (EN)')),
                ('photo', models.ImageField(upload_to='faculty_teachers/', verbose_name='Фото')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='education.faculty')),
            ],
            options={
                'verbose_name': 'Преподаватель факультета',
                'verbose_name_plural': 'Преподаватели факультетов',
            },
        ),
    ]
