# Generated by Django 5.1.2 on 2026-01-14 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_collegedepartmentinfo_collegemanagement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collegedepartmentinfo',
            options={'verbose_name': 'Описание кафедры (колледж)', 'verbose_name_plural': 'Описания кафедр (колледж)'},
        ),
        migrations.AlterModelOptions(
            name='collegemanagement',
            options={'ordering': ['order'], 'verbose_name': 'Руководство (колледж)', 'verbose_name_plural': 'Руководство (колледж)'},
        ),
        migrations.AlterModelOptions(
            name='collegetabcategory',
            options={'ordering': ['order'], 'verbose_name': 'Категория кафедры (колледж)', 'verbose_name_plural': 'Категории кафедр (колледж)'},
        ),
        migrations.AlterModelOptions(
            name='masterdepartmentinfo',
            options={'verbose_name': 'Описание кафедры (магистратура)', 'verbose_name_plural': 'Описания кафедр (магистратура)'},
        ),
        migrations.AlterModelOptions(
            name='mastermanagement',
            options={'ordering': ['order'], 'verbose_name': 'Руководство (магистратура)', 'verbose_name_plural': 'Руководство (магистратура)'},
        ),
        migrations.AlterModelOptions(
            name='mastertabcategory',
            options={'ordering': ['order'], 'verbose_name': 'Категория кафедры (магистратура)', 'verbose_name_plural': 'Категории кафедр (магистратура)'},
        ),
        migrations.AlterModelOptions(
            name='phddepartmentinfo',
            options={'verbose_name': 'Описание кафедры (доктурантура)', 'verbose_name_plural': 'Описания кафедр (доктурантура)'},
        ),
        migrations.AlterModelOptions(
            name='phdmanagement',
            options={'ordering': ['order'], 'verbose_name': 'Руководство (доктурантура)', 'verbose_name_plural': 'Руководство (доктурантура)'},
        ),
        migrations.AlterModelOptions(
            name='phdtabcategory',
            options={'ordering': ['order'], 'verbose_name': 'Категория кафедры(доктурантура)', 'verbose_name_plural': 'Категории кафедр(доктурантура)'},
        ),
    ]
