# Generated by Django 5.1.2 on 2025-10-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_faculty_facultycontacts_facultyprograms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegePrograms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=10, verbose_name='Эмодзи')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название (RU)')),
                ('name_ky', models.CharField(max_length=100, verbose_name='Название (KY)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Название (EN)')),
                ('description_ru', models.TextField(verbose_name='Описание (RU)')),
                ('description_ky', models.TextField(verbose_name='Описание (KY)')),
                ('description_en', models.TextField(verbose_name='Описание (EN)')),
                ('features_ru', models.JSONField(verbose_name='Особенности (RU)')),
                ('features_ky', models.JSONField(verbose_name='Особенности (KY)')),
                ('features_en', models.JSONField(verbose_name='Особенности (EN)')),
                ('duration_years', models.IntegerField(verbose_name='Продолжительность (годы)')),
                ('offline', models.BooleanField(default=True, verbose_name='Очная форма')),
                ('tuition_fee', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стоимость обучения')),
            ],
            options={
                'verbose_name': 'Программа колледжа',
                'verbose_name_plural': 'Программы колледжа',
            },
        ),
        migrations.CreateModel(
            name='PhdPrograms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=10, verbose_name='Эмодзи')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название (RU)')),
                ('name_ky', models.CharField(max_length=100, verbose_name='Название (KY)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Название (EN)')),
                ('description_ru', models.TextField(verbose_name='Описание (RU)')),
                ('description_ky', models.TextField(verbose_name='Описание (KY)')),
                ('description_en', models.TextField(verbose_name='Описание (EN)')),
                ('features_ru', models.JSONField(verbose_name='Особенности (RU)')),
                ('features_ky', models.JSONField(verbose_name='Особенности (KY)')),
                ('features_en', models.JSONField(verbose_name='Особенности (EN)')),
                ('duration_years', models.IntegerField(verbose_name='Продолжительность (годы)')),
                ('offline', models.BooleanField(default=True, verbose_name='Очная форма')),
                ('tuition_fee', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стоимость обучения')),
            ],
            options={
                'verbose_name': 'Программа доктурантуры',
                'verbose_name_plural': 'Программы доктурантуры',
            },
        ),
    ]
