# Generated by Django 5.2.7 on 2025-10-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0003_collegeprograms_phdprograms"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icon", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="AboutPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="about_photos/")),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="AboutStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.IntegerField()),
                ("label", models.CharField(max_length=100)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("suffix", models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
