# Generated by Django 5.2.7 on 2025-10-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0004_aboutfeature_aboutphoto_aboutstat"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collegeprograms",
            options={
                "verbose_name": "РџСЂРѕРіСЂР°РјРјР° РєРѕР»Р»РµРґР¶Р°",
                "verbose_name_plural": "РџСЂРѕРіСЂР°РјРјС‹ РєРѕР»Р»РµРґР¶Р°",
            },
        ),
        migrations.AlterModelOptions(
            name="faculty",
            options={
                "verbose_name": "Р¤Р°РєСѓР»СЊС‚РµС‚",
                "verbose_name_plural": "Р¤Р°РєСѓР»СЊС‚РµС‚С‹",
            },
        ),
        migrations.AlterModelOptions(
            name="facultycontacts",
            options={
                "verbose_name": "РљРѕРЅС‚Р°РєС‚ С„Р°РєСѓР»СЊС‚РµС‚Р°",
                "verbose_name_plural": "РљРѕРЅС‚Р°РєС‚С‹ С„Р°РєСѓР»СЊС‚РµС‚РѕРІ",
            },
        ),
        migrations.AlterModelOptions(
            name="facultyprograms",
            options={
                "verbose_name": "РџСЂРѕРіСЂР°РјРјР° С„Р°РєСѓР»СЊС‚РµС‚Р°",
                "verbose_name_plural": "РџСЂРѕРіСЂР°РјРјС‹ С„Р°РєСѓР»СЊС‚РµС‚РѕРІ",
            },
        ),
        migrations.AlterModelOptions(
            name="facultyspecialization",
            options={
                "verbose_name": "РЎРїРµС†РёР°Р»РёР·Р°С†РёСЏ С„Р°РєСѓР»СЊС‚РµС‚Р°",
                "verbose_name_plural": "РЎРїРµС†РёР°Р»РёР·Р°С†РёРё С„Р°РєСѓР»СЊС‚РµС‚РѕРІ",
            },
        ),
        migrations.AlterModelOptions(
            name="facultysports",
            options={
                "verbose_name": "РЎРїРѕСЂС‚ С„Р°РєСѓР»СЊС‚РµС‚Р°",
                "verbose_name_plural": "РЎРїРѕСЂС‚ С„Р°РєСѓР»СЊС‚РµС‚РѕРІ",
            },
        ),
        migrations.AlterModelOptions(
            name="facultystatistics",
            options={
                "verbose_name": "РЎС‚Р°С‚РёСЃС‚РёРєР° С„Р°РєСѓР»СЊС‚РµС‚Р°",
                "verbose_name_plural": "РЎС‚Р°С‚РёСЃС‚РёРєР° С„Р°РєСѓР»СЊС‚РµС‚РѕРІ",
            },
        ),
        migrations.AlterModelOptions(
            name="facultyteachers",
            options={
                "verbose_name": "РџСЂРµРїРѕРґР°РІР°С‚РµР»СЊ С„Р°РєСѓР»СЊС‚РµС‚Р°",
                "verbose_name_plural": "РџСЂРµРїРѕРґР°РІР°С‚РµР»Рё С„Р°РєСѓР»СЊС‚РµС‚РѕРІ",
            },
        ),
        migrations.AlterModelOptions(
            name="masterprograms",
            options={
                "verbose_name": "РџСЂРѕРіСЂР°РјРјР° РјР°РіРёСЃС‚СЂР°",
                "verbose_name_plural": "РџСЂРѕРіСЂР°РјРјС‹ РјР°РіРёСЃС‚СЂР°",
            },
        ),
        migrations.AlterModelOptions(
            name="phdprograms",
            options={
                "verbose_name": "РџСЂРѕРіСЂР°РјРјР° РґРѕРєС‚СѓСЂР°РЅС‚СѓСЂС‹",
                "verbose_name_plural": "РџСЂРѕРіСЂР°РјРјС‹ РґРѕРєС‚СѓСЂР°РЅС‚СѓСЂС‹",
            },
        ),
        migrations.RemoveField(
            model_name="collegeprograms",
            name="description_ky",
        ),
        migrations.RemoveField(
            model_name="collegeprograms",
            name="features_ky",
        ),
        migrations.RemoveField(
            model_name="collegeprograms",
            name="name_ky",
        ),
        migrations.RemoveField(
            model_name="faculty",
            name="achievements_ky",
        ),
        migrations.RemoveField(
            model_name="faculty",
            name="description_ky",
        ),
        migrations.RemoveField(
            model_name="faculty",
            name="mission_ky",
        ),
        migrations.RemoveField(
            model_name="faculty",
            name="name_ky",
        ),
        migrations.RemoveField(
            model_name="facultycontacts",
            name="title_ky",
        ),
        migrations.RemoveField(
            model_name="facultyprograms",
            name="degree_ky",
        ),
        migrations.RemoveField(
            model_name="facultyprograms",
            name="description_ky",
        ),
        migrations.RemoveField(
            model_name="facultyprograms",
            name="name_ky",
        ),
        migrations.RemoveField(
            model_name="facultyspecialization",
            name="description_ky",
        ),
        migrations.RemoveField(
            model_name="facultyspecialization",
            name="features_ky",
        ),
        migrations.RemoveField(
            model_name="facultyspecialization",
            name="name_ky",
        ),
        migrations.RemoveField(
            model_name="facultysports",
            name="description_ky",
        ),
        migrations.RemoveField(
            model_name="facultysports",
            name="name_ky",
        ),
        migrations.RemoveField(
            model_name="facultystatistics",
            name="meaning_ky",
        ),
        migrations.RemoveField(
            model_name="facultyteachers",
            name="full_name_ky",
        ),
        migrations.RemoveField(
            model_name="facultyteachers",
            name="position_ky",
        ),
        migrations.RemoveField(
            model_name="masterprograms",
            name="description_ky",
        ),
        migrations.RemoveField(
            model_name="masterprograms",
            name="features_ky",
        ),
        migrations.RemoveField(
            model_name="masterprograms",
            name="name_ky",
        ),
        migrations.RemoveField(
            model_name="phdprograms",
            name="description_ky",
        ),
        migrations.RemoveField(
            model_name="phdprograms",
            name="features_ky",
        ),
        migrations.RemoveField(
            model_name="phdprograms",
            name="name_ky",
        ),
        migrations.AddField(
            model_name="collegeprograms",
            name="description_kg",
            field=models.TextField(default="", verbose_name="РћРїРёСЃР°РЅРёРµ (KY)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="collegeprograms",
            name="features_kg",
            field=models.JSONField(
                default="", verbose_name="РћСЃРѕР±РµРЅРЅРѕСЃС‚Рё (KY)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="collegeprograms",
            name="name_kg",
            field=models.CharField(
                default="", max_length=100, verbose_name="РќР°Р·РІР°РЅРёРµ (KY)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="faculty",
            name="achievements_kg",
            field=models.JSONField(
                default="", verbose_name="Р”РѕСЃС‚РёР¶РµРЅРёСЏ (KY)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="faculty",
            name="description_kg",
            field=models.TextField(default="", verbose_name="РћРїРёСЃР°РЅРёРµ (KY)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="faculty",
            name="mission_kg",
            field=models.JSONField(default="", verbose_name="РњРёСЃСЃРёСЏ (KY)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="faculty",
            name="name_kg",
            field=models.CharField(
                default="", max_length=100, verbose_name="РќР°Р·РІР°РЅРёРµ (KY)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="facultycontacts",
            name="title_kg",
            field=models.CharField(
                default="", max_length=100, verbose_name="Р—Р°РіРѕР»РѕРІРѕРє (KY)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="facultyprograms",
            name="degree_kg",
            field=models.CharField(
                default="",
                max_length=100,
                verbose_name="РЎС‚РµРїРµРЅСЊ РЅР° РєРёСЂРіРёР·СЃРєРѕРј",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="facultyprograms",
            name="description_kg",
            field=models.TextField(default="", verbose_name="РћРїРёСЃР°РЅРёРµ (KY)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="facultyprograms",
            name="name_kg",
            field=models.CharField(
                default="", max_length=100, verbose_name="РќР°Р·РІР°РЅРёРµ (KY)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="facultyspecialization",
            name="description_kg",
            field=models.TextField(default="", verbose_name="РћРїРёСЃР°РЅРёРµ (KY)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="facultyspecialization",
            name="features_kg",
            field=models.JSONField(
                default="", verbose_name="РћСЃРѕР±РµРЅРЅРѕСЃС‚Рё (KY)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="facultyspecialization",
            name="name_kg",
            field=models.CharField(
                default="", max_length=100, verbose_name="РќР°Р·РІР°РЅРёРµ (KY)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="facultysports",
            name="description_kg",
            field=models.TextField(default="", verbose_name="РћРїРёСЃР°РЅРёРµ (KY)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="facultysports",
            name="name_kg",
            field=models.CharField(
                default="", max_length=100, verbose_name="РќР°Р·РІР°РЅРёРµ (KY)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="facultystatistics",
            name="meaning_kg",
            field=models.CharField(
                default="", max_length=100, verbose_name="Р—РЅР°С‡РµРЅРёРµ (KY)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="facultyteachers",
            name="full_name_kg",
            field=models.CharField(
                default="", max_length=100, verbose_name="РџРѕР»РЅРѕРµ РёРјСЏ (KY)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="facultyteachers",
            name="position_kg",
            field=models.CharField(
                default="", max_length=100, verbose_name="Р”РѕР»Р¶РЅРѕСЃС‚СЊ (KY)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="masterprograms",
            name="description_kg",
            field=models.TextField(default="", verbose_name="РћРїРёСЃР°РЅРёРµ (KY)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="masterprograms",
            name="features_kg",
            field=models.JSONField(
                default="", verbose_name="РћСЃРѕР±РµРЅРЅРѕСЃС‚Рё (KY)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="masterprograms",
            name="name_kg",
            field=models.CharField(
                default="", max_length=100, verbose_name="РќР°Р·РІР°РЅРёРµ (KY)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="phdprograms",
            name="description_kg",
            field=models.TextField(default="", verbose_name="РћРїРёСЃР°РЅРёРµ (KY)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="phdprograms",
            name="features_kg",
            field=models.JSONField(
                default="", verbose_name="РћСЃРѕР±РµРЅРЅРѕСЃС‚Рё (KY)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="phdprograms",
            name="name_kg",
            field=models.CharField(
                default="", max_length=100, verbose_name="РќР°Р·РІР°РЅРёРµ (KY)"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="collegeprograms",
            name="description_en",
            field=models.TextField(verbose_name="РћРїРёСЃР°РЅРёРµ (EN)"),
        ),
        migrations.AlterField(
            model_name="collegeprograms",
            name="description_ru",
            field=models.TextField(verbose_name="РћРїРёСЃР°РЅРёРµ (RU)"),
        ),
        migrations.AlterField(
            model_name="collegeprograms",
            name="duration_years",
            field=models.IntegerField(
                verbose_name="РџСЂРѕРґРѕР»Р¶РёС‚РµР»СЊРЅРѕСЃС‚СЊ (РіРѕРґС‹)"
            ),
        ),
        migrations.AlterField(
            model_name="collegeprograms",
            name="emoji",
            field=models.CharField(max_length=10, verbose_name="Р\xadРјРѕРґР·Рё"),
        ),
        migrations.AlterField(
            model_name="collegeprograms",
            name="features_en",
            field=models.JSONField(verbose_name="РћСЃРѕР±РµРЅРЅРѕСЃС‚Рё (EN)"),
        ),
        migrations.AlterField(
            model_name="collegeprograms",
            name="features_ru",
            field=models.JSONField(verbose_name="РћСЃРѕР±РµРЅРЅРѕСЃС‚Рё (RU)"),
        ),
        migrations.AlterField(
            model_name="collegeprograms",
            name="name_en",
            field=models.CharField(
                max_length=100, verbose_name="РќР°Р·РІР°РЅРёРµ (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="collegeprograms",
            name="name_ru",
            field=models.CharField(
                max_length=100, verbose_name="РќР°Р·РІР°РЅРёРµ (RU)"
            ),
        ),
        migrations.AlterField(
            model_name="collegeprograms",
            name="offline",
            field=models.BooleanField(
                default=True, verbose_name="РћС‡РЅР°СЏ С„РѕСЂРјР°"
            ),
        ),
        migrations.AlterField(
            model_name="collegeprograms",
            name="tuition_fee",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                verbose_name="РЎС‚РѕРёРјРѕСЃС‚СЊ РѕР±СѓС‡РµРЅРёСЏ",
            ),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="achievements_en",
            field=models.JSONField(verbose_name="Р”РѕСЃС‚РёР¶РµРЅРёСЏ (EN)"),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="achievements_ru",
            field=models.JSONField(verbose_name="Р”РѕСЃС‚РёР¶РµРЅРёСЏ (RU)"),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="description_en",
            field=models.TextField(verbose_name="РћРїРёСЃР°РЅРёРµ (EN)"),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="description_ru",
            field=models.TextField(verbose_name="РћРїРёСЃР°РЅРёРµ (RU)"),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="mission_en",
            field=models.JSONField(verbose_name="РњРёСЃСЃРёСЏ (EN)"),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="mission_ru",
            field=models.JSONField(verbose_name="РњРёСЃСЃРёСЏ (RU)"),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="name_en",
            field=models.CharField(
                max_length=100, verbose_name="РќР°Р·РІР°РЅРёРµ (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="name_ru",
            field=models.CharField(
                max_length=100, verbose_name="РќР°Р·РІР°РЅРёРµ (RU)"
            ),
        ),
        migrations.AlterField(
            model_name="facultycontacts",
            name="title_en",
            field=models.CharField(
                max_length=100, verbose_name="Р—Р°РіРѕР»РѕРІРѕРє (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="facultycontacts",
            name="title_ru",
            field=models.CharField(
                max_length=100, verbose_name="Р—Р°РіРѕР»РѕРІРѕРє (RU)"
            ),
        ),
        migrations.AlterField(
            model_name="facultycontacts",
            name="value",
            field=models.CharField(max_length=200, verbose_name="Р—РЅР°С‡РµРЅРёРµ"),
        ),
        migrations.AlterField(
            model_name="facultyprograms",
            name="degree_en",
            field=models.CharField(
                max_length=100, verbose_name="РЎС‚РµРїРµРЅСЊ РЅР° Р°РЅРіР»РёР№СЃРєРѕРј"
            ),
        ),
        migrations.AlterField(
            model_name="facultyprograms",
            name="degree_ru",
            field=models.CharField(
                max_length=100, verbose_name="РЎС‚РµРїРµРЅСЊ РЅР° СЂСѓСЃСЃРєРѕРј"
            ),
        ),
        migrations.AlterField(
            model_name="facultyprograms",
            name="description_en",
            field=models.TextField(verbose_name="РћРїРёСЃР°РЅРёРµ (EN)"),
        ),
        migrations.AlterField(
            model_name="facultyprograms",
            name="description_ru",
            field=models.TextField(verbose_name="РћРїРёСЃР°РЅРёРµ (RU)"),
        ),
        migrations.AlterField(
            model_name="facultyprograms",
            name="duration_years",
            field=models.IntegerField(
                verbose_name="РџСЂРѕРґРѕР»Р¶РёС‚РµР»СЊРЅРѕСЃС‚СЊ (РіРѕРґС‹)"
            ),
        ),
        migrations.AlterField(
            model_name="facultyprograms",
            name="emoji",
            field=models.CharField(max_length=10, verbose_name="Р\xadРјРѕРґР·Рё"),
        ),
        migrations.AlterField(
            model_name="facultyprograms",
            name="name_en",
            field=models.CharField(
                max_length=100, verbose_name="РќР°Р·РІР°РЅРёРµ (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="facultyprograms",
            name="name_ru",
            field=models.CharField(
                max_length=100, verbose_name="РќР°Р·РІР°РЅРёРµ (RU)"
            ),
        ),
        migrations.AlterField(
            model_name="facultyprograms",
            name="offline",
            field=models.BooleanField(
                default=True, verbose_name="РћС‡РЅР°СЏ С„РѕСЂРјР°"
            ),
        ),
        migrations.AlterField(
            model_name="facultyprograms",
            name="tuition_fee",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                verbose_name="РЎС‚РѕРёРјРѕСЃС‚СЊ РѕР±СѓС‡РµРЅРёСЏ",
            ),
        ),
        migrations.AlterField(
            model_name="facultyspecialization",
            name="description_en",
            field=models.TextField(verbose_name="РћРїРёСЃР°РЅРёРµ (EN)"),
        ),
        migrations.AlterField(
            model_name="facultyspecialization",
            name="description_ru",
            field=models.TextField(verbose_name="РћРїРёСЃР°РЅРёРµ (RU)"),
        ),
        migrations.AlterField(
            model_name="facultyspecialization",
            name="features_en",
            field=models.JSONField(verbose_name="РћСЃРѕР±РµРЅРЅРѕСЃС‚Рё (EN)"),
        ),
        migrations.AlterField(
            model_name="facultyspecialization",
            name="features_ru",
            field=models.JSONField(verbose_name="РћСЃРѕР±РµРЅРЅРѕСЃС‚Рё (RU)"),
        ),
        migrations.AlterField(
            model_name="facultyspecialization",
            name="name_en",
            field=models.CharField(
                max_length=100, verbose_name="РќР°Р·РІР°РЅРёРµ (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="facultyspecialization",
            name="name_ru",
            field=models.CharField(
                max_length=100, verbose_name="РќР°Р·РІР°РЅРёРµ (RU)"
            ),
        ),
        migrations.AlterField(
            model_name="facultysports",
            name="description_en",
            field=models.TextField(verbose_name="РћРїРёСЃР°РЅРёРµ (EN)"),
        ),
        migrations.AlterField(
            model_name="facultysports",
            name="description_ru",
            field=models.TextField(verbose_name="РћРїРёСЃР°РЅРёРµ (RU)"),
        ),
        migrations.AlterField(
            model_name="facultysports",
            name="emoji",
            field=models.CharField(max_length=10, verbose_name="Р\xadРјРѕРґР·Рё"),
        ),
        migrations.AlterField(
            model_name="facultysports",
            name="name_en",
            field=models.CharField(
                max_length=100, verbose_name="РќР°Р·РІР°РЅРёРµ (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="facultysports",
            name="name_ru",
            field=models.CharField(
                max_length=100, verbose_name="РќР°Р·РІР°РЅРёРµ (RU)"
            ),
        ),
        migrations.AlterField(
            model_name="facultystatistics",
            name="meaning_en",
            field=models.CharField(
                max_length=100, verbose_name="Р—РЅР°С‡   РµРЅРёРµ (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="facultystatistics",
            name="meaning_ru",
            field=models.CharField(
                max_length=100, verbose_name="Р—РЅР°С‡РµРЅРёРµ (RU)"
            ),
        ),
        migrations.AlterField(
            model_name="facultystatistics",
            name="titleInt",
            field=models.CharField(
                max_length=100, verbose_name="Р—Р°РіРѕР»РѕРІРѕРє (INT)"
            ),
        ),
        migrations.AlterField(
            model_name="facultyteachers",
            name="full_name_en",
            field=models.CharField(
                max_length=100, verbose_name="РџРѕР»РЅРѕРµ РёРјСЏ (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="facultyteachers",
            name="full_name_ru",
            field=models.CharField(
                max_length=100, verbose_name="РџРѕР»РЅРѕРµ РёРјСЏ (RU)"
            ),
        ),
        migrations.AlterField(
            model_name="facultyteachers",
            name="photo",
            field=models.ImageField(
                upload_to="faculty_teachers/", verbose_name="Р¤РѕС‚Рѕ"
            ),
        ),
        migrations.AlterField(
            model_name="facultyteachers",
            name="position_en",
            field=models.CharField(
                max_length=100, verbose_name="Р”РѕР»Р¶РЅРѕСЃС‚СЊ (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="facultyteachers",
            name="position_ru",
            field=models.CharField(
                max_length=100, verbose_name="Р”РѕР»Р¶РЅРѕСЃС‚СЊ (RU)"
            ),
        ),
        migrations.AlterField(
            model_name="masterprograms",
            name="description_en",
            field=models.TextField(verbose_name="РћРїРёСЃР°РЅРёРµ (EN)"),
        ),
        migrations.AlterField(
            model_name="masterprograms",
            name="description_ru",
            field=models.TextField(verbose_name="РћРїРёСЃР°РЅРёРµ (RU)"),
        ),
        migrations.AlterField(
            model_name="masterprograms",
            name="duration_years",
            field=models.IntegerField(
                verbose_name="РџСЂРѕРґРѕР»Р¶РёС‚РµР»СЊРЅРѕСЃС‚СЊ (РіРѕРґС‹)"
            ),
        ),
        migrations.AlterField(
            model_name="masterprograms",
            name="emoji",
            field=models.CharField(max_length=10, verbose_name="Р\xadРјРѕРґР·Рё"),
        ),
        migrations.AlterField(
            model_name="masterprograms",
            name="features_en",
            field=models.JSONField(verbose_name="РћСЃРѕР±РµРЅРЅРѕСЃС‚Рё (EN)"),
        ),
        migrations.AlterField(
            model_name="masterprograms",
            name="features_ru",
            field=models.JSONField(verbose_name="РћСЃРѕР±РµРЅРЅРѕСЃС‚Рё (RU)"),
        ),
        migrations.AlterField(
            model_name="masterprograms",
            name="name_en",
            field=models.CharField(
                max_length=100, verbose_name="РќР°Р·РІР°РЅРёРµ (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="masterprograms",
            name="name_ru",
            field=models.CharField(
                max_length=100, verbose_name="РќР°Р·РІР°РЅРёРµ (RU)"
            ),
        ),
        migrations.AlterField(
            model_name="masterprograms",
            name="offline",
            field=models.BooleanField(
                default=True, verbose_name="РћС‡РЅР°СЏ С„РѕСЂРјР°"
            ),
        ),
        migrations.AlterField(
            model_name="masterprograms",
            name="tuition_fee",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                verbose_name="РЎС‚РѕРёРјРѕСЃС‚СЊ РѕР±СѓС‡РµРЅРёСЏ",
            ),
        ),
        migrations.AlterField(
            model_name="phdprograms",
            name="description_en",
            field=models.TextField(verbose_name="РћРїРёСЃР°РЅРёРµ (EN)"),
        ),
        migrations.AlterField(
            model_name="phdprograms",
            name="description_ru",
            field=models.TextField(verbose_name="РћРїРёСЃР°РЅРёРµ (RU)"),
        ),
        migrations.AlterField(
            model_name="phdprograms",
            name="duration_years",
            field=models.IntegerField(
                verbose_name="РџСЂРѕРґРѕР»Р¶РёС‚РµР»СЊРЅРѕСЃС‚СЊ (РіРѕРґС‹)"
            ),
        ),
        migrations.AlterField(
            model_name="phdprograms",
            name="emoji",
            field=models.CharField(max_length=10, verbose_name="Р\xadРјРѕРґР·Рё"),
        ),
        migrations.AlterField(
            model_name="phdprograms",
            name="features_en",
            field=models.JSONField(verbose_name="РћСЃРѕР±РµРЅРЅРѕСЃС‚Рё (EN)"),
        ),
        migrations.AlterField(
            model_name="phdprograms",
            name="features_ru",
            field=models.JSONField(verbose_name="РћСЃРѕР±РµРЅРЅРѕСЃС‚Рё (RU)"),
        ),
        migrations.AlterField(
            model_name="phdprograms",
            name="name_en",
            field=models.CharField(
                max_length=100, verbose_name="РќР°Р·РІР°РЅРёРµ (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="phdprograms",
            name="name_ru",
            field=models.CharField(
                max_length=100, verbose_name="РќР°Р·РІР°РЅРёРµ (RU)"
            ),
        ),
        migrations.AlterField(
            model_name="phdprograms",
            name="offline",
            field=models.BooleanField(
                default=True, verbose_name="РћС‡РЅР°СЏ С„РѕСЂРјР°"
            ),
        ),
        migrations.AlterField(
            model_name="phdprograms",
            name="tuition_fee",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                verbose_name="РЎС‚РѕРёРјРѕСЃС‚СЊ РѕР±СѓС‡РµРЅРёСЏ",
            ),
        ),
    ]
