# Generated by Django 5.2.7 on 2025-10-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "education",
            "0005_alter_collegeprograms_options_alter_faculty_options_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="AboutFeature",
        ),
        migrations.DeleteModel(
            name="AboutPhoto",
        ),
        migrations.DeleteModel(
            name="AboutStat",
        ),
        migrations.AlterModelOptions(
            name="collegeprograms",
            options={
                "verbose_name": "Программа колледжа",
                "verbose_name_plural": "Программы колледжа",
            },
        ),
        migrations.AlterModelOptions(
            name="faculty",
            options={"verbose_name": "Факультет", "verbose_name_plural": "Факультеты"},
        ),
        migrations.AlterModelOptions(
            name="facultycontacts",
            options={
                "verbose_name": "Контакт факультета",
                "verbose_name_plural": "Контакты факультетов",
            },
        ),
        migrations.AlterModelOptions(
            name="facultyprograms",
            options={
                "verbose_name": "Программа факультета",
                "verbose_name_plural": "Программы факультетов",
            },
        ),
        migrations.AlterModelOptions(
            name="facultyspecialization",
            options={
                "verbose_name": "Специализация факультета",
                "verbose_name_plural": "Специализации факультетов",
            },
        ),
        migrations.AlterModelOptions(
            name="facultysports",
            options={
                "verbose_name": "Спорт факультета",
                "verbose_name_plural": "Спорт факультетов",
            },
        ),
        migrations.AlterModelOptions(
            name="facultystatistics",
            options={
                "verbose_name": "Статистика факультета",
                "verbose_name_plural": "Статистика факультетов",
            },
        ),
        migrations.AlterModelOptions(
            name="facultyteachers",
            options={
                "verbose_name": "Преподаватель факультета",
                "verbose_name_plural": "Преподаватели факультетов",
            },
        ),
        migrations.AlterModelOptions(
            name="masterprograms",
            options={
                "verbose_name": "Программа магистра",
                "verbose_name_plural": "Программы магистра",
            },
        ),
        migrations.AlterModelOptions(
            name="phdprograms",
            options={
                "verbose_name": "Программа докторантуры",
                "verbose_name_plural": "Программы докторантуры",
            },
        ),
        migrations.AlterField(
            model_name="collegeprograms",
            name="description_en",
            field=models.TextField(verbose_name="Описание (EN)"),
        ),
        migrations.AlterField(
            model_name="collegeprograms",
            name="description_kg",
            field=models.TextField(verbose_name="Описание (KY)"),
        ),
        migrations.AlterField(
            model_name="collegeprograms",
            name="description_ru",
            field=models.TextField(verbose_name="Описание (RU)"),
        ),
        migrations.AlterField(
            model_name="collegeprograms",
            name="duration_years",
            field=models.IntegerField(verbose_name="Продолжительность (годы)"),
        ),
        migrations.AlterField(
            model_name="collegeprograms",
            name="emoji",
            field=models.CharField(max_length=10, verbose_name="Эмодзи"),
        ),
        migrations.AlterField(
            model_name="collegeprograms",
            name="features_en",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="Особенности (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="collegeprograms",
            name="features_kg",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="Особенности (KY)"
            ),
        ),
        migrations.AlterField(
            model_name="collegeprograms",
            name="features_ru",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="Особенности (RU)"
            ),
        ),
        migrations.AlterField(
            model_name="collegeprograms",
            name="name_en",
            field=models.CharField(max_length=100, verbose_name="Название (EN)"),
        ),
        migrations.AlterField(
            model_name="collegeprograms",
            name="name_kg",
            field=models.CharField(max_length=100, verbose_name="Название (KY)"),
        ),
        migrations.AlterField(
            model_name="collegeprograms",
            name="name_ru",
            field=models.CharField(max_length=100, verbose_name="Название (RU)"),
        ),
        migrations.AlterField(
            model_name="collegeprograms",
            name="offline",
            field=models.BooleanField(default=True, verbose_name="Очная форма"),
        ),
        migrations.AlterField(
            model_name="collegeprograms",
            name="tuition_fee",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Стоимость обучения"
            ),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="achievements_en",
            field=models.JSONField(verbose_name="Достижения (EN)"),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="achievements_kg",
            field=models.JSONField(verbose_name="Достижения (KY)"),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="achievements_ru",
            field=models.JSONField(verbose_name="Достижения (RU)"),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="description_en",
            field=models.TextField(verbose_name="Описание (EN)"),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="description_kg",
            field=models.TextField(verbose_name="Описание (KY)"),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="description_ru",
            field=models.TextField(verbose_name="Описание (RU)"),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="mission_en",
            field=models.JSONField(verbose_name="Миссия (EN)"),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="mission_kg",
            field=models.JSONField(verbose_name="Миссия (KY)"),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="mission_ru",
            field=models.JSONField(verbose_name="Миссия (RU)"),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="name_en",
            field=models.CharField(max_length=100, verbose_name="Название (EN)"),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="name_kg",
            field=models.CharField(max_length=100, verbose_name="Название (KY)"),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="name_ru",
            field=models.CharField(max_length=100, verbose_name="Название (RU)"),
        ),
        migrations.AlterField(
            model_name="facultycontacts",
            name="title_en",
            field=models.CharField(max_length=100, verbose_name="Заголовок (EN)"),
        ),
        migrations.AlterField(
            model_name="facultycontacts",
            name="title_kg",
            field=models.CharField(max_length=100, verbose_name="Заголовок (KY)"),
        ),
        migrations.AlterField(
            model_name="facultycontacts",
            name="title_ru",
            field=models.CharField(max_length=100, verbose_name="Заголовок (RU)"),
        ),
        migrations.AlterField(
            model_name="facultycontacts",
            name="value",
            field=models.CharField(max_length=200, verbose_name="Значение"),
        ),
        migrations.AlterField(
            model_name="facultyprograms",
            name="degree_en",
            field=models.CharField(
                max_length=100, verbose_name="Степень на английском"
            ),
        ),
        migrations.AlterField(
            model_name="facultyprograms",
            name="degree_kg",
            field=models.CharField(
                max_length=100, verbose_name="Степень на киргизском"
            ),
        ),
        migrations.AlterField(
            model_name="facultyprograms",
            name="degree_ru",
            field=models.CharField(max_length=100, verbose_name="Степень на русском"),
        ),
        migrations.AlterField(
            model_name="facultyprograms",
            name="description_en",
            field=models.TextField(verbose_name="Описание (EN)"),
        ),
        migrations.AlterField(
            model_name="facultyprograms",
            name="description_kg",
            field=models.TextField(verbose_name="Описание (KY)"),
        ),
        migrations.AlterField(
            model_name="facultyprograms",
            name="description_ru",
            field=models.TextField(verbose_name="Описание (RU)"),
        ),
        migrations.AlterField(
            model_name="facultyprograms",
            name="duration_years",
            field=models.IntegerField(verbose_name="Продолжительность (годы)"),
        ),
        migrations.AlterField(
            model_name="facultyprograms",
            name="emoji",
            field=models.CharField(max_length=10, verbose_name="Эмодзи"),
        ),
        migrations.AlterField(
            model_name="facultyprograms",
            name="name_en",
            field=models.CharField(max_length=100, verbose_name="Название (EN)"),
        ),
        migrations.AlterField(
            model_name="facultyprograms",
            name="name_kg",
            field=models.CharField(max_length=100, verbose_name="Название (KY)"),
        ),
        migrations.AlterField(
            model_name="facultyprograms",
            name="name_ru",
            field=models.CharField(max_length=100, verbose_name="Название (RU)"),
        ),
        migrations.AlterField(
            model_name="facultyprograms",
            name="offline",
            field=models.BooleanField(default=True, verbose_name="Очная форма"),
        ),
        migrations.AlterField(
            model_name="facultyprograms",
            name="tuition_fee",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Стоимость обучения"
            ),
        ),
        migrations.AlterField(
            model_name="facultyspecialization",
            name="description_en",
            field=models.TextField(verbose_name="Описание (EN)"),
        ),
        migrations.AlterField(
            model_name="facultyspecialization",
            name="description_kg",
            field=models.TextField(verbose_name="Описание (KY)"),
        ),
        migrations.AlterField(
            model_name="facultyspecialization",
            name="description_ru",
            field=models.TextField(verbose_name="Описание (RU)"),
        ),
        migrations.AlterField(
            model_name="facultyspecialization",
            name="features_en",
            field=models.JSONField(verbose_name="Особенности (EN)"),
        ),
        migrations.AlterField(
            model_name="facultyspecialization",
            name="features_kg",
            field=models.JSONField(verbose_name="Особенности (KY)"),
        ),
        migrations.AlterField(
            model_name="facultyspecialization",
            name="features_ru",
            field=models.JSONField(verbose_name="Особенности (RU)"),
        ),
        migrations.AlterField(
            model_name="facultyspecialization",
            name="name_en",
            field=models.CharField(max_length=100, verbose_name="Название (EN)"),
        ),
        migrations.AlterField(
            model_name="facultyspecialization",
            name="name_kg",
            field=models.CharField(max_length=100, verbose_name="Название (KY)"),
        ),
        migrations.AlterField(
            model_name="facultyspecialization",
            name="name_ru",
            field=models.CharField(max_length=100, verbose_name="Название (RU)"),
        ),
        migrations.AlterField(
            model_name="facultysports",
            name="description_en",
            field=models.TextField(verbose_name="Описание (EN)"),
        ),
        migrations.AlterField(
            model_name="facultysports",
            name="description_kg",
            field=models.TextField(verbose_name="Описание (KY)"),
        ),
        migrations.AlterField(
            model_name="facultysports",
            name="description_ru",
            field=models.TextField(verbose_name="Описание (RU)"),
        ),
        migrations.AlterField(
            model_name="facultysports",
            name="emoji",
            field=models.CharField(max_length=10, verbose_name="Эмодзи"),
        ),
        migrations.AlterField(
            model_name="facultysports",
            name="name_en",
            field=models.CharField(max_length=100, verbose_name="Название (EN)"),
        ),
        migrations.AlterField(
            model_name="facultysports",
            name="name_kg",
            field=models.CharField(max_length=100, verbose_name="Название (KY)"),
        ),
        migrations.AlterField(
            model_name="facultysports",
            name="name_ru",
            field=models.CharField(max_length=100, verbose_name="Название (RU)"),
        ),
        migrations.AlterField(
            model_name="facultystatistics",
            name="meaning_en",
            field=models.CharField(max_length=100, verbose_name="Знач   ение (EN)"),
        ),
        migrations.AlterField(
            model_name="facultystatistics",
            name="meaning_kg",
            field=models.CharField(max_length=100, verbose_name="Значение (KY)"),
        ),
        migrations.AlterField(
            model_name="facultystatistics",
            name="meaning_ru",
            field=models.CharField(max_length=100, verbose_name="Значение (RU)"),
        ),
        migrations.AlterField(
            model_name="facultystatistics",
            name="titleInt",
            field=models.CharField(max_length=100, verbose_name="Заголовок (INT)"),
        ),
        migrations.AlterField(
            model_name="facultyteachers",
            name="full_name_en",
            field=models.CharField(max_length=100, verbose_name="Полное имя (EN)"),
        ),
        migrations.AlterField(
            model_name="facultyteachers",
            name="full_name_kg",
            field=models.CharField(max_length=100, verbose_name="Полное имя (KY)"),
        ),
        migrations.AlterField(
            model_name="facultyteachers",
            name="full_name_ru",
            field=models.CharField(max_length=100, verbose_name="Полное имя (RU)"),
        ),
        migrations.AlterField(
            model_name="facultyteachers",
            name="photo",
            field=models.ImageField(upload_to="faculty_teachers/", verbose_name="Фото"),
        ),
        migrations.AlterField(
            model_name="facultyteachers",
            name="position_en",
            field=models.CharField(max_length=100, verbose_name="Должность (EN)"),
        ),
        migrations.AlterField(
            model_name="facultyteachers",
            name="position_kg",
            field=models.CharField(max_length=100, verbose_name="Должность (KY)"),
        ),
        migrations.AlterField(
            model_name="facultyteachers",
            name="position_ru",
            field=models.CharField(max_length=100, verbose_name="Должность (RU)"),
        ),
        migrations.AlterField(
            model_name="masterprograms",
            name="description_en",
            field=models.TextField(verbose_name="Описание (EN)"),
        ),
        migrations.AlterField(
            model_name="masterprograms",
            name="description_kg",
            field=models.TextField(verbose_name="Описание (KY)"),
        ),
        migrations.AlterField(
            model_name="masterprograms",
            name="description_ru",
            field=models.TextField(verbose_name="Описание (RU)"),
        ),
        migrations.AlterField(
            model_name="masterprograms",
            name="duration_years",
            field=models.IntegerField(verbose_name="Продолжительность (годы)"),
        ),
        migrations.AlterField(
            model_name="masterprograms",
            name="emoji",
            field=models.CharField(max_length=10, verbose_name="Эмодзи"),
        ),
        migrations.AlterField(
            model_name="masterprograms",
            name="features_en",
            field=models.JSONField(verbose_name="Особенности (EN)"),
        ),
        migrations.AlterField(
            model_name="masterprograms",
            name="features_kg",
            field=models.JSONField(verbose_name="Особенности (KY)"),
        ),
        migrations.AlterField(
            model_name="masterprograms",
            name="features_ru",
            field=models.JSONField(verbose_name="Особенности (RU)"),
        ),
        migrations.AlterField(
            model_name="masterprograms",
            name="name_en",
            field=models.CharField(max_length=100, verbose_name="Название (EN)"),
        ),
        migrations.AlterField(
            model_name="masterprograms",
            name="name_kg",
            field=models.CharField(max_length=100, verbose_name="Название (KY)"),
        ),
        migrations.AlterField(
            model_name="masterprograms",
            name="name_ru",
            field=models.CharField(max_length=100, verbose_name="Название (RU)"),
        ),
        migrations.AlterField(
            model_name="masterprograms",
            name="offline",
            field=models.BooleanField(default=True, verbose_name="Очная форма"),
        ),
        migrations.AlterField(
            model_name="masterprograms",
            name="tuition_fee",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Стоимость обучения"
            ),
        ),
        migrations.AlterField(
            model_name="phdprograms",
            name="description_en",
            field=models.TextField(verbose_name="Описание (EN)"),
        ),
        migrations.AlterField(
            model_name="phdprograms",
            name="description_kg",
            field=models.TextField(verbose_name="Описание (KY)"),
        ),
        migrations.AlterField(
            model_name="phdprograms",
            name="description_ru",
            field=models.TextField(verbose_name="Описание (RU)"),
        ),
        migrations.AlterField(
            model_name="phdprograms",
            name="duration_years",
            field=models.IntegerField(verbose_name="Продолжительность (годы)"),
        ),
        migrations.AlterField(
            model_name="phdprograms",
            name="emoji",
            field=models.CharField(max_length=10, verbose_name="Эмодзи"),
        ),
        migrations.AlterField(
            model_name="phdprograms",
            name="features_en",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="Особенности (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="phdprograms",
            name="features_kg",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="Особенности (KY)"
            ),
        ),
        migrations.AlterField(
            model_name="phdprograms",
            name="features_ru",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="Особенности (RU)"
            ),
        ),
        migrations.AlterField(
            model_name="phdprograms",
            name="name_en",
            field=models.CharField(max_length=100, verbose_name="Название (EN)"),
        ),
        migrations.AlterField(
            model_name="phdprograms",
            name="name_kg",
            field=models.CharField(max_length=100, verbose_name="Название (KY)"),
        ),
        migrations.AlterField(
            model_name="phdprograms",
            name="name_ru",
            field=models.CharField(max_length=100, verbose_name="Название (RU)"),
        ),
        migrations.AlterField(
            model_name="phdprograms",
            name="offline",
            field=models.BooleanField(default=True, verbose_name="Очная форма"),
        ),
        migrations.AlterField(
            model_name="phdprograms",
            name="tuition_fee",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Стоимость обучения"
            ),
        ),
    ]
