# Generated by Django 5.2.7 on 2025-10-24 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0006_delete_aboutfeature_delete_aboutphoto_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EducationPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        help_text="URL identifier (e.g., coaching-faculty, general-departments)",
                        max_length=100,
                        unique=True,
                        verbose_name="URL Slug",
                    ),
                ),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("coaching_faculty", "Coaching Faculty"),
                            ("correspondence_training", "Correspondence Training"),
                            ("doctorate_program", "Doctorate Program"),
                            ("master_program", "Master Program"),
                            ("military_training", "Military Training"),
                            ("pedagogical_sports", "Pedagogical Sports"),
                            ("general_departments", "General Departments"),
                        ],
                        max_length=50,
                        verbose_name="Page Type",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=255, verbose_name="Title (RU)"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=255, verbose_name="Title (EN)"),
                ),
                (
                    "title_kg",
                    models.CharField(max_length=255, verbose_name="Title (KG)"),
                ),
                ("description_ru", models.TextField(verbose_name="Description (RU)")),
                ("description_en", models.TextField(verbose_name="Description (EN)")),
                ("description_kg", models.TextField(verbose_name="Description (KG)")),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="education_pages/",
                        verbose_name="Banner Image",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Order"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Education Page",
                "verbose_name_plural": "Education Pages",
                "ordering": ["order", "title_ru"],
            },
        ),
        migrations.AlterField(
            model_name="collegeprograms",
            name="description_kg",
            field=models.TextField(verbose_name="Описание (KG)"),
        ),
        migrations.AlterField(
            model_name="collegeprograms",
            name="features_kg",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="Особенности (KG)"
            ),
        ),
        migrations.AlterField(
            model_name="collegeprograms",
            name="name_kg",
            field=models.CharField(max_length=100, verbose_name="Название (KG)"),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="achievements_kg",
            field=models.JSONField(verbose_name="Достижения (KG)"),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="description_kg",
            field=models.TextField(verbose_name="Описание (KG)"),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="mission_kg",
            field=models.JSONField(verbose_name="Миссия (KG)"),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="name_kg",
            field=models.CharField(max_length=100, verbose_name="Название (KG)"),
        ),
        migrations.AlterField(
            model_name="facultycontacts",
            name="title_kg",
            field=models.CharField(max_length=100, verbose_name="Заголовок (KG)"),
        ),
        migrations.AlterField(
            model_name="facultyprograms",
            name="description_kg",
            field=models.TextField(verbose_name="Описание (KG)"),
        ),
        migrations.AlterField(
            model_name="facultyprograms",
            name="name_kg",
            field=models.CharField(max_length=100, verbose_name="Название (KG)"),
        ),
        migrations.AlterField(
            model_name="facultyspecialization",
            name="description_kg",
            field=models.TextField(verbose_name="Описание (KG)"),
        ),
        migrations.AlterField(
            model_name="facultyspecialization",
            name="features_kg",
            field=models.JSONField(verbose_name="Особенности (KG)"),
        ),
        migrations.AlterField(
            model_name="facultyspecialization",
            name="name_kg",
            field=models.CharField(max_length=100, verbose_name="Название (KG)"),
        ),
        migrations.AlterField(
            model_name="facultysports",
            name="description_kg",
            field=models.TextField(verbose_name="Описание (KG)"),
        ),
        migrations.AlterField(
            model_name="facultysports",
            name="name_kg",
            field=models.CharField(max_length=100, verbose_name="Название (KG)"),
        ),
        migrations.AlterField(
            model_name="facultystatistics",
            name="meaning_en",
            field=models.CharField(max_length=100, verbose_name="Значение (EN)"),
        ),
        migrations.AlterField(
            model_name="facultystatistics",
            name="meaning_kg",
            field=models.CharField(max_length=100, verbose_name="Значение (KG)"),
        ),
        migrations.AlterField(
            model_name="facultyteachers",
            name="full_name_kg",
            field=models.CharField(max_length=100, verbose_name="Полное имя (KG)"),
        ),
        migrations.AlterField(
            model_name="facultyteachers",
            name="position_kg",
            field=models.CharField(max_length=100, verbose_name="Должность (KG)"),
        ),
        migrations.AlterField(
            model_name="masterprograms",
            name="description_kg",
            field=models.TextField(verbose_name="Описание (KG)"),
        ),
        migrations.AlterField(
            model_name="masterprograms",
            name="features_kg",
            field=models.JSONField(verbose_name="Особенности (KG)"),
        ),
        migrations.AlterField(
            model_name="masterprograms",
            name="name_kg",
            field=models.CharField(max_length=100, verbose_name="Название (KG)"),
        ),
        migrations.AlterField(
            model_name="phdprograms",
            name="description_kg",
            field=models.TextField(verbose_name="Описание (KG)"),
        ),
        migrations.AlterField(
            model_name="phdprograms",
            name="features_kg",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="Особенности (KG)"
            ),
        ),
        migrations.AlterField(
            model_name="phdprograms",
            name="name_kg",
            field=models.CharField(max_length=100, verbose_name="Название (KG)"),
        ),
        migrations.CreateModel(
            name="EducationSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=255, verbose_name="Section Title (RU)"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=255, verbose_name="Section Title (EN)"),
                ),
                (
                    "title_kg",
                    models.CharField(max_length=255, verbose_name="Section Title (KG)"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Order"
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="education.educationpage",
                        verbose_name="Education Page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Education Section",
                "verbose_name_plural": "Education Sections",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="EducationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_ru",
                    models.CharField(max_length=500, verbose_name="Item Text (RU)"),
                ),
                (
                    "text_en",
                    models.CharField(max_length=500, verbose_name="Item Text (EN)"),
                ),
                (
                    "text_kg",
                    models.CharField(max_length=500, verbose_name="Item Text (KG)"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Order"
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="education.educationsection",
                        verbose_name="Section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Education Item",
                "verbose_name_plural": "Education Items",
                "ordering": ["order"],
            },
        ),
    ]
