# Generated by Django 5.2.7 on 2025-10-24 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "education",
            "0007_educationpage_alter_collegeprograms_description_kg_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="educationsection",
            name="page",
        ),
        migrations.AlterModelOptions(
            name="faculty",
            options={
                "ordering": ["order", "name_ru"],
                "verbose_name": "Факультет",
                "verbose_name_plural": "Факультеты",
            },
        ),
        migrations.AddField(
            model_name="faculty",
            name="banner_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="faculty_banners/",
                verbose_name="Баннер",
            ),
        ),
        migrations.AddField(
            model_name="faculty",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AddField(
            model_name="faculty",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AddField(
            model_name="faculty",
            name="order",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Порядок отображения"
            ),
        ),
        migrations.AddField(
            model_name="faculty",
            name="slug",
            field=models.CharField(
                blank=True,
                help_text="URL identifier (e.g., coaching-faculty)",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="URL Slug",
            ),
        ),
        migrations.AddField(
            model_name="faculty",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Дата обновления"
            ),
        ),
        migrations.CreateModel(
            name="FacultySection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        max_length=255, verbose_name="Заголовок раздела (RU)"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=255, verbose_name="Заголовок раздела (EN)"
                    ),
                ),
                (
                    "title_kg",
                    models.CharField(
                        max_length=255, verbose_name="Заголовок раздела (KG)"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок отображения"
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_sections",
                        to="education.faculty",
                        verbose_name="Факультет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Раздел факультета",
                "verbose_name_plural": "Разделы факультетов",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="FacultySectionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_ru",
                    models.CharField(
                        max_length=500, verbose_name="Текст элемента (RU)"
                    ),
                ),
                (
                    "text_en",
                    models.CharField(
                        max_length=500, verbose_name="Текст элемента (EN)"
                    ),
                ),
                (
                    "text_kg",
                    models.CharField(
                        max_length=500, verbose_name="Текст элемента (KG)"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок отображения"
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="education.facultysection",
                        verbose_name="Раздел",
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент раздела",
                "verbose_name_plural": "Элементы разделов",
                "ordering": ["order"],
            },
        ),
        migrations.DeleteModel(
            name="EducationItem",
        ),
        migrations.DeleteModel(
            name="EducationPage",
        ),
        migrations.DeleteModel(
            name="EducationSection",
        ),
    ]
