# Generated by Django 5.1.2 on 2025-11-07 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlockchainFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(default="✓", max_length=10, verbose_name="Иконка"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Функция блокчейна",
                "verbose_name_plural": "Функции блокчейна",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IPChainBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="✅", max_length=10, verbose_name="Иконка"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Преимущество",
                "verbose_name_plural": "Преимущества",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IPChainInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("subtitle", models.TextField(verbose_name="Подзаголовок")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Информация IPChain",
                "verbose_name_plural": "Информация IPChain",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IPChainStatistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Например: 1000+, 500, 99.9%",
                        max_length=50,
                        verbose_name="Значение",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Статистика",
                "verbose_name_plural": "Статистика",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Patent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="Например: PAT2024001",
                        max_length=50,
                        unique=True,
                        verbose_name="Номер патента",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Granted", "Выдан"),
                            ("Pending", "В процессе"),
                            ("Active", "Активный"),
                        ],
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("year", models.CharField(max_length=4, verbose_name="Год")),
                ("date", models.DateField(verbose_name="Дата подачи")),
                (
                    "icon",
                    models.CharField(
                        default="📄", max_length=10, verbose_name="Иконка"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Патент",
                "verbose_name_plural": "Патенты",
                "ordering": ["order", "-date"],
            },
        ),
        migrations.CreateModel(
            name="BlockchainFeatureTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("ru", "Русский"),
                            ("en", "English"),
                            ("kg", "Кыргызча"),
                        ],
                        max_length=2,
                        verbose_name="Язык",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="ipchain_app.blockchainfeature",
                        verbose_name="Функция",
                    ),
                ),
            ],
            options={
                "verbose_name": "Перевод функции",
                "verbose_name_plural": "Переводы функций",
                "unique_together": {("feature", "language")},
            },
        ),
        migrations.CreateModel(
            name="IPChainBenefitTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("ru", "Русский"),
                            ("en", "English"),
                            ("kg", "Кыргызча"),
                        ],
                        max_length=2,
                        verbose_name="Язык",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "benefit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="ipchain_app.ipchainbenefit",
                        verbose_name="Преимущество",
                    ),
                ),
            ],
            options={
                "verbose_name": "Перевод преимущества",
                "verbose_name_plural": "Переводы преимуществ",
                "unique_together": {("benefit", "language")},
            },
        ),
        migrations.CreateModel(
            name="IPChainInfoTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("ru", "Русский"),
                            ("en", "English"),
                            ("kg", "Кыргызча"),
                        ],
                        max_length=2,
                        verbose_name="Язык",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("subtitle", models.TextField(verbose_name="Подзаголовок")),
                (
                    "info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="ipchain_app.ipchaininfo",
                        verbose_name="Информация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Перевод информации",
                "verbose_name_plural": "Переводы информации",
                "unique_together": {("info", "language")},
            },
        ),
        migrations.CreateModel(
            name="IPChainStatisticTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("ru", "Русский"),
                            ("en", "English"),
                            ("kg", "Кыргызча"),
                        ],
                        max_length=2,
                        verbose_name="Язык",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Например: Защищено патентов, Пользователей",
                        max_length=200,
                        verbose_name="Название",
                    ),
                ),
                (
                    "statistic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="ipchain_app.ipchainstatistic",
                        verbose_name="Статистика",
                    ),
                ),
            ],
            options={
                "verbose_name": "Перевод статистики",
                "verbose_name_plural": "Переводы статистики",
                "unique_together": {("statistic", "language")},
            },
        ),
        migrations.CreateModel(
            name="PatentTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("ru", "Русский"),
                            ("en", "English"),
                            ("kg", "Кыргызча"),
                        ],
                        max_length=2,
                        verbose_name="Язык",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Краткое описание")),
                (
                    "full_description",
                    models.TextField(blank=True, verbose_name="Полное описание"),
                ),
                (
                    "technologies",
                    models.JSONField(
                        default=list,
                        help_text='Например: ["Blockchain", "AI"]',
                        verbose_name="Технологии",
                    ),
                ),
                (
                    "applications",
                    models.JSONField(
                        default=list,
                        help_text='Например: ["IP Protection", "Verification"]',
                        verbose_name="Применение",
                    ),
                ),
                (
                    "patent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="ipchain_app.patent",
                        verbose_name="Патент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Перевод патента",
                "verbose_name_plural": "Переводы патентов",
                "unique_together": {("patent", "language")},
            },
        ),
    ]
