# Generated by Django 5.1.2 on 2025-11-07 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipchain_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockchainData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_block",
                    models.CharField(
                        help_text="Например: 15,842,367",
                        max_length=50,
                        verbose_name="Текущий блок",
                    ),
                ),
                (
                    "ip_registrations",
                    models.CharField(
                        help_text="Например: 2,847",
                        max_length=50,
                        verbose_name="Регистраций IP",
                    ),
                ),
                (
                    "smart_contracts",
                    models.CharField(
                        help_text="Например: 1,563",
                        max_length=50,
                        verbose_name="Смарт-контрактов",
                    ),
                ),
                (
                    "network_hash",
                    models.CharField(
                        help_text="Например: 0x8f3a...c42b",
                        max_length=100,
                        verbose_name="Хэш сети",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последнее обновление"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Данные блокчейна",
                "verbose_name_plural": "Данные блокчейна",
                "ordering": ["order", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="BlockchainDataTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("ru", "Русский"),
                            ("en", "English"),
                            ("kg", "Кыргызча"),
                        ],
                        max_length=2,
                        verbose_name="Язык",
                    ),
                ),
                (
                    "current_block_label",
                    models.CharField(
                        default="Текущий блок",
                        max_length=100,
                        verbose_name="Название 'Текущий блок'",
                    ),
                ),
                (
                    "ip_registrations_label",
                    models.CharField(
                        default="Регистраций IP",
                        max_length=100,
                        verbose_name="Название 'Регистраций IP'",
                    ),
                ),
                (
                    "smart_contracts_label",
                    models.CharField(
                        default="Смарт-контрактов",
                        max_length=100,
                        verbose_name="Название 'Смарт-контрактов'",
                    ),
                ),
                (
                    "network_hash_label",
                    models.CharField(
                        default="Хэш сети",
                        max_length=100,
                        verbose_name="Название 'Хэш сети'",
                    ),
                ),
                (
                    "blockchain_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="ipchain_app.blockchaindata",
                        verbose_name="Данные блокчейна",
                    ),
                ),
            ],
            options={
                "verbose_name": "Перевод данных блокчейна",
                "verbose_name_plural": "Переводы данных блокчейна",
                "unique_together": {("blockchain_data", "language")},
            },
        ),
    ]
