# Generated by Django 5.1.2 on 2025-12-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedagogical_faculty", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="description",
        ),
        migrations.RemoveField(
            model_name="card",
            name="title",
        ),
        migrations.RemoveField(
            model_name="tabcategory",
            name="icon_svg",
        ),
        migrations.RemoveField(
            model_name="tabcategory",
            name="title",
        ),
        migrations.RemoveField(
            model_name="timelineevent",
            name="event",
        ),
        migrations.AddField(
            model_name="card",
            name="description_en",
            field=models.TextField(default="", verbose_name="Описание (English)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="card",
            name="description_kg",
            field=models.TextField(default="", verbose_name="Описание (Кыргызча)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="card",
            name="description_ru",
            field=models.TextField(default="", verbose_name="Описание (Русский)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="card",
            name="title_en",
            field=models.CharField(
                default="", max_length=200, verbose_name="Заголовок (English)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="card",
            name="title_kg",
            field=models.CharField(
                default="", max_length=200, verbose_name="Заголовок (Кыргызча)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="card",
            name="title_ru",
            field=models.CharField(
                default="", max_length=200, verbose_name="Заголовок (Русский)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tabcategory",
            name="icon",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Иконка (эмодзи)"
            ),
        ),
        migrations.AddField(
            model_name="tabcategory",
            name="title_en",
            field=models.CharField(
                default="", max_length=200, verbose_name="Заголовок (English)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tabcategory",
            name="title_kg",
            field=models.CharField(
                default="", max_length=200, verbose_name="Заголовок (Кыргызча)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tabcategory",
            name="title_ru",
            field=models.CharField(
                default="", max_length=200, verbose_name="Заголовок (Русский)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="timelineevent",
            name="event_en",
            field=models.TextField(default="", verbose_name="Событие (English)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="timelineevent",
            name="event_kg",
            field=models.TextField(default="", verbose_name="Событие (Кыргызча)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="timelineevent",
            name="event_ru",
            field=models.TextField(default="", verbose_name="Событие (Русский)"),
            preserve_default=False,
        ),
    ]
