# Generated by Django 5.1.2 on 2025-12-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogical_faculty', '0006_department_departmentstaff_management_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentstaff',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='pedagogical_faculty/departments/resumes/', verbose_name='Резюме (PDF)'),
        ),
        migrations.AlterField(
            model_name='management',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='pedagogical_faculty/management/resumes/', verbose_name='Резюме (PDF)'),
        ),
    ]
