# Generated by Django 5.1.2 on 2025-12-19 05:56

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogical_faculty', '0007_alter_departmentstaff_resume_alter_management_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutfaculty',
            name='text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст (English)'),
        ),
        migrations.AlterField(
            model_name='aboutfaculty',
            name='text_kg',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст (Кыргызча)'),
        ),
        migrations.AlterField(
            model_name='aboutfaculty',
            name='text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст (Русский)'),
        ),
        migrations.AlterField(
            model_name='department',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='description_kg',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
