# Generated by Django 5.1.2 on 2025-12-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedagogical_faculty", "0008_alter_aboutfaculty_text_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to="pedagogical_faculty/gallery/", verbose_name="Фото"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Заголовок (Русский)"
                    ),
                ),
                (
                    "title_kg",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Заголовок (Кыргызча)"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Заголовок (English)"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(blank=True, verbose_name="Описание (Русский)"),
                ),
                (
                    "description_kg",
                    models.TextField(blank=True, verbose_name="Описание (Кыргызча)"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Описание (English)"),
                ),
            ],
            options={
                "verbose_name": "Карточка галереи",
                "verbose_name_plural": "Карточки галереи",
                "ordering": ["id"],
            },
        ),
    ]
