# Generated by Django 5.1.2 on 2026-01-14 12:38

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogical_faculty', '0010_alter_gallerycard_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentstaff',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Резюме (PDF)'),
        ),
        migrations.AlterField(
            model_name='gallerycard',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Фото'),
        ),
    ]
