# Generated by Django 5.1.2 on 2025-10-23 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='announcements/', verbose_name='Изображение')),
                ('urgency', models.CharField(choices=[('high', 'Высокая'), ('medium', 'Средняя'), ('low', 'Низкая')], default='low', max_length=10, verbose_name='Срочность')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('ky', 'Кыргызча')], max_length=2, verbose_name='Язык')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('department', models.CharField(max_length=150, verbose_name='Отдел/Факультет')),
                ('content', models.TextField(blank=True, verbose_name='Полное содержание')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='announcements.announcement')),
            ],
            options={
                'verbose_name': 'Перевод объявления',
                'verbose_name_plural': 'Переводы объявлений',
                'unique_together': {('announcement', 'language')},
            },
        ),
    ]
