# Generated by Django 5.1.2 on 2026-01-14 12:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_alter_announcement_image_announcementimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='announcementimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Изображение'),
        ),
    ]
