# Generated by Django 5.1.2 on 2025-12-08 17:31

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence_faculty", "0004_alter_tabcategory_icon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timelineevent",
            name="year",
        ),
        migrations.AddField(
            model_name="timelineevent",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="Картинка"
            ),
        ),
        migrations.CreateModel(
            name="AboutFaculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_ru", models.TextField(verbose_name="Текст (Русский)")),
                ("text_kg", models.TextField(verbose_name="Текст (Кыргызча)")),
                ("text_en", models.TextField(verbose_name="Текст (English)")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tab",
                    models.ForeignKey(
                        limit_choices_to={"key": "about_faculty"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="about_faculty",
                        to="correspondence_faculty.tabcategory",
                        verbose_name="Таб",
                    ),
                ),
            ],
            options={
                "verbose_name": "О факультете",
                "verbose_name_plural": "О факультете",
                "ordering": ["order"],
            },
        ),
    ]
