# Generated by Django 5.1.2 on 2025-12-16 05:31

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "correspondence_faculty",
            "0005_remove_timelineevent_year_timelineevent_image_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Management",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="Фото"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=200, verbose_name="Имя (Русский)"),
                ),
                (
                    "name_kg",
                    models.CharField(max_length=200, verbose_name="Имя (Кыргызча)"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=200, verbose_name="Имя (English)"),
                ),
                (
                    "role_ru",
                    models.CharField(max_length=200, verbose_name="Роль (Русский)"),
                ),
                (
                    "role_kg",
                    models.CharField(max_length=200, verbose_name="Роль (Кыргызча)"),
                ),
                (
                    "role_en",
                    models.CharField(max_length=200, verbose_name="Роль (English)"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Номер телефона"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "resume",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Резюме (PDF)",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tab",
                    models.ForeignKey(
                        limit_choices_to={"key": "management"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="management",
                        to="correspondence_faculty.tabcategory",
                        verbose_name="Таб",
                    ),
                ),
            ],
            options={
                "verbose_name": "Руководство",
                "verbose_name_plural": "Руководство",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=300, verbose_name="Название (Русский)"),
                ),
                (
                    "title_kg",
                    models.CharField(
                        max_length=300, verbose_name="Название (Кыргызча)"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(max_length=300, verbose_name="Название (English)"),
                ),
                (
                    "description_ru",
                    models.TextField(blank=True, verbose_name="Описание (Русский)"),
                ),
                (
                    "description_kg",
                    models.TextField(blank=True, verbose_name="Описание (Кыргызча)"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Описание (English)"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tab",
                    models.ForeignKey(
                        limit_choices_to={"key": "specializations"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specializations",
                        to="correspondence_faculty.tabcategory",
                        verbose_name="Таб",
                    ),
                ),
            ],
            options={
                "verbose_name": "Специализация",
                "verbose_name_plural": "Специализации",
                "ordering": ["order"],
            },
        ),
    ]
