# Generated by Django 5.1.2 on 2025-12-03 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coaching_faculy", "0002_remove_card_description_remove_card_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="timelineevent",
            name="tab",
            field=models.ForeignKey(
                default="",
                limit_choices_to={"key": "history"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timeline_events",
                to="coaching_faculy.tabcategory",
                verbose_name="Таб",
            ),
            preserve_default=False,
        ),
    ]
