# Generated by Django 5.1.2 on 2025-12-04 06:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coaching_faculy", "0003_timelineevent_tab"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tabcategory",
            name="icon",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="Иконка"
            ),
        ),
    ]
