# Generated by Django 5.1.2 on 2025-12-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_faculy', '0008_gallerycard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerycard',
            name='photo',
            field=models.ImageField(max_length=255, upload_to='pedagogical_faculty/gallery/', verbose_name='Фото'),
        ),
    ]
