# Generated by Django 5.1.2 on 2026-01-14 12:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_faculy', '0009_alter_gallerycard_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerycard',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Фото'),
        ),
    ]
