# Generated by Django 5.1.2 on 2025-10-23 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='quotes/', verbose_name='Изображение автора')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Цитата',
                'verbose_name_plural': 'Цитаты',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('kg', 'Кыргызча')], max_length=2, verbose_name='Язык')),
                ('text', models.TextField(verbose_name='Текст цитаты')),
                ('author', models.CharField(max_length=200, verbose_name='Автор')),
                ('author_title', models.CharField(blank=True, max_length=200, verbose_name='Должность/титул автора')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='quotes.quote')),
            ],
            options={
                'verbose_name': 'Перевод цитаты',
                'verbose_name_plural': 'Переводы цитат',
                'unique_together': {('quote', 'language')},
            },
        ),
    ]
