# Generated by Django 5.1.2 on 2026-01-14 12:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_update_language_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Изображение автора'),
        ),
    ]
