# Generated by Django 5.1.2 on 2026-01-14 12:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerslide',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Изображение'),
        ),
    ]
